/********************************************************************
  Texture mapped area using tiling for each 30 by 30 degree area. 
  Also, Blue Earth;

  -- created by Y. Tung, 10/26/92;
  -- first make the Blue Earth;

*********************************************************************/

#ifndef GR_TAREA
#define GR_TAREA                          "GR_Tareaclass"

#include "GR_Interface.H"
#include "GR_DispObj.H"


/*
class GR_Tarea: public GR_DispObj
{
 private:
   char* p_filename;
   float p_texps[9];
   float p_tevps[1];
   int p_xsize;
   int p_ysize;
   
 protected:
   void texture_init();
   void draw_area (int n, Boolean nflag, Boolean tflag);

 public:
   GR_Tarea (char* filename=NULL, long type);
   unsigned long* take_rgbdata (char* infile);
   void objdraw ();
   //void v_process_pick (GR_MouseEvent&, GR_Window*);
};
*/

#endif
