/*
 *----------------------------------------------------------------------------
 *<
 * file:		patterns.H
 *
 * abstract:	RSD default patterns
 *
 *>
 *----------------------------------------------------------------------------
 */

#define PATTERN_SOLID								 0
#define PATTERN_one_wish_we_knew					 1
#define PATTERN_two_wish_we_knew					 2
#define PATTERN_three_wish_we_knew					 3
#define PATTERN_diag_lines_to_left_a				 4
#define PATTERN_diag_lines_to_right_a				 5
#define PATTERN_diag_lines_to_right_b				 6
#define PATTERN_diag_lines_to_left_b				 7
#define PATTERN_diag_lines_both_ways				 8
#define PATTERN_triangles							 9
#define PATTERN_wiggley								10
#define PATTERN_diag_weave							11
#define PATTERN_4x4_grid							12
#define PATTERN_8x8_grid							13
#define PATTERN_16x16_grid							14
#define PATTERN_wide_weave							15
#define PATTERN_diag_twill_a						16
#define PATTERN_diag_twill_b						17
#define PATTERN_diag_lines_to_right_2_on_2_off		18
#define PATTERN_office_talk							19
#define PATTERN_quarter_tone						20
#define PATTERN_half_tone							21

#define	PATTERN_TOP									22

