/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WNInterface */

#ifndef _Included_WNInterface
#define _Included_WNInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef WNInterface_NOUN
#define WNInterface_NOUN 1L
#undef WNInterface_VERB
#define WNInterface_VERB 2L
#undef WNInterface_ADJ
#define WNInterface_ADJ 3L
#undef WNInterface_ADV
#define WNInterface_ADV 4L
#undef WNInterface_SATELLITE
#define WNInterface_SATELLITE 5L
#undef WNInterface_ADJSAT
#define WNInterface_ADJSAT 5L
/* Inaccessible static: POS_STRINGS */
#undef WNInterface_ALLSENSES
#define WNInterface_ALLSENSES 0L
#undef WNInterface_MAXID
#define WNInterface_MAXID 15L
#undef WNInterface_MAXDEPTH
#define WNInterface_MAXDEPTH 20L
#undef WNInterface_MAXSENSE
#define WNInterface_MAXSENSE 75L
#undef WNInterface_MAX_FORMS
#define WNInterface_MAX_FORMS 5L
#undef WNInterface_MAXFNUM
#define WNInterface_MAXFNUM 44L
#undef WNInterface_MAXPTR
#define WNInterface_MAXPTR 19L
#undef WNInterface_MAXSEARCH
#define WNInterface_MAXSEARCH 29L
#undef WNInterface_ANTPTR
#define WNInterface_ANTPTR 1L
#undef WNInterface_HYPERPTR
#define WNInterface_HYPERPTR 2L
#undef WNInterface_HYPOPTR
#define WNInterface_HYPOPTR 3L
#undef WNInterface_ENTAILPTR
#define WNInterface_ENTAILPTR 4L
#undef WNInterface_SIMPTR
#define WNInterface_SIMPTR 5L
#undef WNInterface_ISMEMBERPTR
#define WNInterface_ISMEMBERPTR 6L
#undef WNInterface_ISSTUFFPTR
#define WNInterface_ISSTUFFPTR 7L
#undef WNInterface_ISPARTPTR
#define WNInterface_ISPARTPTR 8L
#undef WNInterface_HASMEMBERPTR
#define WNInterface_HASMEMBERPTR 9L
#undef WNInterface_HASSTUFFPTR
#define WNInterface_HASSTUFFPTR 10L
#undef WNInterface_HASPARTPTR
#define WNInterface_HASPARTPTR 11L
#undef WNInterface_MERONYM
#define WNInterface_MERONYM 12L
#undef WNInterface_HOLONYM
#define WNInterface_HOLONYM 13L
#undef WNInterface_CAUSETO
#define WNInterface_CAUSETO 14L
#undef WNInterface_PPLPTR
#define WNInterface_PPLPTR 15L
#undef WNInterface_SEEALSOPTR
#define WNInterface_SEEALSOPTR 16L
#undef WNInterface_PERTPTR
#define WNInterface_PERTPTR 17L
#undef WNInterface_ATTRIBUTE
#define WNInterface_ATTRIBUTE 18L
#undef WNInterface_VERBGROUP
#define WNInterface_VERBGROUP 19L
#undef WNInterface_SYNS
#define WNInterface_SYNS 20L
#undef WNInterface_FREQ
#define WNInterface_FREQ 21L
#undef WNInterface_FRAMES
#define WNInterface_FRAMES 22L
#undef WNInterface_COORDS
#define WNInterface_COORDS 23L
#undef WNInterface_RELATIVES
#define WNInterface_RELATIVES 24L
#undef WNInterface_HMERONYM
#define WNInterface_HMERONYM 25L
#undef WNInterface_HHOLONYM
#define WNInterface_HHOLONYM 26L
#undef WNInterface_WNESCORT
#define WNInterface_WNESCORT 27L
#undef WNInterface_WNGREP
#define WNInterface_WNGREP 28L
#undef WNInterface_OVERVIEW
#define WNInterface_OVERVIEW 29L
#undef WNInterface_NUMPARTS
#define WNInterface_NUMPARTS 4L
#undef WNInterface_NUMFRAMES
#define WNInterface_NUMFRAMES 35L
#undef WNInterface_NUM_SIM_WORD_TYPES
#define WNInterface_NUM_SIM_WORD_TYPES 4L
#undef WNInterface_SIM
#define WNInterface_SIM 0L
#undef WNInterface_PARENT
#define WNInterface_PARENT 0L
#undef WNInterface_POS
#define WNInterface_POS 1L
#undef WNInterface_DEF
#define WNInterface_DEF 2L
#undef WNInterface_EXAMPLE
#define WNInterface_EXAMPLE 3L
#undef WNInterface_SENSE_NUMBER
#define WNInterface_SENSE_NUMBER 4L
/*
 * Class:     WNInterface
 * Method:    ttt_wninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_WNInterface_ttt_1wninit
  (JNIEnv *, jobject);

/*
 * Class:     WNInterface
 * Method:    wninitFoo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_WNInterface_wninitFoo
  (JNIEnv *, jobject);

/*
 * Class:     WNInterface
 * Method:    findtheinfo
 * Signature: (Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_WNInterface_findtheinfo
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     WNInterface
 * Method:    findAllTheInfo
 * Signature: (Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_WNInterface_findAllTheInfo
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     WNInterface
 * Method:    getDefinitions
 * Signature: (Ljava/lang/String;III)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_WNInterface_getDefinitions
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     WNInterface
 * Method:    getJustWords
 * Signature: (Ljava/lang/String;III)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_WNInterface_getJustWords
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     WNInterface
 * Method:    getMorphForms
 * Signature: (Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_WNInterface_getMorphForms
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
