/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "CBPforms.h"

static FL_PUP_ENTRY fdchoice_gen_weighting_0[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "Low",	0,	"",	 FL_PUP_NONE},
    { "Medium",	0,	"",	 FL_PUP_NONE},
    { "High",	0,	"",	 FL_PUP_NONE},
    { "Weight",	0,	"",	 FL_PUP_NONE},
    { "Must Have",	0,	"",	 FL_PUP_NONE},
    { "Not",	0,	"",	 FL_PUP_NONE},
    {0}
};

static FL_PUP_ENTRY fdmenu_jcs_orders_1[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "JCS 04/24/00 09:18",	0,	"",	 FL_PUP_NONE},
    { "JCS 04/19/00 14:27",	0,	"",	 FL_PUP_NONE},
    {0}
};

static FL_PUP_ENTRY fdmenu_cbp_view_2[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "COA View",	0,	"",	 FL_PUP_RADIO},
    { "Map View",	0,	"",	 FL_PUP_RADIO},
    { "Plan View",	0,	"",	 FL_PUP_RADIO},
    {0}
};

static FL_PUP_ENTRY fdmenu_Options_3[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "Default Weighting",	0,	"",	 FL_PUP_CHECK},
    { "Quick Search",	0,	"",	 FL_PUP_CHECK},
    { "Optimize Search",	0,	"",	 FL_PUP_CHECK},
    { "Repair Solution",	0,	"",	 FL_PUP_CHECK},
    { "Manual Edit",	0,	"",	 FL_PUP_CHECK},
    { "View",	0,	"",	 FL_PUP_GRAY},
    { "Integrated",	0,	"",	 FL_PUP_RADIO},
    { "Defense",	0,	"",	 FL_PUP_RADIO},
    { "Offense",	0,	"",	 FL_PUP_RADIO},
    {0}
};

FD_cbpinput *create_form_cbpinput(void)
{
  FL_OBJECT *obj;
  FD_cbpinput *fdui = (FD_cbpinput *) fl_calloc(1, sizeof(*fdui));

  fdui->cbpinput = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  obj = fl_add_box(FL_BORDER_BOX,5,330,630,120,"");
    fl_set_object_color(obj,FL_DODGERBLUE,FL_COL1);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_box(FL_BORDER_BOX,5,205,630,120,"");
    fl_set_object_color(obj,FL_TOMATO,FL_COL1);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_box(FL_BORDER_BOX,5,80,630,120,"");
    fl_set_object_color(obj,FL_SPRINGGREEN,FL_COL1);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->cbp_caseid = obj = fl_add_input(FL_NORMAL_INPUT,45,10,140,30,"Input  \nName:");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,430,10,70,30,"Clear");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseCB,1);
  fdui->cbp_save = obj = fl_add_button(FL_NORMAL_BUTTON,360,10,70,30,"Save");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseCB,4);
  fdui->cbp_exec = obj = fl_add_button(FL_NORMAL_BUTTON,575,55,60,20,"Search");
    fl_set_object_color(obj,FL_WHITE,FL_COL1);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,jcsordersCB,5);
  obj = fl_add_button(FL_NORMAL_BUTTON,765,10,70,30,"Exit");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPexitCB,0);
  fdui->gen_weighting = obj = fl_add_choice(FL_NORMAL_CHOICE2,780,85,60,20,"");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,genweightCB,0);
    fl_set_choice_entries(obj, fdchoice_gen_weighting_0);
    fl_set_choice(obj,4);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,45,820,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,640,55,10,400,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->jcs_orders = obj = fl_add_menu(FL_PULLDOWN_MENU,195,10,80,30,"Load Order");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_callback(obj,jcsordersCB,0);
    fl_set_menu_entries(obj, fdmenu_jcs_orders_1);
  fdui->view_order = obj = fl_add_button(FL_NORMAL_BUTTON,575,10,80,30,"View Order");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,jcsordersCB,1);
  fdui->gen_select = obj = fl_add_lightbutton(FL_RADIO_BUTTON,690,390,120,20,"Toggle Selection");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,genselectCB,0);
  fdui->user_default = obj = fl_add_button(FL_NORMAL_BUTTON,275,10,80,30,"Load Criteria");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseCB,3);
  fdui->cbp_view = obj = fl_add_menu(FL_PUSH_MENU,655,10,70,30,"View Menu");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_callback(obj,coaviewCB,0);
    fl_set_menu_entries(obj, fdmenu_cbp_view_2);
  fdui->gen_thumb = obj = fl_add_slider(FL_HOR_NICE_SLIDER,710,85,70,20,"");
    fl_set_object_callback(obj,genweightCB,1);
    fl_set_slider_size(obj, 0.15);
  fdui->category = obj = fl_add_choice(FL_NORMAL_CHOICE2,650,55,190,20,"");
    fl_set_object_callback(obj,catselectCB,0);
  fdui->cbp_criteria = obj = fl_add_input(FL_NORMAL_INPUT,50,55,520,20,"Criteria");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->cbp_goallist[0] = obj = fl_add_browser(FL_NORMAL_BROWSER,75,100,130,70,"Strategic");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,0);
  fdui->cbp_goallist[3] = obj = fl_add_browser(FL_NORMAL_BROWSER,495,100,130,70,"Task");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,3);
  fdui->cbp_goallist[2] = obj = fl_add_browser(FL_NORMAL_BROWSER,355,100,130,70,"Tactical");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,2);
  fdui->cbp_goallist[1] = obj = fl_add_browser(FL_NORMAL_BROWSER,215,100,130,70,"Operational");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,1);
  fdui->cbp_threatlist[0] = obj = fl_add_browser(FL_NORMAL_BROWSER,75,225,130,70,"Region");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,10);
  fdui->cbp_threatlist[1] = obj = fl_add_browser(FL_NORMAL_BROWSER,215,225,130,70,"Nation");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,11);
  fdui->cbp_threatlist[2] = obj = fl_add_browser(FL_NORMAL_BROWSER,355,225,130,70,"City");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,12);
  fdui->cbp_threatlist[3] = obj = fl_add_browser(FL_NORMAL_BROWSER,495,225,130,70,"Name");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,13);
  fdui->cbp_assetlist[0] = obj = fl_add_browser(FL_NORMAL_BROWSER,75,350,130,70,"Defended");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,20);
  fdui->cbp_assetlist[1] = obj = fl_add_browser(FL_NORMAL_BROWSER,215,350,130,70,"Weapons");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,21);
  fdui->cbp_assetlist[2] = obj = fl_add_browser(FL_NORMAL_BROWSER,355,350,130,70,"Participants");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,22);
  fdui->cbp_assetlist[3] = obj = fl_add_browser(FL_NORMAL_BROWSER,495,350,130,70,"Sources");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,goallistCB,23);
  fdui->cbp_cats[0] = obj = fl_add_text(FL_NORMAL_TEXT,10,130,60,20,"Goals");
    fl_set_object_color(obj,FL_SPRINGGREEN,FL_MCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->cbp_cats[1] = obj = fl_add_text(FL_NORMAL_TEXT,10,250,60,20,"Threats");
    fl_set_object_color(obj,FL_TOMATO,FL_MCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->cbp_cats[2] = obj = fl_add_text(FL_NORMAL_TEXT,10,380,60,20,"Assets");
    fl_set_object_color(obj,FL_DODGERBLUE,FL_MCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_menu(FL_PULLDOWN_MENU,675,430,140,20,"Options");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_callback(obj,controlparmsCB,0);
    fl_set_menu_entries(obj, fdmenu_Options_3);
  fdui->indice_browser = obj = fl_add_browser(FL_SELECT_BROWSER,650,110,190,310,"Keywords\n& Weights");
    fl_set_object_color(obj,FL_TOP_BCOL,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,genbrowserCB,0);
  fdui->morekeys[0][0] = obj = fl_add_button(FL_NORMAL_BUTTON,190,85,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,0);
  fdui->lesskeys[0][0] = obj = fl_add_button(FL_NORMAL_BUTTON,175,85,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,0);
  fdui->morekeys[0][1] = obj = fl_add_button(FL_NORMAL_BUTTON,330,85,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,1);
  fdui->morekeys[0][2] = obj = fl_add_button(FL_NORMAL_BUTTON,470,85,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,2);
  fdui->morekeys[0][3] = obj = fl_add_button(FL_NORMAL_BUTTON,610,85,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,3);
  fdui->morekeys[1][0] = obj = fl_add_button(FL_NORMAL_BUTTON,190,210,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,10);
  fdui->morekeys[1][1] = obj = fl_add_button(FL_NORMAL_BUTTON,330,210,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,11);
  fdui->morekeys[1][2] = obj = fl_add_button(FL_NORMAL_BUTTON,470,210,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,12);
  fdui->morekeys[1][3] = obj = fl_add_button(FL_NORMAL_BUTTON,610,210,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,13);
  fdui->morekeys[2][0] = obj = fl_add_button(FL_NORMAL_BUTTON,190,335,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,20);
  fdui->morekeys[2][1] = obj = fl_add_button(FL_NORMAL_BUTTON,330,335,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,21);
  fdui->morekeys[2][2] = obj = fl_add_button(FL_NORMAL_BUTTON,470,335,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,22);
  fdui->morekeys[2][3] = obj = fl_add_button(FL_NORMAL_BUTTON,610,335,15,15,">");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,morekeysCB,23);
  fdui->lesskeys[0][1] = obj = fl_add_button(FL_NORMAL_BUTTON,315,85,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,1);
  fdui->lesskeys[0][2] = obj = fl_add_button(FL_NORMAL_BUTTON,455,85,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,2);
  fdui->lesskeys[0][3] = obj = fl_add_button(FL_NORMAL_BUTTON,595,85,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,3);
  fdui->lesskeys[1][0] = obj = fl_add_button(FL_NORMAL_BUTTON,175,210,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,10);
  fdui->lesskeys[1][1] = obj = fl_add_button(FL_NORMAL_BUTTON,315,210,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,11);
  fdui->lesskeys[1][2] = obj = fl_add_button(FL_NORMAL_BUTTON,455,210,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,12);
  fdui->lesskeys[1][3] = obj = fl_add_button(FL_NORMAL_BUTTON,595,210,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,13);
  fdui->lesskeys[2][0] = obj = fl_add_button(FL_NORMAL_BUTTON,175,335,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,20);
  fdui->lesskeys[2][1] = obj = fl_add_button(FL_NORMAL_BUTTON,315,335,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,21);
  fdui->lesskeys[2][2] = obj = fl_add_button(FL_NORMAL_BUTTON,455,335,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,22);
  fdui->lesskeys[2][3] = obj = fl_add_button(FL_NORMAL_BUTTON,595,335,15,15,"<");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,lesskeysCB,23);
  fl_end_form();

  fdui->cbpinput->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_caseinfo *create_form_caseinfo(void)
{
  FL_OBJECT *obj;
  FD_caseinfo *fdui = (FD_caseinfo *) fl_calloc(1, sizeof(*fdui));

  fdui->caseinfo = fl_bgn_form(FL_NO_BOX, 391, 451);
  obj = fl_add_box(FL_UP_BOX,0,0,391,451,"");
  obj = fl_add_text(FL_NORMAL_TEXT,10,150,100,20,"Date Case Built:");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,10,180,100,20,"Date Last Used:");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,10,210,100,20,"No. times used:");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,10,240,100,20,"% indices used:");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->info_ok = obj = fl_add_button(FL_NORMAL_BUTTON,100,400,60,30,"OK");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseCB,8);
  fdui->info_cancel = obj = fl_add_button(FL_NORMAL_BUTTON,230,400,60,30,"Cancel");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseCB,9);
  fdui->info_caseid = obj = fl_add_input(FL_NORMAL_INPUT,110,60,260,20,"Case ID:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseinfoCB,2);
  fdui->info_desc = obj = fl_add_input(FL_NORMAL_INPUT,110,90,260,20,"Case Description:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseinfoCB,3);
  fdui->info_prep = obj = fl_add_input(FL_NORMAL_INPUT,110,120,260,20,"Case Preparer:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseinfoCB,4);
  fdui->info_bilt = obj = fl_add_text(FL_NORMAL_TEXT,110,150,140,20,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_callback(obj,caseinfoCB,5);
  fdui->info_last = obj = fl_add_text(FL_NORMAL_TEXT,110,180,140,20,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_callback(obj,caseinfoCB,6);
  fdui->info_used = obj = fl_add_text(FL_NORMAL_TEXT,110,210,40,20,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_callback(obj,caseinfoCB,7);
  fdui->info_percent = obj = fl_add_text(FL_NORMAL_TEXT,110,240,40,20,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_callback(obj,caseinfoCB,8);
  fdui->info_low = obj = fl_add_input(FL_FLOAT_INPUT,110,300,70,20,"Default 'Low':");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseinfoCB,9);
  fdui->info_med = obj = fl_add_input(FL_FLOAT_INPUT,110,330,70,20,"Default 'Medium':");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseinfoCB,10);
  fdui->info_high = obj = fl_add_input(FL_FLOAT_INPUT,110,360,70,20,"Default 'High':");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseinfoCB,11);
  fl_end_form();

  fdui->caseinfo->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_cbpview *create_form_cbpview(void)
{
  FL_OBJECT *obj;
  FD_cbpview *fdui = (FD_cbpview *) fl_calloc(1, sizeof(*fdui));

  fdui->cbpview = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  obj = fl_add_button(FL_NORMAL_BUTTON,760,20,80,30,"Dismiss");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,viewdoneCB,0);
  fdui->view_browser = obj = fl_add_browser(FL_NORMAL_BROWSER,10,60,830,390,"");
    fl_set_object_color(obj,FL_WHITE,FL_YELLOW);
    fl_set_object_callback(obj,viewbrowserCB,0);
  fl_end_form();

  fdui->cbpview->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_cbpmapview *create_form_cbpmapview(void)
{
  FL_OBJECT *obj;
  FD_cbpmapview *fdui = (FD_cbpmapview *) fl_calloc(1, sizeof(*fdui));

  fdui->cbpmapview = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  obj = fl_add_pixmap(FL_NORMAL_PIXMAP,90,65,670,390,"");
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/planmapback.xpm");
  fdui->cbpmap_caseid = obj = fl_add_input(FL_NORMAL_INPUT,90,20,140,30,"Case ID:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,760,20,70,30,"Dismiss");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,COAexitCB,1);
  fdui->pix_icon[2] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,160,30,30,"UEWR");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/uewr.xpm");
  fdui->pix_icon[3] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,205,30,30,"Sensor");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/sensor.xpm");
  fdui->pix_icon[4] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,250,30,30,"XBR");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,60,820,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_icon[1] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,115,30,30,"DSP");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/dsp.xpm");
  fdui->pix_count[1] = obj = fl_add_text(FL_NORMAL_TEXT,50,120,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[2] = obj = fl_add_text(FL_NORMAL_TEXT,50,165,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[3] = obj = fl_add_text(FL_NORMAL_TEXT,50,210,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[4] = obj = fl_add_text(FL_NORMAL_TEXT,50,255,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_icon[5] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,295,30,30,"Recon");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/SpySat.xpm");
  fdui->pix_icon[11] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,205,30,30,"Aegis");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/Aegis.xpm");
  fdui->pix_icon[12] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,250,30,30,"PAC3");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/PAC3.xpm");
  fdui->pix_count[5] = obj = fl_add_text(FL_NORMAL_TEXT,50,300,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[8] = obj = fl_add_text(FL_NORMAL_TEXT,770,80,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[9] = obj = fl_add_text(FL_NORMAL_TEXT,770,120,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_icon[8] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,70,30,30,"GBI");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  fdui->pix_icon[9] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,115,30,30,"Sub");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  fdui->pix_icon[10] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,160,30,30,"Bomber");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/bomber.xpm");
  fdui->pix_icon[13] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,295,30,30,"Thaad");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  fdui->pix_icon[14] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,340,30,30,"Fighter");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  fdui->pix_icon[6] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,340,30,30,"AWACS");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  fdui->pix_count[6] = obj = fl_add_text(FL_NORMAL_TEXT,50,345,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[10] = obj = fl_add_text(FL_NORMAL_TEXT,770,165,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[11] = obj = fl_add_text(FL_NORMAL_TEXT,770,210,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[12] = obj = fl_add_text(FL_NORMAL_TEXT,770,255,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[13] = obj = fl_add_text(FL_NORMAL_TEXT,770,300,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_count[14] = obj = fl_add_text(FL_NORMAL_TEXT,770,345,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_icon[0] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,70,30,30,"SBIRS");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/sbirs.xpm");
  fdui->pix_count[0] = obj = fl_add_text(FL_NORMAL_TEXT,50,75,30,20,"(1)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_icon[7] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,10,390,30,30,"AWACS");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  fdui->pix_count[7] = obj = fl_add_text(FL_NORMAL_TEXT,50,390,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->pix_icon[15] = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,810,390,30,30,"Fighter");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/xbr.xpm");
  fdui->pix_count[15] = obj = fl_add_text(FL_NORMAL_TEXT,770,395,30,20,"(0)");
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fl_end_form();

  fdui->cbpmapview->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_cbpcoaview *create_form_cbpcoaview(void)
{
  FL_OBJECT *obj;
  FD_cbpcoaview *fdui = (FD_cbpcoaview *) fl_calloc(1, sizeof(*fdui));

  fdui->cbpcoaview = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  fdui->cbpcoa_caseid = obj = fl_add_input(FL_NORMAL_INPUT,80,10,140,30,"Case ID:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,760,10,70,30,"Dismiss");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,COAexitCB,0);

  fdui->verttext = fl_bgn_group();
  obj = fl_add_text(FL_NORMAL_TEXT,10,140,20,20,"S");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,160,20,20,"E");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,180,20,20,"L");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,200,20,20,"E");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,220,20,20,"C");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,240,20,20,"T");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,290,20,20,"C");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,310,20,20,"R");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,330,20,20,"I");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,350,20,20,"T");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,370,20,20,"E");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,390,20,20,"R");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,410,20,20,"I");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,10,430,20,20,"A");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fl_end_group();

  obj = fl_add_frame(FL_SHADOW_FRAME,10,140,20,310,"");
    fl_set_object_color(obj,FL_RIGHT_BCOL,FL_COL1);
  fdui->coa_top[0] = obj = fl_add_text(FL_NORMAL_TEXT,40,150,20,100,"S\nT\nR\nA\nT\nE\nG\nY");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_top[1] = obj = fl_add_text(FL_NORMAL_TEXT,40,265,20,90,"T\nH\nR\nE\nA\nT");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_top[2] = obj = fl_add_text(FL_NORMAL_TEXT,40,370,20,80,"A\nS\nS\nE\nT\nS");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_assets[3] = obj = fl_add_text(FL_NORMAL_TEXT,60,430,100,20,"Weapon Types");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_assets[2] = obj = fl_add_text(FL_NORMAL_TEXT,60,410,100,20,"Weapon Classes");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_assets[1] = obj = fl_add_text(FL_NORMAL_TEXT,60,390,90,20,"Sensors");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_assets[0] = obj = fl_add_text(FL_NORMAL_TEXT,60,370,100,20,"Defended Areas");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_threat[3] = obj = fl_add_text(FL_NORMAL_TEXT,60,330,100,20,"Enemy Platforms");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_threat[2] = obj = fl_add_text(FL_NORMAL_TEXT,60,310,100,20,"Enemy Weapons");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_threat[1] = obj = fl_add_text(FL_NORMAL_TEXT,60,290,90,20,"Nation/State");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coasub_threat[0] = obj = fl_add_text(FL_NORMAL_TEXT,60,270,90,20,"Characteristics");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_class[0] = obj = fl_add_text(FL_NORMAL_TEXT,60,170,90,20,"Mission");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_class[1] = obj = fl_add_text(FL_NORMAL_TEXT,60,190,90,20,"Effects");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_class[2] = obj = fl_add_text(FL_NORMAL_TEXT,60,210,90,20,"Objectives");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,40,255,610,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,40,355,610,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,160,60,10,390,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->cbp_score[2] = obj = fl_add_button(FL_NORMAL_BUTTON,180,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,2);
  obj = fl_add_text(FL_NORMAL_TEXT,660,60,70,40,"Matched\nCases From\nCase Base");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,660,145,180,20,"Overall Case vs Criteria Score (%)");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->cbp_score[1] = obj = fl_add_button(FL_NORMAL_BUTTON,180,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,1);
  fdui->cbp_score[0] = obj = fl_add_button(FL_NORMAL_BUTTON,180,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  fdui->cbp_score[15] = obj = fl_add_button(FL_NORMAL_BUTTON,240,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,15);
  fdui->cbp_score[5] = obj = fl_add_button(FL_NORMAL_BUTTON,180,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,5);
  fdui->cbp_score[6] = obj = fl_add_button(FL_NORMAL_BUTTON,180,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,6);
  fdui->cbp_score[7] = obj = fl_add_button(FL_NORMAL_BUTTON,180,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,7);
  fdui->cbp_score[8] = obj = fl_add_button(FL_NORMAL_BUTTON,180,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,8);
  fdui->cbp_score[10] = obj = fl_add_button(FL_NORMAL_BUTTON,180,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,10);
  fdui->cbp_score[11] = obj = fl_add_button(FL_NORMAL_BUTTON,180,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,11);
  fdui->cbp_score[12] = obj = fl_add_button(FL_NORMAL_BUTTON,180,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,12);
  fdui->cbp_score[13] = obj = fl_add_button(FL_NORMAL_BUTTON,180,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,13);
  obj = fl_add_button(FL_NORMAL_BUTTON,240,10,130,30,"View Tasking Order");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,jcsordersCB,1);
  fdui->coa_score[0] = obj = fl_add_text(FL_NORMAL_TEXT,180,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_score[1] = obj = fl_add_text(FL_NORMAL_TEXT,240,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,1);
  fdui->coa_score[3] = obj = fl_add_text(FL_NORMAL_TEXT,360,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,10);
  fdui->coa_score[4] = obj = fl_add_text(FL_NORMAL_TEXT,420,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,11);
  fdui->coa_score[5] = obj = fl_add_text(FL_NORMAL_TEXT,480,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,12);
  fdui->coa_score[6] = obj = fl_add_text(FL_NORMAL_TEXT,540,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_score[7] = obj = fl_add_text(FL_NORMAL_TEXT,600,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,21);
  fdui->cbp_score[3] = obj = fl_add_button(FL_NORMAL_BUTTON,180,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,3);
  fdui->coa_class[3] = obj = fl_add_text(FL_NORMAL_TEXT,60,230,90,20,"Emphasis");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->coa_score[2] = obj = fl_add_text(FL_NORMAL_TEXT,300,145,40,20,"N/A");
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,2);
  fdui->cbp_score[16] = obj = fl_add_button(FL_NORMAL_BUTTON,240,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,16);
  fdui->cbp_score[17] = obj = fl_add_button(FL_NORMAL_BUTTON,240,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,17);
  fdui->cbp_score[18] = obj = fl_add_button(FL_NORMAL_BUTTON,240,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,18);
  fdui->cbp_score[20] = obj = fl_add_button(FL_NORMAL_BUTTON,240,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,20);
  fdui->cbp_score[21] = obj = fl_add_button(FL_NORMAL_BUTTON,240,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,21);
  fdui->cbp_score[22] = obj = fl_add_button(FL_NORMAL_BUTTON,240,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,22);
  fdui->cbp_score[23] = obj = fl_add_button(FL_NORMAL_BUTTON,240,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,23);
  fdui->cbp_score[25] = obj = fl_add_button(FL_NORMAL_BUTTON,240,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,25);
  fdui->cbp_score[26] = obj = fl_add_button(FL_NORMAL_BUTTON,240,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,26);
  fdui->cbp_score[27] = obj = fl_add_button(FL_NORMAL_BUTTON,240,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,27);
  fdui->cbp_score[28] = obj = fl_add_button(FL_NORMAL_BUTTON,240,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,28);
  fdui->cbp_score[30] = obj = fl_add_button(FL_NORMAL_BUTTON,300,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,30);
  fdui->cbp_score[31] = obj = fl_add_button(FL_NORMAL_BUTTON,300,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,31);
  fdui->cbp_score[32] = obj = fl_add_button(FL_NORMAL_BUTTON,300,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,32);
  fdui->cbp_score[33] = obj = fl_add_button(FL_NORMAL_BUTTON,300,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,33);
  fdui->cbp_score[35] = obj = fl_add_button(FL_NORMAL_BUTTON,300,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,35);
  fdui->cbp_score[36] = obj = fl_add_button(FL_NORMAL_BUTTON,300,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,36);
  fdui->cbp_score[37] = obj = fl_add_button(FL_NORMAL_BUTTON,300,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,37);
  fdui->cbp_score[38] = obj = fl_add_button(FL_NORMAL_BUTTON,300,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,38);
  fdui->cbp_score[40] = obj = fl_add_button(FL_NORMAL_BUTTON,300,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,40);
  fdui->cbp_score[41] = obj = fl_add_button(FL_NORMAL_BUTTON,300,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,41);
  fdui->cbp_score[42] = obj = fl_add_button(FL_NORMAL_BUTTON,300,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,42);
  fdui->cbp_score[43] = obj = fl_add_button(FL_NORMAL_BUTTON,300,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,43);
  fdui->cbp_score[45] = obj = fl_add_button(FL_NORMAL_BUTTON,360,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,45);
  fdui->cbp_case_select = obj = fl_add_input(FL_NORMAL_INPUT,665,185,170,20,"Selected Case ID");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->cbp_case_active = obj = fl_add_browser(FL_NORMAL_BROWSER,665,230,170,220,"Selected Case Active Keywords");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->case_name[0] = obj = fl_add_button(FL_NORMAL_BUTTON,190,60,20,80,"C\na\ns\ne\n \n1");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,0);
  fdui->case_name[1] = obj = fl_add_button(FL_NORMAL_BUTTON,250,60,20,80,"C\na\ns\ne\n \n2");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,1);
  fdui->case_name[2] = obj = fl_add_button(FL_NORMAL_BUTTON,310,60,20,80,"C\na\ns\ne\n \n3");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,2);
  fdui->case_name[3] = obj = fl_add_button(FL_NORMAL_BUTTON,370,60,20,80,"C\na\ns\ne\n \n4");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,3);
  fdui->case_name[4] = obj = fl_add_button(FL_NORMAL_BUTTON,430,60,20,80,"C\na\ns\ne\n \n5");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,4);
  fdui->case_name[5] = obj = fl_add_button(FL_NORMAL_BUTTON,490,60,20,80,"C\na\ns\ne\n \n6");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,5);
  fdui->case_name[6] = obj = fl_add_button(FL_NORMAL_BUTTON,550,60,20,80,"C\na\ns\ne\n \n7");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,6);
  fdui->case_name[7] = obj = fl_add_button(FL_NORMAL_BUTTON,610,60,20,80,"C\na\ns\ne\n \n8");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,caseselectCB,7);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,15,80,70,20,"0-1%");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_WHITE,FL_WHITE);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,15,100,70,20,"1-50%");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_TOMATO,FL_TOMATO);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,85,100,70,20,"85-100%");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_GREEN);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,85,80,70,20,"50-85%");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_WHEAT,FL_WHEAT);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,50,830,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,600,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,170,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,540,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,480,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,420,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,190,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,210,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,230,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,270,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,290,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,310,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,330,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,370,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,390,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,410,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,360,430,40,20,"N/A");
    fl_set_object_color(obj,FL_LEFT_BCOL,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cbpscoreCB,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,10,70,150,60,"Score Legend");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,645,145,20,20,"@<-");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_button(FL_NORMAL_BUTTON,645,80,20,20,"@<-");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_text(FL_NORMAL_TEXT,655,100,80,40,"Select desired \ncase by left\nclicking on it.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fl_end_form();

  fdui->cbpcoaview->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_cbprdeinput *create_form_cbprdeinput(void)
{
  FL_OBJECT *obj;
  FD_cbprdeinput *fdui = (FD_cbprdeinput *) fl_calloc(1, sizeof(*fdui));

  fdui->cbprdeinput = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  obj = fl_add_button(FL_NORMAL_BUTTON,750,20,80,30,"Dismiss");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,COAexitCB,2);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,260,70,10,380,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->vu_jcs_warn = obj = fl_add_button(FL_NORMAL_BUTTON,25,260,220,30,"View Tasking Order");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,jcsordersCB,1);
  fdui->rde_jcswo = obj = fl_add_text(FL_NORMAL_TEXT,10,70,250,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[0] = obj = fl_add_text(FL_NORMAL_TEXT,30,90,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[1] = obj = fl_add_text(FL_NORMAL_TEXT,30,110,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_coaper[0] = obj = fl_add_text(FL_NORMAL_TEXT,210,90,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_coaper[1] = obj = fl_add_text(FL_NORMAL_TEXT,210,110,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_coaper[3] = obj = fl_add_text(FL_NORMAL_TEXT,210,150,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_coaper[4] = obj = fl_add_text(FL_NORMAL_TEXT,210,170,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_coaper[5] = obj = fl_add_text(FL_NORMAL_TEXT,210,190,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_coaper[6] = obj = fl_add_text(FL_NORMAL_TEXT,210,210,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_coaper[7] = obj = fl_add_text(FL_NORMAL_TEXT,210,230,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[3] = obj = fl_add_text(FL_NORMAL_TEXT,30,150,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[6] = obj = fl_add_text(FL_NORMAL_TEXT,30,210,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[4] = obj = fl_add_text(FL_NORMAL_TEXT,30,170,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[7] = obj = fl_add_text(FL_NORMAL_TEXT,30,230,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[5] = obj = fl_add_text(FL_NORMAL_TEXT,30,190,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,60,820,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->cbprde_caseid = obj = fl_add_input(FL_NORMAL_INPUT,70,20,140,20,"Case ID:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  fdui->rde_coaper[2] = obj = fl_add_text(FL_NORMAL_TEXT,210,130,50,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,290,435,500,20,"(N) = Nuclear     (C) = Conventional     (V) = Covert     (B) = Biological     (H) = Chemical");
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  fdui->rde_jcscoa[2] = obj = fl_add_text(FL_NORMAL_TEXT,30,130,170,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,RDEnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,90,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,110,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,1);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,130,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,2);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,150,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,3);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,170,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,4);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,190,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,5);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,210,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,6);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,230,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdehelpCB,7);
  fdui->ro_browser = obj = fl_add_browser(FL_HOLD_BROWSER,270,90,560,310,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_WHITE,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,530,410,80,20,"Clear");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdeactionCB,2);
  obj = fl_add_button(FL_NORMAL_BUTTON,620,410,80,20,"Reload");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdeactionCB,3);
  obj = fl_add_button(FL_NORMAL_BUTTON,270,410,120,20,"Add to Active List");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdeactionCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,400,410,120,20,"Remove From Active");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdeactionCB,1);
  obj = fl_add_button(FL_NORMAL_BUTTON,730,410,80,20,"Save");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_browser(FL_NORMAL_BROWSER,10,320,200,130,"Constraints");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_button(FL_NORMAL_BUTTON,220,330,20,20,"?");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_button(FL_NORMAL_BUTTON,220,370,20,20,"+");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_button(FL_NORMAL_BUTTON,220,410,20,20,"-");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_button(FL_NORMAL_BUTTON,240,15,80,30,"Info");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,rdetextCB,0);
  fl_end_form();

  fdui->cbprdeinput->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_cbprdehelp *create_form_cbprdehelp(void)
{
  FL_OBJECT *obj;
  FD_cbprdehelp *fdui = (FD_cbprdehelp *) fl_calloc(1, sizeof(*fdui));

  fdui->cbprdehelp = fl_bgn_form(FL_NO_BOX, 390, 450);
  obj = fl_add_box(FL_UP_BOX,0,0,390,450,"");
  obj = fl_add_input(FL_NORMAL_INPUT,120,80,260,20,"Response Name:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_input(FL_NORMAL_INPUT,120,120,260,20,"Response Type:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_input(FL_NORMAL_INPUT,120,160,260,20,"Response Arena:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_input(FL_NORMAL_INPUT,120,200,260,20,"Response Weapon:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_input(FL_NORMAL_INPUT,120,240,260,20,"Target Class:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_input(FL_NORMAL_INPUT,120,280,260,20,"Target Locale:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_input(FL_NORMAL_INPUT,120,320,260,20,"Target Weight:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_button(FL_NORMAL_BUTTON,160,400,60,30,"OK");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fl_end_form();

  fdui->cbprdehelp->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_cbprdetext *create_form_cbprdetext(void)
{
  FL_OBJECT *obj;
  FD_cbprdetext *fdui = (FD_cbprdetext *) fl_calloc(1, sizeof(*fdui));

  fdui->cbprdetext = fl_bgn_form(FL_NO_BOX, 411, 381);
  obj = fl_add_box(FL_UP_BOX,0,0,411,381,"");
  fdui->cbprdedisclaim = obj = fl_add_browser(FL_NORMAL_BROWSER,10,30,390,300,"");
    fl_set_object_callback(obj,CBPnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,160,340,80,30,"OK");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,COAexitCB,8);
  fl_end_form();

  fdui->cbprdetext->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

