/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "DSforms.h"

FD_input *create_form_input(void)
{
  FL_OBJECT *obj;
  FD_input *fdui = (FD_input *) fl_calloc(1, sizeof(*fdui));

  fdui->input = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  fdui->exit_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,10,70,30,"EXIT");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,input_exitCB,0);
  fdui->save_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,180,70,30,"SAVE");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,input_saveCB,0);
  fdui->load_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,140,70,30,"LOAD");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,input_loadCB,0);
  fdui->netw_but = obj = fl_add_button(FL_NORMAL_BUTTON,10,420,110,30,"NETWORK");
    fl_set_object_callback(obj,input_netwCB,0);
  fdui->assm_but = obj = fl_add_button(FL_NORMAL_BUTTON,140,420,110,30,"ASSESSMENT");
    fl_set_object_callback(obj,input_assessCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,10,390,230,20,"DISPLAY RESULTS");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->mod_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,310,70,30,"MODIFY");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,input_modCB,0);
  fdui->add_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,270,70,30,"ADD");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,input_addCB,0);
  fdui->del_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,350,70,30,"DELETE");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,input_delCB,0);
  fdui->asstype_text = obj = fl_add_text(FL_NORMAL_TEXT,90,60,210,20,"ASSESSMENT TYPE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->startime_text = obj = fl_add_text(FL_NORMAL_TEXT,480,10,80,20,"Start Time =");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->sdate_text = obj = fl_add_text(FL_NORMAL_TEXT,560,10,130,20,"140900 : 30Aug96");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->bot_sep = obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,380,740,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  fdui->top_sep = obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,120,830,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  fdui->source_title = obj = fl_add_text(FL_NORMAL_TEXT,30,130,180,20,"SOURCE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->conf_title = obj = fl_add_text(FL_NORMAL_TEXT,310,130,150,20,"CONFIDENCE %");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->tplus_title = obj = fl_add_text(FL_NORMAL_TEXT,610,130,60,20,"T +/-");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->day_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,600,90,20,20,"DAYS");
    fl_set_object_callback(obj,assess_tunitCB,3);
  fdui->sec_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,500,60,20,20,"SECONDS");
    fl_set_object_callback(obj,assess_tunitCB,0);
  fdui->min_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,600,60,20,20,"MINUTES");
    fl_set_object_callback(obj,assess_tunitCB,1);
  fdui->hour_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,500,90,20,20,"HOURS");
    fl_set_object_callback(obj,assess_tunitCB,2);
  fdui->timestep_text = obj = fl_add_text(FL_NORMAL_TEXT,510,40,130,20,"TIME STEPS");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->asstype_menu = obj = fl_add_choice(FL_DROPLIST_CHOICE,90,80,210,30,"");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_callback(obj,input_menuCB,0);
  fdui->input_browser = obj = fl_add_browser(FL_HOLD_BROWSER,10,160,700,210,"");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_FIXEDBOLD_STYLE);
    fl_set_object_callback(obj,input_browserCB,0);
  fdui->input_exec_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,420,70,30,"EXECUTE");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,executeCB,0);
  fdui->input_caseid = obj = fl_add_input(FL_NORMAL_INPUT,90,20,220,30,"Case ID:");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,input_caseidCB,0);
  fdui->assess_reset_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,220,70,30,"RESET");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,resetCB,0);
  fl_end_form();

  fdui->input->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_assess *create_form_assess(void)
{
  FL_OBJECT *obj;
  FD_assess *fdui = (FD_assess *) fl_calloc(1, sizeof(*fdui));

  fdui->assess = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  fdui->conf_plot = obj = fl_add_xyplot(FL_SQUARE_XYPLOT,430,10,400,220,"");
  fdui->caseid_title = obj = fl_add_text(FL_NORMAL_TEXT,10,10,90,20,"CASE ID:");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->case_id = obj = fl_add_text(FL_NORMAL_TEXT,100,10,100,20,"9001");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->stime_text = obj = fl_add_text(FL_NORMAL_TEXT,200,10,90,20,"Start Time =");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->ctime_text = obj = fl_add_text(FL_NORMAL_TEXT,200,30,90,20,"Current Time =");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->sdate_text = obj = fl_add_text(FL_NORMAL_TEXT,290,10,110,20,"140900:30Aug96");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->cdate_text = obj = fl_add_text(FL_NORMAL_TEXT,290,30,110,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->netw_but = obj = fl_add_button(FL_NORMAL_BUTTON,40,410,80,30,"NETWORK");
    fl_set_object_callback(obj,assess_netwCB,0);
  fdui->exit_but = obj = fl_add_button(FL_NORMAL_BUTTON,160,410,80,30,"DISMISS");
    fl_set_object_callback(obj,assess_exitCB,0);
  fdui->sec_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,10,330,20,20,"SECONDS");
  fdui->min_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,100,330,20,20,"MINUTES");
  fdui->hour_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,10,360,20,20,"HOURS");
  fdui->timestep_text = obj = fl_add_text(FL_NORMAL_TEXT,30,310,130,20,"TIME UNITS");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->issue_but = obj = fl_add_button(FL_NORMAL_BUTTON,310,260,110,40,"ISSUE SELECTED\nASSESSMENT");
    fl_set_object_callback(obj,assess_issueCB,0);
  fdui->asstype_text = obj = fl_add_text(FL_NORMAL_TEXT,10,30,90,20,"Assessment:");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->assess_type = obj = fl_add_text(FL_NORMAL_TEXT,100,30,100,20,"Launch");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->best_title = obj = fl_add_text(FL_NORMAL_TEXT,470,390,120,20,"BEST ASSESSMENT:");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->best_value = obj = fl_add_text(FL_NORMAL_TEXT,450,410,150,30,"Hostile Missile Launch");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->param_title = obj = fl_add_text(FL_NORMAL_TEXT,20,60,340,20,"PARAMETER                    LAT            LON          ALT          T+/-");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_accid_but = obj = fl_add_button(FL_NORMAL_BUTTON,780,290,40,20,"<2>");
    fl_set_object_callback(obj,assess_selectCB,1);
  fdui->ass_anom_but = obj = fl_add_button(FL_NORMAL_BUTTON,780,320,40,20,"<3>");
    fl_set_object_callback(obj,assess_selectCB,2);
  fdui->ass_other_but = obj = fl_add_button(FL_NORMAL_BUTTON,780,350,40,20,"<4>");
    fl_set_object_callback(obj,assess_selectCB,3);
  fdui->assess_ass1_plause = obj = fl_add_text(FL_NORMAL_TEXT,700,260,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_ass2_plause = obj = fl_add_text(FL_NORMAL_TEXT,700,290,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_ass1_belief = obj = fl_add_text(FL_NORMAL_TEXT,610,260,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_ass2_belief = obj = fl_add_text(FL_NORMAL_TEXT,610,290,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_ass3_plause = obj = fl_add_text(FL_NORMAL_TEXT,700,320,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_ass4_plause = obj = fl_add_text(FL_NORMAL_TEXT,700,350,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_CHARTREUSE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_ass1_text = obj = fl_add_text(FL_NORMAL_TEXT,450,260,150,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_ass2_text = obj = fl_add_text(FL_NORMAL_TEXT,450,290,150,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_ass3_text = obj = fl_add_text(FL_NORMAL_TEXT,450,320,150,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_ass4_text = obj = fl_add_text(FL_NORMAL_TEXT,450,350,150,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_CHARTREUSE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_ass3_belief = obj = fl_add_text(FL_NORMAL_TEXT,610,320,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_ass4_belief = obj = fl_add_text(FL_NORMAL_TEXT,610,350,70,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lcolor(obj,FL_CHARTREUSE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_belief_text = obj = fl_add_text(FL_NORMAL_TEXT,480,240,340,20,"        ASSESSMENT                  BELIEF          PLAUSIBILITY   SELECT");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_host_but = obj = fl_add_button(FL_NORMAL_BUTTON,780,260,40,20,"<1>");
    fl_set_object_callback(obj,assess_selectCB,0);
  fdui->ass_graf_bot = obj = fl_add_positioner(FL_NORMAL_POSITIONER,290,230,530,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,290,230,10,220,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);

  fdui->time_group = fl_bgn_group();
  fdui->ass_day_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,100,360,20,20,"DAYS");
    fl_set_object_callback(obj,assess_tunitCB,3);
  fdui->ass_sec_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,10,330,20,20,"SECONDS");
    fl_set_object_callback(obj,assess_tunitCB,0);
  fdui->ass_min_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,100,330,20,20,"MINUTES");
    fl_set_object_callback(obj,assess_tunitCB,1);
  fdui->ass_hour_check = obj = fl_add_checkbutton(FL_RADIO_BUTTON,10,360,20,20,"HOURS");
    fl_set_object_callback(obj,assess_tunitCB,2);
  fl_end_group();

  fdui->propagate_button = obj = fl_add_button(FL_NORMAL_BUTTON,20,240,90,20,"PROPAGATE");
    fl_set_object_callback(obj,populateCB,0);
  obj = fl_add_clock(FL_DIGITAL_CLOCK,210,240,70,30,"");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BOTTOM_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_NORMAL_STYLE+FL_ENGRAVED_STYLE);
  fdui->belief_pie = obj = fl_add_chart(FL_BAR_CHART,610,390,70,50,"");
  fdui->plause_pie = obj = fl_add_chart(FL_BAR_CHART,700,390,70,50,"");

  fdui->issue_group = fl_bgn_group();
  fdui->assess_round[0] = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,310,320,100,20,"SBIRS");
    fl_set_object_callback(obj,assess_selectCB,0);
  fdui->assess_round[1] = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,310,340,90,20,"STRAT");
    fl_set_object_callback(obj,assess_selectCB,1);
  fdui->assess_round[2] = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,310,360,80,20,"POLITICAL");
    fl_set_object_callback(obj,assess_selectCB,2);
  fdui->assess_round[3] = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,310,380,80,20,"INTEL");
    fl_set_object_callback(obj,assess_selectCB,3);
  fdui->assess_round[4] = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,310,400,100,20,"FIRE CONTROL");
    fl_set_object_callback(obj,assess_selectCB,4);
  fdui->assess_round[5] = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,310,420,100,20,"RADAR");
    fl_set_object_callback(obj,assess_selectCB,5);
  fl_end_group();

  fdui->ass_browser = obj = fl_add_browser(FL_NORMAL_BROWSER,10,80,390,150,"");
    fl_set_object_callback(obj,evidenceCB,0);
  fl_end_form();

  fdui->assess->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_network *create_form_network(void)
{
  FL_OBJECT *obj;
  FD_network *fdui = (FD_network *) fl_calloc(1, sizeof(*fdui));

  fdui->network = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  fdui->hypot_text = obj = fl_add_text(FL_NORMAL_TEXT,20,230,130,20,"HYPOTHESIS");
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->ass_text = obj = fl_add_text(FL_NORMAL_TEXT,20,340,130,20,"ASSESSMENT");
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,200,10,110,20,"CASE ID:");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->case_id = obj = fl_add_text(FL_NORMAL_TEXT,260,10,110,20,"9001");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->assess_type = obj = fl_add_text(FL_NORMAL_TEXT,260,30,110,20,"Launch");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->ass_title = obj = fl_add_text(FL_NORMAL_TEXT,150,30,110,20,"ASSESSMENT TYPE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->exit_but = obj = fl_add_button(FL_NORMAL_BUTTON,770,10,70,30,"DISMISS");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_exitCB,0);
  fdui->ass_but = obj = fl_add_button(FL_NORMAL_BUTTON,10,420,120,30,"ASSESSMENT");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_assessCB,0);
  fdui->chang_but = obj = fl_add_button(FL_NORMAL_BUTTON,380,420,150,30,"CHANGE EVIDENCE");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,evidenceCB,0);
  fdui->hyp_title[0] = obj = fl_add_text(FL_NORMAL_TEXT,310,260,80,20,"NFL");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->hyp_title[1] = obj = fl_add_text(FL_NORMAL_TEXT,420,260,80,20,"Anticipated");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->hyp_title[2] = obj = fl_add_text(FL_NORMAL_TEXT,530,260,80,20,"Friendly");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->hyp_title[3] = obj = fl_add_text(FL_NORMAL_TEXT,640,260,80,20,"Space");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->src_title[5] = obj = fl_add_text(FL_NORMAL_TEXT,690,150,80,20,"FIRE CONTROL");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->evid_text = obj = fl_add_text(FL_NORMAL_TEXT,20,110,130,20,"SOURCE");
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->src_title[0] = obj = fl_add_text(FL_NORMAL_TEXT,240,150,80,20,"SBIRS");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->src_title[1] = obj = fl_add_text(FL_NORMAL_TEXT,330,150,80,20,"STRAT");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->src_title[2] = obj = fl_add_text(FL_NORMAL_TEXT,420,150,80,20,"POLITICAL");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->src_title[3] = obj = fl_add_text(FL_NORMAL_TEXT,510,150,80,20,"INTEL");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->src_title[4] = obj = fl_add_text(FL_NORMAL_TEXT,600,150,80,20,"RADAR");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->stime_text = obj = fl_add_text(FL_NORMAL_TEXT,380,10,110,20,"Start Time =");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->ctime_text = obj = fl_add_text(FL_NORMAL_TEXT,380,30,110,20,"Current Time =");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->sdate_text = obj = fl_add_text(FL_NORMAL_TEXT,490,10,100,20,"140900:30Aug96");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->cdate_text = obj = fl_add_text(FL_NORMAL_TEXT,490,30,100,20,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->net_top_sep = obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,70,830,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  fdui->net_bot_sep = obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,410,830,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  fdui->propagate_button = obj = fl_add_button(FL_NORMAL_BUTTON,550,420,110,30,"PROPAGATE");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,populateCB,0);
  fdui->netw_reset_but = obj = fl_add_button(FL_NORMAL_BUTTON,680,420,90,30,"RESET");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,resetCB,0);
  fdui->netw_ass1_text = obj = fl_add_text(FL_NORMAL_TEXT,360,370,80,20,"Hostile");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->netw_ass2_text = obj = fl_add_text(FL_NORMAL_TEXT,470,370,80,20,"Deliberate");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  fdui->netw_src_belief[4] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,510,90,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,34);
  fdui->netw_src_plause[4] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,510,110,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,34);
  fdui->netw_src_unknown[4] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,510,130,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,34);
  fdui->netw_src_belief[5] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,600,90,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,35);
  fdui->netw_src_plause[5] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,600,110,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,35);
  fdui->netw_src_unknown[5] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,600,130,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,35);
  fdui->netw_src_belief[6] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,690,90,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,36);
  fdui->netw_src_plause[6] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,690,110,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,36);
  fdui->netw_src_unknown[6] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,690,130,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,36);
  fdui->netw_ass3_text = obj = fl_add_text(FL_NORMAL_TEXT,580,370,80,20,"Space");
    fl_set_object_boxtype(obj,FL_UP_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,90,80,20,"Belief");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,110,80,20,"Plausibility");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,130,80,20,"Don't Know");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,140,80,10,330,"");
    fl_set_object_boxtype(obj,FL_FLAT_BOX);
  obj = fl_add_text(FL_NORMAL_TEXT,150,200,80,20,"Belief");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,220,80,20,"Plausibility");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,240,80,20,"Don't Know");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,310,80,20,"Belief");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,330,80,20,"Plausibility");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,150,350,80,20,"Don't Know");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->netw_src_belief[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,240,90,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,31);
  fdui->netw_src_plause[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,240,110,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,31);
  fdui->netw_src_unknown[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,240,130,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,31);
  fdui->netw_src_belief[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,330,90,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,32);
  fdui->netw_src_plause[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,330,110,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,32);
  fdui->netw_src_unknown[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,330,130,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,32);
  fdui->netw_src_belief[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,420,90,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,33);
  fdui->netw_src_plause[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,420,110,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,33);
  fdui->netw_src_unknown[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,420,130,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,33);
  fdui->netw_hyp_unknown[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,310,240,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,21);
  fdui->netw_hyp_plause[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,310,220,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,21);
  fdui->netw_hyp_belief[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,310,200,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,21);
  fdui->netw_hyp_unknown[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,420,240,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,22);
  fdui->netw_hyp_plause[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,420,220,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,22);
  fdui->netw_hyp_belief[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,420,200,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,22);
  fdui->netw_hyp_unknown[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,530,240,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,23);
  fdui->netw_hyp_plause[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,530,220,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,23);
  fdui->netw_hyp_belief[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,530,200,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,23);
  fdui->netw_hyp_unknown[4] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,640,240,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,24);
  fdui->netw_hyp_plause[4] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,640,220,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,24);
  fdui->netw_ass_unknown[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,360,350,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,11);
  fdui->netw_ass_plause[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,360,330,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,11);
  fdui->netw_ass_belief[1] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,360,310,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,11);
  fdui->netw_ass_unknown[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,470,350,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,12);
  fdui->netw_ass_plause[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,470,330,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,12);
  fdui->netw_ass_belief[2] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,470,310,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,12);
  fdui->netw_ass_unknown[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,580,350,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_unknownCB,13);
  fdui->netw_ass_plause[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,580,330,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_plauseCB,13);
  fdui->netw_ass_belief[3] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,580,310,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,13);
  fdui->netw_hyp_belief[4] = obj = fl_add_valslider(FL_HOR_FILL_SLIDER,640,200,80,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,netw_beliefCB,24);
  fl_end_form();

  fdui->network->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_assessadd *create_form_assessadd(void)
{
  FL_OBJECT *obj;
  FD_assessadd *fdui = (FD_assessadd *) fl_calloc(1, sizeof(*fdui));

  fdui->assessadd = fl_bgn_form(FL_NO_BOX, 610, 230);
  obj = fl_add_box(FL_UP_BOX,0,0,610,230,"");
  obj = fl_add_text(FL_NORMAL_TEXT,120,50,60,20,"SOURCE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,300,20,140,20,"CONFIDENCE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,300,50,140,20,"T +/-");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->add_confid = obj = fl_add_input(FL_FLOAT_INPUT,450,20,110,20,"");
    fl_set_object_callback(obj,add_getvalCB,0);
  fdui->add_time = obj = fl_add_input(FL_FLOAT_INPUT,450,50,110,20,"");
    fl_set_object_callback(obj,add_getvalCB,1);
  fdui->add_source = obj = fl_add_text(FL_NORMAL_TEXT,180,50,110,20,"Text");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->add_src_choice = obj = fl_add_choice(FL_NORMAL_CHOICE2,130,20,160,20,"");
    fl_set_object_callback(obj,add_sourceCB,0);
  fdui->SC_icon = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,20,10,80,80,"");
  fdui->add_accept = obj = fl_add_button(FL_NORMAL_BUTTON,180,200,110,20,"Accept");
    fl_set_object_callback(obj,add_acceptCB,0);
  fdui->assadd_cancel = obj = fl_add_button(FL_NORMAL_BUTTON,310,200,90,20,"Cancel");
    fl_set_object_callback(obj,assadd_cancelCB,0);
  fdui->add_lat = obj = fl_add_input(FL_FLOAT_INPUT,450,80,110,20,"");
    fl_set_object_callback(obj,add_getvalCB,2);
  fdui->add_long = obj = fl_add_input(FL_FLOAT_INPUT,450,110,110,20,"");
    fl_set_object_callback(obj,add_getvalCB,3);
  fdui->add_alt = obj = fl_add_input(FL_FLOAT_INPUT,450,140,110,20,"");
    fl_set_object_callback(obj,add_getvalCB,4);
  obj = fl_add_text(FL_NORMAL_TEXT,340,80,100,20,"LATITUDE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,360,110,80,20,"LONGITUDE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,360,140,80,20,"ALTITUDE");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,120,110,80,20,"DESCRIPTION");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->add_desc = obj = fl_add_input(FL_NORMAL_INPUT,120,130,160,20,"");
    fl_set_object_callback(obj,add_getvalCB,5);
  fl_end_form();

  fdui->assessadd->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

