/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "ODIforms.h"

FD_ODI *create_form_ODI(void)
{
  FL_OBJECT *obj;
  FD_ODI *fdui = (FD_ODI *) fl_calloc(1, sizeof(*fdui));

  fdui->ODI = fl_bgn_form(FL_NO_BOX, 940, 660);
  obj = fl_add_box(FL_UP_BOX,0,0,940,660,"");
  fdui->background = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,115,45,710,560,"");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lsize(obj,FL_LARGE_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,ODInoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/Splash2.xpm");
  fdui->quit_button = obj = fl_add_button(FL_NORMAL_BUTTON,395,610,150,40,"Quit");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_DARKTOMATO,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lsize(obj,FL_LARGE_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,ODIexitCB,0);
  fdui->rhs_button[1] = obj = fl_add_button(FL_NORMAL_BUTTON,830,45,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,1);
  fdui->rhs_button[2] = obj = fl_add_button(FL_NORMAL_BUTTON,830,85,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,2);
  fdui->rhs_button[3] = obj = fl_add_button(FL_NORMAL_BUTTON,830,125,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,3);
  fdui->rhs_button[4] = obj = fl_add_button(FL_NORMAL_BUTTON,830,165,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,4);
  fdui->rhs_button[5] = obj = fl_add_button(FL_NORMAL_BUTTON,830,205,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,5);
  fdui->rhs_button[6] = obj = fl_add_button(FL_NORMAL_BUTTON,830,245,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,6);
  fdui->rhs_button[7] = obj = fl_add_button(FL_NORMAL_BUTTON,830,285,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,7);
  fdui->rhs_button[8] = obj = fl_add_button(FL_NORMAL_BUTTON,830,325,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,8);
  fdui->rhs_button[9] = obj = fl_add_button(FL_NORMAL_BUTTON,830,365,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,9);
  fdui->rhs_button[10] = obj = fl_add_button(FL_NORMAL_BUTTON,830,405,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,10);
  fdui->rhs_button[11] = obj = fl_add_button(FL_NORMAL_BUTTON,830,445,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,11);
  fdui->rhs_button[12] = obj = fl_add_button(FL_NORMAL_BUTTON,830,485,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,12);
  fdui->rhs_button[13] = obj = fl_add_button(FL_NORMAL_BUTTON,830,525,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,13);
  fdui->rhs_button[14] = obj = fl_add_button(FL_NORMAL_BUTTON,830,565,100,40,"");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,RHSideCB,14);

  fdui->RHSRadio = fl_bgn_group();
  obj = fl_add_button(FL_RADIO_BUTTON,10,127,100,40,"Blue Force");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,3);
  obj = fl_add_button(FL_RADIO_BUTTON,10,245,100,40,"PBA");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_DARKCYAN);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,6);
  obj = fl_add_button(FL_RADIO_BUTTON,10,325,100,40,"BDA");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_DARKCYAN);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,8);
  obj = fl_add_button(FL_RADIO_BUTTON,10,45,100,40,"ATO");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_CYAN);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,1);
  obj = fl_add_button(FL_RADIO_BUTTON,10,85,100,40,"Geo");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,2);
  obj = fl_add_button(FL_RADIO_BUTTON,10,165,100,40,"Red Force");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,4);
  obj = fl_add_button(FL_RADIO_BUTTON,10,205,100,40,"ISR");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,5);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,285,100,40,"WTP");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,7);
  obj = fl_add_button(FL_RADIO_BUTTON,10,365,100,40,"BM");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,9);
  obj = fl_add_button(FL_RADIO_BUTTON,10,405,100,40,"COMM");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,10);
  obj = fl_add_button(FL_RADIO_BUTTON,10,445,100,40,"Chat Room");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,11);
  obj = fl_add_button(FL_RADIO_BUTTON,10,485,100,40,"Elec. Mea.");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,12);
  obj = fl_add_button(FL_RADIO_BUTTON,10,525,100,40,"Schedule");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,13);
  obj = fl_add_button(FL_RADIO_BUTTON,10,565,100,40,"Predict");
    fl_set_object_boxtype(obj,FL_EMBOSSED_BOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_DODGERBLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE+FL_ENGRAVED_STYLE);
    fl_set_object_callback(obj,battleCB,14);
  fl_end_group();

  fl_end_form();

  fdui->ODI->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

