/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "CLUforms.h"

static FL_PUP_ENTRY fdchoice_out_choice_0[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "Best Substructure",	0,	"",	 FL_PUP_NONE},
    { "Best 'n' Substructures",	0,	"",	 FL_PUP_NONE},
    { "Best 'n' & Intermediates",	0,	"",	 FL_PUP_NONE},
    { "Best 'n' with Tables",	0,	"",	 FL_PUP_NONE},
    { "Best 'n' with Neg.Subs",	0,	"",	 FL_PUP_NONE},
    {0}
};

FD_cluster *create_form_cluster(void)
{
  FL_OBJECT *obj;
  FD_cluster *fdui = (FD_cluster *) fl_calloc(1, sizeof(*fdui));

  fdui->cluster = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,430,60,180,280,"General Parameters");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,30,60,180,135,"General Switches");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,230,60,180,385,"General Parameters");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,30,270,180,175,"Supervised Learning");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,430,360,180,85,"Clustering");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,755,15,80,30,"Exit");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUexitCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,715,180,80,30,"Cluster");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluapplyCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,715,260,80,30,"View Graph");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluviewCB,0);
  fdui->clu_waitmsg = obj = fl_add_text(FL_NORMAL_TEXT,675,210,165,50,"This may take awhile.\nPlease be patient.\nI'll let you know when it's done.");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->clu_donemsg = obj = fl_add_text(FL_NORMAL_TEXT,710,225,85,25,"Done!");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,715,415,80,30,"Reset");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluresetCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,715,105,80,30,"Classify");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluclassCB,1);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,660,10,5,440,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,675,65,165,40,"The 'Classify' button converts\na flat table file to a graph file\nneeded by 'Subdue'");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,675,140,170,40,"The 'Cluster' button performs a\nSubdue cluster analysis on\nthe specified graph file.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->message = obj = fl_add_input(FL_NORMAL_INPUT,80,15,550,25,"Message");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->param[21] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,370,160,20,"Cluster");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,21);
    fl_set_button(obj, 1);
  fdui->param[22] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,395,160,20,"True Labels");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,22);
    fl_set_button(obj, 1);
  fdui->param[23] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,420,160,20,"Exhaustive Analysis");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,23);
  fdui->param[24] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,280,160,20,"Supervised");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,24);
  fdui->param[25] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,300,160,20,"Scratch");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,25);
  fdui->param[26] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,320,160,20,"# of Positives");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,26);
  fdui->param[27] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,360,160,20,"Minimum %");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,27);
  fdui->param[28] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,400,160,20,"Neg. Weight");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,28);
  fdui->param[5] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,70,160,20,"Prune Children");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,5);
  fdui->param[8] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,90,160,20,"Allow Overlap");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,8);
  fdui->param[9] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,110,160,20,"Allow Undirected Edges");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,9);
  fdui->param[19] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,130,160,20,"Use Old Evaluation");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,19);
  fdui->param[20] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,150,160,20,"Save Substructures");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,20);
  fdui->param[29] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,170,160,20,"Interactive Display");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,29);
  fdui->param[1] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,75,160,20,"Substructure Limit");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,1);
  fdui->param[2] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,115,160,20,"# of Iterations");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,2);
  fdui->param[3] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,155,160,20,"Threshold");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,3);
  fdui->param[4] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,195,160,20,"Substructure List Length");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,4);
  fdui->cluvalue[1] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,95,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,1);
  fdui->cluvalue[2] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,135,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,2);
  fdui->cluvalue[3] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,175,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,3);
  fdui->cluvalue[4] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,215,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,4);
  fdui->param[6] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,235,160,20,"Detect Minima");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,6);
  fdui->param[7] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,275,160,20,"Beam Search Width");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,7);
  fdui->param[10] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,315,160,20,"Connectivity");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,10);
  fdui->cluvalue[6] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,255,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,6);
  fdui->cluvalue[7] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,295,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,7);
  fdui->cluvalue[10] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,335,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,10);
  fdui->param[11] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,355,160,20,"Compactness");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,11);
  fdui->param[12] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,240,395,160,20,"Coverage");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,12);
  fdui->cluvalue[11] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,375,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,11);
  fdui->cluvalue[12] = obj = fl_add_counter(FL_NORMAL_COUNTER,265,415,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,12);
  fdui->out_choice = obj = fl_add_choice(FL_NORMAL_CHOICE2,40,230,160,20,"");
    fl_set_object_callback(obj,cluparamCB,16);
    fl_set_choice_entries(obj, fdchoice_out_choice_0);
    fl_set_choice(obj,2);
  fdui->cluvalue[26] = obj = fl_add_counter(FL_NORMAL_COUNTER,65,340,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,26);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 1000);
    fl_set_counter_step(obj, 1, 10);
  fdui->cluvalue[27] = obj = fl_add_counter(FL_NORMAL_COUNTER,65,380,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,27);
  fdui->cluvalue[28] = obj = fl_add_counter(FL_NORMAL_COUNTER,65,420,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,28);
  fdui->param[13] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,75,160,20,"Use Alternative Labels");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,13);
  fdui->param[15] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,155,160,20,"Bound Vertice Count");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,15);
  fdui->clu_lowsize = obj = fl_add_counter(FL_NORMAL_COUNTER,465,175,135,20,"");
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->clu_highsize = obj = fl_add_counter(FL_NORMAL_COUNTER,465,195,135,20,"");
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->param[18] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,225,160,20,"Compression Information");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,18);
  fdui->clu_plotfn = obj = fl_add_input(FL_NORMAL_INPUT,440,255,160,20,"        Plot File Name");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->param[17] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,295,160,20,"PVM Processor Count");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,17);
  fdui->cluvalue[17] = obj = fl_add_counter(FL_NORMAL_COUNTER,465,315,135,20,"");
    fl_set_object_callback(obj,cluvalueCB,17);
  fdui->param[14] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,440,100,160,20,"Predefined SubStructures");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,14);
  fdui->clu_subsfn = obj = fl_add_input(FL_NORMAL_INPUT,440,130,160,20,"        File Name");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->param[16] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,40,210,160,20,"Screen Output Level");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluparamCB,16);
  obj = fl_add_button(FL_NORMAL_BUTTON,715,340,80,30,"Make Node");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,clunodeCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,670,300,165,40,"The 'Make Node' button\nprovides for adding a new\nnode to a fusion network.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fl_end_form();

  fdui->cluster->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_itelfields *create_form_itelfields(void)
{
  FL_OBJECT *obj;
  FD_itelfields *fdui = (FD_itelfields *) fl_calloc(1, sizeof(*fdui));

  fdui->itelfields = fl_bgn_form(FL_NO_BOX, 846, 486);
  obj = fl_add_box(FL_UP_BOX,0,0,846,486,"");
  fdui->itel_fldselect[0] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,70,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[1] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,100,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[2] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,130,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[3] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,160,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[4] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,190,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[5] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,220,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[6] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,250,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[7] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,280,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[8] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,310,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[9] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,340,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[10] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,370,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[11] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,400,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[12] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,70,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[13] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,100,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[14] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,130,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[15] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,160,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[16] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,190,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[17] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,220,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[18] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,250,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[19] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,280,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[20] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,310,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[21] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,340,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[22] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,370,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[23] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,400,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[24] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,70,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[25] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,100,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[26] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,130,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[27] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,160,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[28] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,190,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[29] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,220,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[30] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,250,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[31] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,280,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[32] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,310,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[33] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,340,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[34] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,370,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[35] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,400,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[36] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,70,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[37] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,100,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[38] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,130,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[39] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,160,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[40] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,190,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[41] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,220,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[42] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,250,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[43] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,280,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[44] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,310,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[45] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,340,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[48] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,30,435,100,20,"Prepared");
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[49] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,160,430,100,20,"Prep-Date");
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[50] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,295,430,100,20,"");
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[51] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,430,120,20,"");
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,500,15,80,30,"Apply");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluclassCB,10);
  obj = fl_add_text(FL_NORMAL_TEXT,30,10,170,40,"Select fields to classify\nfrom list below or:");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,205,30,120,20,"Deselect All");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluclassCB,13);
  obj = fl_add_button(FL_NORMAL_BUTTON,205,10,120,20,"Select All");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluclassCB,12);
  obj = fl_add_text(FL_NORMAL_TEXT,15,460,535,20,"(Selections are set by default if that field has a value other than \"Unknown\" in at least one record )");
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,750,15,80,30,"Done");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cluclassCB,11);
  fdui->itel_fldselect[46] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,370,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_fldselect[47] = obj = fl_add_checkbutton(FL_PUSH_BUTTON,435,400,120,20,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,595,10,5,465,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  fdui->clu_classes = obj = fl_add_browser(FL_NORMAL_BROWSER,610,155,220,310,"Classification Relationships");
    fl_set_object_color(obj,FL_WHITE,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,610,135,220,20,"Class #      Hypothesis");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_FIXEDBOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->clu_classfn = obj = fl_add_input(FL_NORMAL_INPUT,610,110,220,20,"Classifying File:");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);

  fdui->clugrp_mode = fl_bgn_group();
  fdui->clu_subdue = obj = fl_add_checkbutton(FL_RADIO_BUTTON,350,10,135,20,"Cluster Analysis");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
    fl_set_button(obj, 1);
  fdui->clu_classify = obj = fl_add_checkbutton(FL_RADIO_BUTTON,350,30,135,20,"Classify Analysis");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fl_end_group();

  fdui->clu_closest = obj = fl_add_input(FL_NORMAL_INPUT,610,70,220,20,"Closest Match:");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fl_end_form();

  fdui->itelfields->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_defnode *create_form_defnode(void)
{
  FL_OBJECT *obj;
  FD_defnode *fdui = (FD_defnode *) fl_calloc(1, sizeof(*fdui));

  fdui->defnode = fl_bgn_form(FL_NO_BOX, 321, 306);
  obj = fl_add_box(FL_UP_BOX,0,0,321,306,"");
  fdui->clu_mission = obj = fl_add_choice(FL_NORMAL_CHOICE2,55,60,190,25,"");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  fdui->clu_nodename = obj = fl_add_input(FL_NORMAL_INPUT,60,150,190,25,"Choose a hypothesis name for\nthis concept.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,CLUnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,115,250,90,25,"Done");
    fl_set_object_callback(obj,clunodeCB,9);
  obj = fl_add_text(FL_NORMAL_TEXT,50,20,205,35,"Choose the Mission Domain\nto which this node is to be added.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fl_end_form();

  fdui->defnode->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

