/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "FOGforms.h"

FD_FogInput *create_form_FogInput(void)
{
  FL_OBJECT *obj;
  FD_FogInput *fdui = (FD_FogInput *) fl_calloc(1, sizeof(*fdui));

  fdui->FogInput = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  obj = fl_add_text(FL_NORMAL_TEXT,80,70,130,30,"Causes");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,440,70,180,30,"Weights");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,650,70,180,30,"Outcomes");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,15,100,60,180,"Data");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_color(obj,FL_DARKGOLD,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,15,290,60,160,"Human");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_color(obj,FL_DARKTOMATO,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,FOGnoneCB,0);
  fdui->evid_button[0] = obj = fl_add_button(FL_NORMAL_BUTTON,230,110,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,230,70,180,30,"Evidence");
    fl_set_object_boxtype(obj,FL_SHADOW_BOX);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,20,280,820,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,50,830,10,"");
    fl_set_object_boxtype(obj,FL_FLAT_BOX);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,760,10,80,30,"Exit");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,FOGexitCB,0);
  fdui->weight_button[10] = obj = fl_add_button(FL_NORMAL_BUTTON,440,300,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,10);
  fdui->weight_button[11] = obj = fl_add_button(FL_NORMAL_BUTTON,440,320,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,11);
  fdui->weight_button[12] = obj = fl_add_button(FL_NORMAL_BUTTON,440,340,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,12);
  fdui->weight_button[13] = obj = fl_add_button(FL_NORMAL_BUTTON,440,360,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,13);
  fdui->weight_button[14] = obj = fl_add_button(FL_NORMAL_BUTTON,440,380,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,14);
  fdui->weight_button[15] = obj = fl_add_button(FL_NORMAL_BUTTON,440,400,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,15);
  fdui->weight_button[30] = obj = fl_add_button(FL_NORMAL_BUTTON,530,300,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,30);
  fdui->weight_button[32] = obj = fl_add_button(FL_NORMAL_BUTTON,530,340,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,32);
  fdui->weight_button[33] = obj = fl_add_button(FL_NORMAL_BUTTON,530,360,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,33);
  fdui->weight_button[34] = obj = fl_add_button(FL_NORMAL_BUTTON,530,380,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,34);
  fdui->weight_button[35] = obj = fl_add_button(FL_NORMAL_BUTTON,530,400,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,35);
  fdui->outcome_button[10] = obj = fl_add_button(FL_NORMAL_BUTTON,650,300,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,10);
  fdui->outcome_button[12] = obj = fl_add_button(FL_NORMAL_BUTTON,650,340,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,12);
  fdui->outcome_button[13] = obj = fl_add_button(FL_NORMAL_BUTTON,650,360,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,13);
  fdui->outcome_button[14] = obj = fl_add_button(FL_NORMAL_BUTTON,650,380,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,14);
  fdui->outcome_button[15] = obj = fl_add_button(FL_NORMAL_BUTTON,650,400,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,15);
  fdui->outcome_button[30] = obj = fl_add_button(FL_NORMAL_BUTTON,740,300,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,30);
  fdui->outcome_button[31] = obj = fl_add_button(FL_NORMAL_BUTTON,740,320,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,31);
  fdui->outcome_button[33] = obj = fl_add_button(FL_NORMAL_BUTTON,740,360,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,33);
  fdui->outcome_button[34] = obj = fl_add_button(FL_NORMAL_BUTTON,740,380,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,34);
  fdui->outcome_button[35] = obj = fl_add_button(FL_NORMAL_BUTTON,740,400,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,35);
  fdui->evid_button[1] = obj = fl_add_button(FL_NORMAL_BUTTON,230,130,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,1);
  fdui->evid_button[2] = obj = fl_add_button(FL_NORMAL_BUTTON,230,150,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,2);
  fdui->evid_button[3] = obj = fl_add_button(FL_NORMAL_BUTTON,230,170,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,3);
  fdui->evid_button[4] = obj = fl_add_button(FL_NORMAL_BUTTON,230,190,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,4);
  fdui->evid_button[5] = obj = fl_add_button(FL_NORMAL_BUTTON,230,210,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,5);
  fdui->evid_button[6] = obj = fl_add_button(FL_NORMAL_BUTTON,230,230,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,6);
  fdui->evid_button[7] = obj = fl_add_button(FL_NORMAL_BUTTON,230,250,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,7);
  fdui->evid_button[20] = obj = fl_add_button(FL_NORMAL_BUTTON,320,110,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,20);
  fdui->evid_button[21] = obj = fl_add_button(FL_NORMAL_BUTTON,320,130,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,21);
  fdui->evid_button[22] = obj = fl_add_button(FL_NORMAL_BUTTON,320,150,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,22);
  fdui->evid_button[23] = obj = fl_add_button(FL_NORMAL_BUTTON,320,170,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,23);
  fdui->evid_button[24] = obj = fl_add_button(FL_NORMAL_BUTTON,320,190,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,24);
  fdui->evid_button[25] = obj = fl_add_button(FL_NORMAL_BUTTON,320,210,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,25);
  fdui->evid_button[26] = obj = fl_add_button(FL_NORMAL_BUTTON,320,230,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,26);
  fdui->evid_button[27] = obj = fl_add_button(FL_NORMAL_BUTTON,320,250,90,20,"random");
    fl_set_object_color(obj,FL_PALEGREEN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_evidCB,27);
  fdui->weight_button[16] = obj = fl_add_button(FL_NORMAL_BUTTON,440,420,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,16);
  fdui->weight_button[36] = obj = fl_add_button(FL_NORMAL_BUTTON,530,420,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,36);
  fdui->outcome_button[16] = obj = fl_add_button(FL_NORMAL_BUTTON,650,420,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,16);
  fdui->outcome_button[36] = obj = fl_add_button(FL_NORMAL_BUTTON,740,420,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,36);
  obj = fl_add_button(FL_NORMAL_BUTTON,280,10,80,30,"Load");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_loadCB,0);
  fdui->cause_button[0] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,110,130,20,"Loss");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,0);
  fdui->cause_button[1] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,130,130,20,"Latency");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,1);
  fdui->cause_button[2] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,150,130,20,"Asynchrony");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,2);
  fdui->cause_button[3] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,170,130,20,"Degradation");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,3);
  fdui->cause_button[4] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,190,130,20,"Ambiguity");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,4);
  fdui->cause_button[5] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,210,130,20,"Conflict");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,5);
  fdui->cause_button[6] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,230,130,20,"Overload");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,6);
  fdui->cause_button[7] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,250,130,20,"Bad Luck");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,7);
  fdui->cause_button[11] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,320,130,20,"Disposition");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,11);
  fdui->cause_button[12] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,340,130,20,"Cognition");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,12);
  fdui->cause_button[13] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,360,130,20,"Confusion");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,13);
  fdui->cause_button[14] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,380,130,20,"Priorities");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,14);
  fdui->cause_button[15] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,400,130,20,"Miscommunicate");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,15);
  fdui->cause_button[16] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,420,130,20,"Assumptions");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,16);
  obj = fl_add_button(FL_NORMAL_BUTTON,370,10,80,30,"Save");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_saveCB,0);
  fdui->cause_button[10] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,300,130,20,"Surprises");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lcolor(obj,FL_RIGHT_BCOL);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,cause_buttonCB,10);
  fdui->weight_button[31] = obj = fl_add_button(FL_NORMAL_BUTTON,530,320,90,20,"random");
    fl_set_object_color(obj,FL_CYAN,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_weightCB,31);
  fdui->outcome_button[11] = obj = fl_add_button(FL_NORMAL_BUTTON,650,320,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,11);
  fdui->outcome_button[32] = obj = fl_add_button(FL_NORMAL_BUTTON,740,340,90,20,"random");
    fl_set_object_color(obj,FL_WHEAT,FL_COL1);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_outcomeCB,32);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,500,10,90,30,"Enable");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,fog_buttonCB,2);
  fdui->fog_name = obj = fl_add_input(FL_NORMAL_INPUT,80,10,180,30,"FOG File");
    fl_set_object_callback(obj,fog_loadCB,1);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,630,60,10,390,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,FOGnoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,420,60,10,390,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,FOGnoneCB,0);
  fl_end_form();

  fdui->FogInput->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_SetDialog *create_form_SetDialog(void)
{
  FL_OBJECT *obj;
  FD_SetDialog *fdui = (FD_SetDialog *) fl_calloc(1, sizeof(*fdui));

  fdui->SetDialog = fl_bgn_form(FL_NO_BOX, 310, 240);
  obj = fl_add_box(FL_UP_BOX,0,0,310,240,"");
  obj = fl_add_button(FL_NORMAL_BUTTON,70,210,80,20,"Accept");
    fl_set_object_callback(obj,fog_acceptCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,160,210,70,20,"Cancel");
    fl_set_object_callback(obj,fog_cancelCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,10,160,70,20,"Low");
    fl_set_object_callback(obj,fog_settingCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,90,160,70,20,"Medium");
    fl_set_object_callback(obj,fog_settingCB,1);
  obj = fl_add_button(FL_NORMAL_BUTTON,170,160,70,20,"High");
    fl_set_object_callback(obj,fog_settingCB,2);
  fdui->set_slider = obj = fl_add_valslider(FL_VERT_NICE_SLIDER,280,10,20,170,"");
    fl_set_object_callback(obj,fog_sliderCB,0);
  fdui->set_value = obj = fl_add_input(FL_FLOAT_INPUT,130,80,110,30,"Random");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,190,290,10,"");
    fl_set_object_boxtype(obj,FL_FLAT_BOX);
  fl_end_form();

  fdui->SetDialog->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_HelpDialog *create_form_HelpDialog(void)
{
  FL_OBJECT *obj;
  FD_HelpDialog *fdui = (FD_HelpDialog *) fl_calloc(1, sizeof(*fdui));

  fdui->HelpDialog = fl_bgn_form(FL_NO_BOX, 470, 210);
  obj = fl_add_box(FL_UP_BOX,0,0,470,210,"");
  obj = fl_add_text(FL_NORMAL_TEXT,10,20,80,20,"Operator");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->help_oper = obj = fl_add_text(FL_NORMAL_TEXT,90,20,120,20,"Text");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,250,20,80,20,"Fog Factor");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
  fdui->help_factor = obj = fl_add_text(FL_NORMAL_TEXT,330,20,100,20,"Text");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->help_browser = obj = fl_add_browser(FL_NORMAL_BROWSER,10,60,450,110,"");
    fl_set_object_callback(obj,help_browserCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,190,180,90,20,"Done");
    fl_set_object_callback(obj,help_doneCB,0);
  fl_end_form();

  fdui->HelpDialog->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

