/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "ITELforms.h"

static FL_PUP_ENTRY fdchoice_itel_source_0[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "SIGINT",	0,	"",	 FL_PUP_NONE},
    { "HUMINT",	0,	"",	 FL_PUP_NONE},
    { "Recon",	0,	"",	 FL_PUP_NONE},
    { "Open Source",	0,	"",	 FL_PUP_NONE},
    {0}
};

static FL_PUP_ENTRY fdchoice_itel_tframe_1[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "Near",	0,	"",	 FL_PUP_NONE},
    { "Far",	0,	"",	 FL_PUP_NONE},
    {0}
};

static FL_PUP_ENTRY fdchoice_2[] =
{ 
    /*  itemtext   callback  shortcut   mode */
    { "Auto Claasify",	0,	"",	 FL_PUP_NONE},
    { "Heir. Classify",	0,	"",	 FL_PUP_NONE},
    {0}
};

FD_bmcintel *create_form_bmcintel(void)
{
  FL_OBJECT *obj;
  FD_bmcintel *fdui = (FD_bmcintel *) fl_calloc(1, sizeof(*fdui));

  fdui->bmcintel = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  fdui->itel_frame[1] = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,10,355,205,95,"Other");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_evidence = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,225,60,410,200,"Evidence");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,0);
  fdui->itel_frame[5] = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,645,270,190,180,"How (Means & Method)");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->itel_frame[2] = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,225,270,190,180,"Where (Location)");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_frame[6] = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,445,270,190,180,"When (Time & Duration)");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->intel_exit = obj = fl_add_button(FL_NORMAL_BUTTON,760,10,80,30,"Exit");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELexitCB,0);
  fdui->intel_source = obj = fl_add_browser(FL_NORMAL_BROWSER,235,140,390,50,"");
    fl_set_object_color(obj,FL_TOP_BCOL,FL_TOP_BCOL);
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_field[21] = obj = fl_add_input(FL_NORMAL_INPUT,285,300,120,20,"Nation");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,2);
  fdui->itel_field[20] = obj = fl_add_input(FL_NORMAL_INPUT,285,280,120,20,"Region");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[22] = obj = fl_add_input(FL_NORMAL_INPUT,285,320,120,20,"Locale");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,3);
  fdui->itel_field[25] = obj = fl_add_input(FL_NORMAL_INPUT,285,380,120,20,"Latitude");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,6);
  fdui->itel_field[26] = obj = fl_add_input(FL_NORMAL_INPUT,285,400,120,20,"Longitude");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,7);
  fdui->itel_field[27] = obj = fl_add_input(FL_NORMAL_INPUT,285,420,120,20,"Altitude");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,8);
  fdui->itel_frame[3] = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,645,70,190,80,"What (Activities & Events)");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_field[28] = obj = fl_add_input(FL_NORMAL_INPUT,705,80,120,20,"Subject");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,0);
  fdui->itel_field[29] = obj = fl_add_input(FL_NORMAL_INPUT,705,100,120,20,"Action");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_mission = obj = fl_add_choice(FL_NORMAL_CHOICE2,280,90,140,20,"");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelmissionCB,1);
  fdui->itel_source = obj = fl_add_choice(FL_NORMAL_CHOICE2,485,90,140,20,"");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelevidenceCB,1);
    fl_set_choice_entries(obj, fdchoice_itel_source_0);
    fl_set_choice(obj,1);
  fdui->itel_belief = obj = fl_add_choice(FL_NORMAL_CHOICE2,280,115,140,20,"Belief");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_disbelief = obj = fl_add_choice(FL_NORMAL_CHOICE2,485,115,140,20,"Disbelief");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,1);
  fdui->itel_add = obj = fl_add_button(FL_NORMAL_BUTTON,380,30,60,20,"Add");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,2);
  fdui->itel_sources = obj = fl_add_browser(FL_NORMAL_BROWSER,235,200,110,55,"");
    fl_set_object_color(obj,FL_WHITE,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_BOTTOM_BCOL);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_field[23] = obj = fl_add_input(FL_NORMAL_INPUT,285,340,120,20,"City");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,4);
  fdui->itel_field[24] = obj = fl_add_input(FL_NORMAL_INPUT,285,360,120,20,"Structure");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,5);
  fdui->itel_frame[0] = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,10,80,205,265,"Who (People & Groups)");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_field[4] = obj = fl_add_input(FL_NORMAL_INPUT,85,90,120,20,"Report Org.");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[5] = obj = fl_add_input(FL_NORMAL_INPUT,85,110,120,20,"Report Affil.");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[6] = obj = fl_add_input(FL_NORMAL_INPUT,85,130,120,20,"Report Desc.");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[7] = obj = fl_add_input(FL_NORMAL_INPUT,85,150,120,20,"Report Name");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[8] = obj = fl_add_input(FL_NORMAL_INPUT,85,175,120,20,"Enemy Org.");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[9] = obj = fl_add_input(FL_NORMAL_INPUT,85,195,120,20,"Enemy Affil.");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[10] = obj = fl_add_input(FL_NORMAL_INPUT,85,215,120,20,"Enemy Desc.");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[11] = obj = fl_add_input(FL_NORMAL_INPUT,85,235,120,20,"Enemy Name");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[12] = obj = fl_add_input(FL_NORMAL_INPUT,85,260,120,20,"Ally Org.");
    fl_set_object_lcolor(obj,FL_DARKVIOLET);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[13] = obj = fl_add_input(FL_NORMAL_INPUT,85,280,120,20,"Ally Affil.");
    fl_set_object_lcolor(obj,FL_DARKVIOLET);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[14] = obj = fl_add_input(FL_NORMAL_INPUT,85,300,120,20,"Ally Desc.");
    fl_set_object_lcolor(obj,FL_DARKVIOLET);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[16] = obj = fl_add_input(FL_NORMAL_INPUT,85,365,120,20,"Other Org.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[19] = obj = fl_add_input(FL_NORMAL_INPUT,85,425,120,20,"Other Name");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[18] = obj = fl_add_input(FL_NORMAL_INPUT,85,405,120,20,"Other Desc.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[17] = obj = fl_add_input(FL_NORMAL_INPUT,85,385,120,20,"Other Affil.");
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[15] = obj = fl_add_input(FL_NORMAL_INPUT,85,320,120,20,"Ally Name");
    fl_set_object_lcolor(obj,FL_DARKVIOLET);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[30] = obj = fl_add_input(FL_NORMAL_INPUT,705,120,120,20,"Object");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[42] = obj = fl_add_input(FL_NORMAL_INPUT,705,420,120,20,"Adjective");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[40] = obj = fl_add_input(FL_NORMAL_INPUT,705,380,120,20,"# Injuries");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[39] = obj = fl_add_input(FL_NORMAL_INPUT,705,360,120,20,"Casualties");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[41] = obj = fl_add_input(FL_NORMAL_INPUT,705,400,120,20,"Est. Cost");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[38] = obj = fl_add_input(FL_NORMAL_INPUT,705,340,120,20,"Desc. 3");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[37] = obj = fl_add_input(FL_NORMAL_INPUT,705,320,120,20,"Desc. 2");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[36] = obj = fl_add_input(FL_NORMAL_INPUT,705,300,120,20,"Desc. 1");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[35] = obj = fl_add_input(FL_NORMAL_INPUT,705,280,120,20,"Action");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_frame[4] = obj = fl_add_labelframe(FL_ENGRAVED_FRAME,645,160,190,100,"Why (Goal/Intent/Purpose)");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_field[31] = obj = fl_add_input(FL_NORMAL_INPUT,705,170,120,20,"Strategic");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[33] = obj = fl_add_input(FL_NORMAL_INPUT,705,210,120,20,"Tactical");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[32] = obj = fl_add_input(FL_NORMAL_INPUT,705,190,120,20,"Operation");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_field[34] = obj = fl_add_input(FL_NORMAL_INPUT,705,230,120,20,"Task");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelsubjectCB,1);
  fdui->itel_end_day = obj = fl_add_counter(FL_SIMPLE_COUNTER,535,340,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 1, 31);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_end_mon = obj = fl_add_counter(FL_SIMPLE_COUNTER,505,340,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 1, 12);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_end_year = obj = fl_add_counter(FL_SIMPLE_COUNTER,455,340,50,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 2000, 2010);
    fl_set_counter_value(obj, 2002);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_tframe = obj = fl_add_choice(FL_NORMAL_CHOICE2,520,425,110,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_choice_entries(obj, fdchoice_itel_tframe_1);
    fl_set_choice(obj,1);
  fdui->itel_end_hour = obj = fl_add_counter(FL_SIMPLE_COUNTER,565,340,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 24);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_end_min = obj = fl_add_counter(FL_SIMPLE_COUNTER,595,340,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 31);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_start_year = obj = fl_add_counter(FL_SIMPLE_COUNTER,455,300,50,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 2000, 2010);
    fl_set_counter_value(obj, 2002);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_start_mon = obj = fl_add_counter(FL_SIMPLE_COUNTER,505,300,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 1, 12);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_start_day = obj = fl_add_counter(FL_SIMPLE_COUNTER,535,300,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 1, 12);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_start_hour = obj = fl_add_counter(FL_SIMPLE_COUNTER,565,300,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 24);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_start_min = obj = fl_add_counter(FL_SIMPLE_COUNTER,595,300,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 31);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_dur_year = obj = fl_add_counter(FL_SIMPLE_COUNTER,455,380,50,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 10);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_dur_mon = obj = fl_add_counter(FL_SIMPLE_COUNTER,505,380,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 12);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_dur_day = obj = fl_add_counter(FL_SIMPLE_COUNTER,535,380,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 12);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_dur_hour = obj = fl_add_counter(FL_SIMPLE_COUNTER,565,380,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 24);
    fl_set_counter_value(obj, 1);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_dur_min = obj = fl_add_counter(FL_SIMPLE_COUNTER,595,380,30,20,"");
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 0, 31);
    fl_set_counter_step(obj, 1, 1);
  fdui->itel_field[48] = obj = fl_add_input(FL_NORMAL_INPUT,85,10,130,20,"Info ID");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_field[49] = obj = fl_add_input(FL_NORMAL_INPUT,85,30,130,20,"Prepared By");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_field[50] = obj = fl_add_input(FL_NORMAL_INPUT,85,50,130,20,"Prepared On");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,450,280,170,20,"   Year      Mon    Day     Hr     Min");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);

  fdui->itel_mode = fl_bgn_group();
  fdui->itel_evidmode = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,230,20,90,20,"Message");
    fl_set_object_color(obj,FL_COL1,FL_RED);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
    fl_set_button(obj, 1);
  fdui->itel_datamode = obj = fl_add_round3dbutton(FL_RADIO_BUTTON,230,35,100,20,"Database");
    fl_set_object_color(obj,FL_COL1,FL_CHARTREUSE);
    fl_set_object_lcolor(obj,FL_CHARTREUSE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fl_end_group();

  obj = fl_add_text(FL_NORMAL_TEXT,225,5,45,20,"Mode:");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->intel_browser = obj = fl_add_browser(FL_NORMAL_BROWSER,345,200,280,55,"");
    fl_set_object_color(obj,FL_WHITE,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_BOTTOM_BCOL);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,ITELnoneCB,0);
  fdui->itel_newfile = obj = fl_add_button(FL_NORMAL_BUTTON,320,30,60,20,"New");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,0);
  fdui->itel_openfile = obj = fl_add_button(FL_NORMAL_BUTTON,380,10,60,20,"Append");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,1);
  fdui->itep_apply = obj = fl_add_button(FL_NORMAL_BUTTON,320,10,60,20,"Apply");
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,4);
  obj = fl_add_button(FL_NORMAL_BUTTON,500,10,60,20,"Close");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,9);
  obj = fl_add_button(FL_NORMAL_BUTTON,500,30,60,20,"Clear");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,8);
  fdui->itel_browse = obj = fl_add_button(FL_NORMAL_BUTTON,440,10,60,20,"Browse");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,5);
  fdui->itel_nextrec = obj = fl_add_button(FL_NORMAL_BUTTON,470,30,30,20,">");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,6);
  fdui->itel_firstrec = obj = fl_add_button(FL_NORMAL_BUTTON,440,30,30,20,"<<");
    fl_set_object_lcolor(obj,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelbuttonCB,3);
  fdui->itel_field[47] = obj = fl_add_input(FL_NORMAL_INPUT,250,30,65,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  fdui->itel_field[43] = obj = fl_add_input(FL_NORMAL_INPUT,455,320,170,20,"Start Time");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->itel_field[44] = obj = fl_add_input(FL_NORMAL_INPUT,455,360,170,20,"End Time");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->itel_field[45] = obj = fl_add_input(FL_NORMAL_INPUT,455,400,170,20,"Duration");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->itel_field[46] = obj = fl_add_input(FL_NORMAL_INPUT,455,425,65,20,"Time Frame");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  fdui->itel_field[1] = obj = fl_add_input(FL_NORMAL_INPUT,485,70,140,20,"Hypothesis");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_field[51] = obj = fl_add_input(FL_NORMAL_INPUT,280,70,140,20,"Mission");
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,itelocationCB,1);
  fdui->itel_rules = obj = fl_add_lightbutton(FL_PUSH_BUTTON,570,30,90,20,"Enable Rules");
    fl_set_object_color(obj,FL_RED,FL_GREEN);
    fl_set_object_callback(obj,BMCnoneCB,0);
    fl_set_button(obj, 1);
  obj = fl_add_choice(FL_NORMAL_CHOICE2,570,10,90,20,"");
    fl_set_object_callback(obj,itelbuttonCB,7);
    fl_set_choice_entries(obj, fdchoice_2);
    fl_set_choice(obj,1);
  fl_end_form();

  fdui->bmcintel->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

