/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "SIMforms.h"

FD_simgraph *create_form_simgraph(void)
{
  FL_OBJECT *obj;
  FD_simgraph *fdui = (FD_simgraph *) fl_calloc(1, sizeof(*fdui));

  fdui->simgraph = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
    fl_set_object_lalign(obj,FL_ALIGN_BOTTOM);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,695,55,145,70,"Run Mode");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,515,55,170,270,"Results");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,695,140,145,185,"Graph Control");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,760,10,80,30,"Dismiss");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMexitCB,0);
  fdui->canvas = obj = fl_add_glcanvas(FL_NORMAL_CANVAS,55,5,425,425,"");
    fl_set_object_color(obj,FL_WHITE,FL_BLACK);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->viewpos = obj = fl_add_slider(FL_HOR_NICE_SLIDER,50,435,435,20,"");
    fl_set_object_color(obj,FL_COL1,FL_RED);
    fl_set_object_callback(obj,SIMsliderCB,0);
    fl_set_slider_bounds(obj, 0, 200);
    fl_set_slider_value(obj, 30);
    fl_set_slider_size(obj, 0.15);
    fl_set_slider_step(obj, 1);
    fl_set_slider_increment(obj, 10, 1);
     fl_set_slider_return(obj, FL_RETURN_END_CHANGED);
  fdui->zoomer = obj = fl_add_slider(FL_VERT_NICE_SLIDER,485,20,20,415,"Zoom");
    fl_set_object_color(obj,FL_COL1,FL_CYAN);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMzoomCB,0);
    fl_set_slider_bounds(obj, -90, 90);
    fl_set_slider_value(obj, 80);
    fl_set_slider_size(obj, 0.15);
    fl_set_slider_step(obj, 1);
    fl_set_slider_increment(obj, 5, 1);
     fl_set_slider_return(obj, FL_RETURN_END_CHANGED);
  fdui->elevation = obj = fl_add_slider(FL_VERT_NICE_SLIDER,30,25,20,410,"Tilt");
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMelevCB,0);
    fl_set_slider_bounds(obj, 0, 200);
    fl_set_slider_value(obj, 50);
    fl_set_slider_size(obj, 0.15);
    fl_set_slider_step(obj, 1);
    fl_set_slider_increment(obj, 5, 1);
     fl_set_slider_return(obj, FL_RETURN_END_CHANGED);
  fdui->h3d_scale = obj = fl_add_counter(FL_NORMAL_COUNTER,590,340,95,20,"V. Scale");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMrefreshCB,0);
    fl_set_counter_precision(obj, 0);
    fl_set_counter_bounds(obj, 1, 100);
    fl_set_counter_value(obj, 10);
    fl_set_counter_step(obj, 1, 2);
  fdui->sim_step = obj = fl_add_input(FL_NORMAL_INPUT,585,10,95,25,"Iteration");
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,725,155,85,25,"Refresh");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMrefreshCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,725,185,85,25,"Pause");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMcontrolCB,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,725,215,85,25,"Resume");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMcontrolCB,1);
  obj = fl_add_button(FL_NORMAL_BUTTON,725,290,85,25,"Replay");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMcontrolCB,3);
  obj = fl_add_button(FL_NORMAL_BUTTON,725,245,85,25,"Step");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMcontrolCB,2);
  fdui->sim_results[0] = obj = fl_add_input(FL_NORMAL_INPUT,525,70,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[1] = obj = fl_add_input(FL_NORMAL_INPUT,525,95,75,20,"Results[1]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[2] = obj = fl_add_input(FL_NORMAL_INPUT,525,120,75,20,"Results[2]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[3] = obj = fl_add_input(FL_NORMAL_INPUT,525,145,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[4] = obj = fl_add_input(FL_NORMAL_INPUT,525,170,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[5] = obj = fl_add_input(FL_NORMAL_INPUT,525,195,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[6] = obj = fl_add_input(FL_NORMAL_INPUT,525,220,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[7] = obj = fl_add_input(FL_NORMAL_INPUT,525,245,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[8] = obj = fl_add_input(FL_NORMAL_INPUT,525,270,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_results[9] = obj = fl_add_input(FL_NORMAL_INPUT,525,295,75,20,"Results[0]");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lcolor(obj,FL_WHEAT);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);

  fdui->simgrp_mode = fl_bgn_group();
  fdui->sim_realtime = obj = fl_add_checkbutton(FL_RADIO_BUTTON,700,70,95,20,"Realtime");
    fl_set_object_color(obj,FL_COL1,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
  fdui->sim_playback = obj = fl_add_checkbutton(FL_RADIO_BUTTON,700,95,95,20,"Playback");
    fl_set_object_color(obj,FL_COL1,FL_GREEN);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMnoneCB,0);
    fl_set_button(obj, 1);
  fl_end_group();

  obj = fl_add_button(FL_NORMAL_BUTTON,795,80,35,25,"Go!");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,SIMstartCB,0);
  fl_end_form();

  fdui->simgraph->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

