# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/unixODBC
pkglibdir = $(libdir)/unixODBC
pkgincludedir = $(includedir)/unixODBC

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = @target_alias@
target_triplet = @target@
AS = @AS@
AWK = gawk
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
ECHO = echo
EXEEXT = 
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = @GMSGFMT@
ICONV_CHAR_ENCODING = auto-search
ICONV_UNICODE_ENCODING = auto-search
IDL = @IDL@
INCLTDL = -I${top_srcdir}/libltdl
KDE_EXTRA_RPATH = @KDE_EXTRA_RPATH@
KDE_INCLUDES = @KDE_INCLUDES@
KDE_LDFLAGS = @KDE_LDFLAGS@
KDE_RPATH = @KDE_RPATH@
KDE_USE_FINAL_FALSE = @KDE_USE_FINAL_FALSE@
KDE_USE_FINAL_TRUE = @KDE_USE_FINAL_TRUE@
LEX = flex
LFLAGS =  -i
LIBADD_CRYPT = -lcrypt
LIBADD_DL = 
LIBCOMPAT = @LIBCOMPAT@
LIBCRYPT = @LIBCRYPT@
LIBDL = @LIBDL@
LIBICONV = 
LIBJPEG = @LIBJPEG@
LIBLTDL = ${top_builddir}/libltdl/libltdlc.la
LIBMICO = @LIBMICO@
LIBNSL = -lnsl
LIBPNG = 
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBSOCKET = 
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = @LIBUCB@
LIBZ = 
LIB_KAB = @LIB_KAB@
LIB_KDECORE = @LIB_KDECORE@
LIB_KDEUI = @LIB_KDEUI@
LIB_KFILE = @LIB_KFILE@
LIB_KFM = @LIB_KFM@
LIB_KFORMULA = @LIB_KFORMULA@
LIB_KHTML = @LIB_KHTML@
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = @LIB_KIO@
LIB_MEDIATOOL = @LIB_MEDIATOOL@
LIB_QT = -lqt $(LIBPNG) -lXext $(LIB_X11)
LIB_SMB = @LIB_SMB@
LIB_VERSION = 1:0:0
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = 
MSGFMT = @MSGFMT@
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = unixODBC
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PTH_CFLAGS = 
PTH_CPPFLAGS = 
PTH_LDFLAGS = 
PTH_LIBS = 
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = 
QT_LDFLAGS = 
RANLIB = ranlib
READLINE = -lreadline -lcurses
SHLIBEXT = .so
STRIP = strip
TOPSUBDIRS = @TOPSUBDIRS@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_NLS = @USE_NLS@
VERSION = 2.2.3
XGETTEXT = @XGETTEXT@
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = @X_EXTRA_LIBS@
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
YACC = bison -y
all_includes = @all_includes@
all_libraries = @all_libraries@
idldir = @idldir@
kde_appsdir = @kde_appsdir@
kde_bindir = @kde_bindir@
kde_cgidir = @kde_cgidir@
kde_confdir = @kde_confdir@
kde_datadir = @kde_datadir@
kde_htmldir = @kde_htmldir@
kde_icondir = @kde_icondir@
kde_includes = @kde_includes@
kde_libraries = @kde_libraries@
kde_locale = @kde_locale@
kde_mimedir = @kde_mimedir@
kde_minidir = @kde_minidir@
kde_servicesdir = @kde_servicesdir@
kde_servicetypesdir = @kde_servicetypesdir@
kde_sounddir = @kde_sounddir@
kde_toolbardir = @kde_toolbardir@
kde_wallpaperdir = @kde_wallpaperdir@
micodir = @micodir@
msql_headers = 
msql_libraries = 
qt_includes = 
qt_libraries = 
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

lib_LTLIBRARIES = libodbcinst.la

INCLUDES = -I../include 	-DSYSTEM_FILE_PATH=\"${prefix}/etc\" 	-DDEFLIB_PATH=\"${exec_prefix}/lib\" 	-DSHLIBEXT=\".so\" 	$(INCLTDL)


libodbcinst_la_LDFLAGS =      -version-info 1:0:0     -export-dynamic 


libodbcinst_la_LIBADD =  	../ini/libinilc.la 	../log/libloglc.la 	../lst/liblstlc.la 	$(LIBLTDL) $(LIBADD_DL) 


libodbcinst_la_DEPENDENCIES =      ../log/libloglc.la     ../ini/libinilc.la     ../lst/liblstlc.la     $(LIBLTDL) 


sysconf_DATA = 

libodbcinst_la_SOURCES =  	ODBCINSTConstructProperties.c 	ODBCINSTDestructProperties.c 	ODBCINSTSetProperty.c 	ODBCINSTValidateProperties.c 	ODBCINSTValidateProperty.c 	SQLConfigDataSource.c 	SQLConfigDriver.c 	SQLCreateDataSource.c 	SQLGetAvailableDrivers.c 	SQLGetConfigMode.c 	SQLGetInstalledDrivers.c 	SQLGetPrivateProfileString.c 	SQLGetTranslator.c 	SQLInstallDriverEx.c 	SQLInstallDriverManager.c 	SQLInstallTranslatorEx.c 	SQLInstallerError.c 	SQLManageDataSources.c 	SQLPostInstallerError.c 	SQLReadFileDSN.c 	SQLRemoveDSNFromIni.c 	SQLRemoveDriver.c 	SQLRemoveDriverManager.c 	SQLRemoveTranslator.c 	SQLSetConfigMode.c 	SQLValidDSN.c 	SQLWriteDSNToIni.c 	SQLWriteFileDSN.c 	SQLWritePrivateProfileString.c 	_logging.c 	_odbcinst_ConfigModeINI.c 	_odbcinst_UserINI.c 	_odbcinst_SystemINI.c 	_odbcinst_GetSections.c 	_odbcinst_GetEntries.c 	_SQLGetInstalledDrivers.c 	_SQLWriteInstalledDrivers.c


libodbcinstlc_la_LDFLAGS = 

noinst_LTLIBRARIES = libodbcinstlc.la

libodbcinstlc_la_SOURCES =  	ODBCINSTConstructProperties.c 	ODBCINSTDestructProperties.c 	ODBCINSTSetProperty.c 	ODBCINSTValidateProperties.c 	ODBCINSTValidateProperty.c 	SQLConfigDataSource.c 	SQLConfigDriver.c 	SQLCreateDataSource.c 	SQLGetAvailableDrivers.c 	SQLGetConfigMode.c 	SQLGetInstalledDrivers.c 	SQLGetPrivateProfileString.c 	SQLGetTranslator.c 	SQLInstallDriverEx.c 	SQLInstallDriverManager.c 	SQLInstallTranslatorEx.c 	SQLInstallerError.c 	SQLManageDataSources.c 	SQLPostInstallerError.c 	SQLReadFileDSN.c 	SQLRemoveDSNFromIni.c 	SQLRemoveDriver.c 	SQLRemoveDriverManager.c 	SQLRemoveTranslator.c 	SQLSetConfigMode.c 	SQLValidDSN.c 	SQLWriteDSNToIni.c 	SQLWriteFileDSN.c 	SQLWritePrivateProfileString.c 	_logging.c 	_odbcinst_ConfigModeINI.c 	_odbcinst_UserINI.c 	_odbcinst_SystemINI.c 	_odbcinst_GetSections.c 	_odbcinst_GetEntries.c 	_SQLGetInstalledDrivers.c 	_SQLWriteInstalledDrivers.c

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES) $(noinst_LTLIBRARIES)


DEFS =  -DPACKAGE=\"unixODBC\" -DVERSION=\"2.2.3\" -DYYTEXT_POINTER=1 -DHAVE_SYS_SEM_H=1 -DHAVE_DLFCN_H=1 -DLTDL_SHLIB_EXT=\".so\" -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_LIBCRYPT=1 -DHAVE_LIBM=1 -DHAVE_READLINE_HISTORY_H=1 -DHAVE_READLINE=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_SYS_TIME_H=1 -DSIZEOF_LONG=4 -DHAVE_LONG_LONG=1 -DHAVE_STRCASECMP=1 -DHAVE_STRNCASECMP=1 -DHAVE_VSNPRINTF=1 -DHAVE_STRTOL=1 -DHAVE_LIBPTHREAD=1 -D_REENTRANT=1 -DHAVE_LOCALTIME_R=1 -DHAVE_FTOK=1 -DHAVE_SEMGET=1 -DHAVE_SHMGET=1 -DHAVE_SEMOP=1 -DHAVE_SNPRINTF=1 -DNEED_SEMUNDO_UNION=1 -DCOLLECT_STATS=1 -DSTDC_HEADERS=1 -DHAVE_MALLOC_H=1 -DHAVE_UNISTD_H=1 -DHAVE_PWD_H=1 -DHAVE_CRYPT_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STRINGS_H=1 -DHAVE_STRING_H=1 -DHAVE_LOCALE_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_SEM_H=1 -DHAVE_DIRENT_H=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_VPRINTF=1 -DHAVE_PUTENV=1 -DHAVE_SOCKET=1 -DHAVE_STRDUP=1 -DHAVE_STRSTR=1 -DHAVE_SETENV=1  -I. -I$(srcdir) 
CPPFLAGS = 
LDFLAGS = 
LIBS = -lm  -lpthread
libodbcinst_la_OBJECTS =  ODBCINSTConstructProperties.lo \
ODBCINSTDestructProperties.lo ODBCINSTSetProperty.lo \
ODBCINSTValidateProperties.lo ODBCINSTValidateProperty.lo \
SQLConfigDataSource.lo SQLConfigDriver.lo SQLCreateDataSource.lo \
SQLGetAvailableDrivers.lo SQLGetConfigMode.lo SQLGetInstalledDrivers.lo \
SQLGetPrivateProfileString.lo SQLGetTranslator.lo SQLInstallDriverEx.lo \
SQLInstallDriverManager.lo SQLInstallTranslatorEx.lo \
SQLInstallerError.lo SQLManageDataSources.lo SQLPostInstallerError.lo \
SQLReadFileDSN.lo SQLRemoveDSNFromIni.lo SQLRemoveDriver.lo \
SQLRemoveDriverManager.lo SQLRemoveTranslator.lo SQLSetConfigMode.lo \
SQLValidDSN.lo SQLWriteDSNToIni.lo SQLWriteFileDSN.lo \
SQLWritePrivateProfileString.lo _logging.lo _odbcinst_ConfigModeINI.lo \
_odbcinst_UserINI.lo _odbcinst_SystemINI.lo _odbcinst_GetSections.lo \
_odbcinst_GetEntries.lo _SQLGetInstalledDrivers.lo \
_SQLWriteInstalledDrivers.lo
libodbcinstlc_la_LIBADD = 
libodbcinstlc_la_OBJECTS =  ODBCINSTConstructProperties.lo \
ODBCINSTDestructProperties.lo ODBCINSTSetProperty.lo \
ODBCINSTValidateProperties.lo ODBCINSTValidateProperty.lo \
SQLConfigDataSource.lo SQLConfigDriver.lo SQLCreateDataSource.lo \
SQLGetAvailableDrivers.lo SQLGetConfigMode.lo SQLGetInstalledDrivers.lo \
SQLGetPrivateProfileString.lo SQLGetTranslator.lo SQLInstallDriverEx.lo \
SQLInstallDriverManager.lo SQLInstallTranslatorEx.lo \
SQLInstallerError.lo SQLManageDataSources.lo SQLPostInstallerError.lo \
SQLReadFileDSN.lo SQLRemoveDSNFromIni.lo SQLRemoveDriver.lo \
SQLRemoveDriverManager.lo SQLRemoveTranslator.lo SQLSetConfigMode.lo \
SQLValidDSN.lo SQLWriteDSNToIni.lo SQLWriteFileDSN.lo \
SQLWritePrivateProfileString.lo _logging.lo _odbcinst_ConfigModeINI.lo \
_odbcinst_UserINI.lo _odbcinst_SystemINI.lo _odbcinst_GetSections.lo \
_odbcinst_GetEntries.lo _SQLGetInstalledDrivers.lo \
_SQLWriteInstalledDrivers.lo
CFLAGS = -g -O2 -pthread
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DATA =  $(sysconf_DATA)

DIST_COMMON =  README ChangeLog Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libodbcinst_la_SOURCES) $(libodbcinstlc_la_SOURCES)
OBJECTS = $(libodbcinst_la_OBJECTS) $(libodbcinstlc_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps odbcinst/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

mostlyclean-noinstLTLIBRARIES:

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)

distclean-noinstLTLIBRARIES:

maintainer-clean-noinstLTLIBRARIES:

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libodbcinst.la: $(libodbcinst_la_OBJECTS) $(libodbcinst_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libodbcinst_la_LDFLAGS) $(libodbcinst_la_OBJECTS) $(libodbcinst_la_LIBADD) $(LIBS)

libodbcinstlc.la: $(libodbcinstlc_la_OBJECTS) $(libodbcinstlc_la_DEPENDENCIES)
	$(LINK)  $(libodbcinstlc_la_LDFLAGS) $(libodbcinstlc_la_OBJECTS) $(libodbcinstlc_la_LIBADD) $(LIBS)

install-sysconfDATA: $(sysconf_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(sysconfdir)
	@list='$(sysconf_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(sysconfdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(sysconfdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(sysconfdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(sysconfdir)/$$p; \
	  fi; fi; \
	done

uninstall-sysconfDATA:
	@$(NORMAL_UNINSTALL)
	list='$(sysconf_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(sysconfdir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = odbcinst

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
_logging.lo _logging.o : _logging.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
_odbcinst_ConfigModeINI.lo _odbcinst_ConfigModeINI.o : \
	_odbcinst_ConfigModeINI.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
ODBCINSTConstructProperties.lo ODBCINSTConstructProperties.o : \
	ODBCINSTConstructProperties.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
ODBCINSTDestructProperties.lo ODBCINSTDestructProperties.o : \
	ODBCINSTDestructProperties.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
_odbcinst_GetEntries.lo _odbcinst_GetEntries.o : _odbcinst_GetEntries.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
_odbcinst_GetSections.lo _odbcinst_GetSections.o : \
	_odbcinst_GetSections.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
ODBCINSTSetProperty.lo ODBCINSTSetProperty.o : ODBCINSTSetProperty.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
_odbcinst_SystemINI.lo _odbcinst_SystemINI.o : _odbcinst_SystemINI.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
_odbcinst_UserINI.lo _odbcinst_UserINI.o : _odbcinst_UserINI.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
ODBCINSTValidateProperties.lo ODBCINSTValidateProperties.o : \
	ODBCINSTValidateProperties.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
ODBCINSTValidateProperty.lo ODBCINSTValidateProperty.o : \
	ODBCINSTValidateProperty.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLConfigDataSource.lo SQLConfigDataSource.o : SQLConfigDataSource.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLConfigDriver.lo SQLConfigDriver.o : SQLConfigDriver.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLCreateDataSource.lo SQLCreateDataSource.o : SQLCreateDataSource.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLGetAvailableDrivers.lo SQLGetAvailableDrivers.o : \
	SQLGetAvailableDrivers.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLGetConfigMode.lo SQLGetConfigMode.o : SQLGetConfigMode.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
_SQLGetInstalledDrivers.lo _SQLGetInstalledDrivers.o : \
	_SQLGetInstalledDrivers.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLGetInstalledDrivers.lo SQLGetInstalledDrivers.o : \
	SQLGetInstalledDrivers.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLGetPrivateProfileString.lo SQLGetPrivateProfileString.o : \
	SQLGetPrivateProfileString.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLGetTranslator.lo SQLGetTranslator.o : SQLGetTranslator.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLInstallDriverEx.lo SQLInstallDriverEx.o : SQLInstallDriverEx.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLInstallDriverManager.lo SQLInstallDriverManager.o : \
	SQLInstallDriverManager.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLInstallerError.lo SQLInstallerError.o : SQLInstallerError.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLInstallTranslatorEx.lo SQLInstallTranslatorEx.o : \
	SQLInstallTranslatorEx.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLManageDataSources.lo SQLManageDataSources.o : SQLManageDataSources.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLPostInstallerError.lo SQLPostInstallerError.o : \
	SQLPostInstallerError.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLReadFileDSN.lo SQLReadFileDSN.o : SQLReadFileDSN.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLRemoveDriverManager.lo SQLRemoveDriverManager.o : \
	SQLRemoveDriverManager.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLRemoveDriver.lo SQLRemoveDriver.o : SQLRemoveDriver.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLRemoveDSNFromIni.lo SQLRemoveDSNFromIni.o : SQLRemoveDSNFromIni.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLRemoveTranslator.lo SQLRemoveTranslator.o : SQLRemoveTranslator.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLSetConfigMode.lo SQLSetConfigMode.o : SQLSetConfigMode.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLValidDSN.lo SQLValidDSN.o : SQLValidDSN.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLWriteDSNToIni.lo SQLWriteDSNToIni.o : SQLWriteDSNToIni.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
SQLWriteFileDSN.lo SQLWriteFileDSN.o : SQLWriteFileDSN.c \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h
_SQLWriteInstalledDrivers.lo _SQLWriteInstalledDrivers.o : \
	_SQLWriteInstalledDrivers.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h
SQLWritePrivateProfileString.lo SQLWritePrivateProfileString.o : \
	SQLWritePrivateProfileString.c ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLTLIBRARIES install-sysconfDATA
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLTLIBRARIES uninstall-sysconfDATA
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir) $(DESTDIR)$(sysconfdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-libLTLIBRARIES \
		mostlyclean-noinstLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-libLTLIBRARIES clean-noinstLTLIBRARIES clean-compile \
		clean-libtool clean-tags clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-libLTLIBRARIES distclean-noinstLTLIBRARIES \
		distclean-compile distclean-libtool distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-noinstLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES \
mostlyclean-noinstLTLIBRARIES distclean-noinstLTLIBRARIES \
clean-noinstLTLIBRARIES maintainer-clean-noinstLTLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool uninstall-sysconfDATA \
install-sysconfDATA tags mostlyclean-tags distclean-tags clean-tags \
maintainer-clean-tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
