    3    F2T2EA                       0     0.0     0.0 H
      6     Evidence_Sources
  Intel
  SIGINT
  Sensor
  TCTCell
  UAV
  PAC3
      4     Hypothesis
  F2T
  Target
  Execute
  Assess
      3     Assessments
  Emerging				0.75     100.0
  Active				0.75     100.0
  Neutralized			0.75     100.0
#  Evidence labels follow. Must be 3, each < 5 chars
Lat      Lon      Alt
#  Default time units follow. Must be: Sec, Min, Hour, or Days
Min
<EOF>
