/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ANSITERM_H
#define _XFWF_ANSITERM_H
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
void  XfwfAnsiWrite(
#if NeedFunctionPrototypes
Widget,char *,int 
#endif
);
typedef struct {
	    int rows, columns;
	} XfwfResizeInfo;

#include <Xfwf/scroll.h>
#ifndef XtNrows
#define XtNrows "rows"
#endif
#ifndef XtCRows
#define XtCRows "Rows"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcolumns
#define XtNcolumns "columns"
#endif
#ifndef XtCColumns
#define XtCColumns "Columns"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNfont
#define XtNfont "font"
#endif
#ifndef XtCFont
#define XtCFont "Font"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNboldfont
#define XtNboldfont "boldfont"
#endif
#ifndef XtCBoldfont
#define XtCBoldfont "Boldfont"
#endif
#ifndef XtRXFontStruct
#define XtRXFontStruct "XFontStruct"
#endif

#ifndef XtNmargin
#define XtNmargin "margin"
#endif
#ifndef XtCMargin
#define XtCMargin "Margin"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRXFwfColor
#define XtRXFwfColor "XFwfColor"
#endif

#ifndef XtNkeyCallback
#define XtNkeyCallback "keyCallback"
#endif
#ifndef XtCKeyCallback
#define XtCKeyCallback "KeyCallback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNresizeCallback
#define XtNresizeCallback "resizeCallback"
#endif
#ifndef XtCResizeCallback
#define XtCResizeCallback "ResizeCallback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNscrollCallback
#define XtNscrollCallback "scrollCallback"
#endif
#ifndef XtCScrollCallback
#define XtCScrollCallback "ScrollCallback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNscrollResponse
#define XtNscrollResponse "scrollResponse"
#endif
#ifndef XtCScrollResponse
#define XtCScrollResponse "ScrollResponse"
#endif
#ifndef XtRXTCallbackProc
#define XtRXTCallbackProc "XTCallbackProc"
#endif

typedef struct _XfwfAnsiTermClassRec *XfwfAnsiTermWidgetClass;
typedef struct _XfwfAnsiTermRec *XfwfAnsiTermWidget;
externalref WidgetClass xfwfAnsiTermWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_ANSITERM_H */
