/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ARTTEXT_H
#define _XFWF_ARTTEXT_H
#include <Xfwf/TextOut.h>
_XFUNCPROTOBEGIN
void XfwfSetArticleText(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#ifndef XtNbodyFont
#define XtNbodyFont "bodyFont"
#endif
#ifndef XtCBodyFont
#define XtCBodyFont "BodyFont"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNquoteFont
#define XtNquoteFont "quoteFont"
#endif
#ifndef XtCQuoteFont
#define XtCQuoteFont "QuoteFont"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNheaderItemFont
#define XtNheaderItemFont "headerItemFont"
#endif
#ifndef XtCHeaderItemFont
#define XtCHeaderItemFont "HeaderItemFont"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNheaderValueFont
#define XtNheaderValueFont "headerValueFont"
#endif
#ifndef XtCHeaderValueFont
#define XtCHeaderValueFont "HeaderValueFont"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNbodyColor
#define XtNbodyColor "bodyColor"
#endif
#ifndef XtCBodyColor
#define XtCBodyColor "BodyColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNquoteColor
#define XtNquoteColor "quoteColor"
#endif
#ifndef XtCQuoteColor
#define XtCQuoteColor "QuoteColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNheaderItemColor
#define XtNheaderItemColor "headerItemColor"
#endif
#ifndef XtCHeaderItemColor
#define XtCHeaderItemColor "HeaderItemColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNheaderValueColor
#define XtNheaderValueColor "headerValueColor"
#endif
#ifndef XtCHeaderValueColor
#define XtCHeaderValueColor "HeaderValueColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNquoteChar
#define XtNquoteChar "quoteChar"
#endif
#ifndef XtCQuoteChar
#define XtCQuoteChar "QuoteChar"
#endif
#ifndef XtRChar
#define XtRChar "Char"
#endif

typedef struct _XfwfArticleTextClassRec *XfwfArticleTextWidgetClass;
typedef struct _XfwfArticleTextRec *XfwfArticleTextWidget;
externalref WidgetClass xfwfArticleTextWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_ARTTEXT_H */
