/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ENTRYP_H
#define _XFWF_ENTRYP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/Entry.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfEntryClassPart;

typedef struct _XfwfEntryClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfEntryClassPart xfwfEntry_class;
} XfwfEntryClassRec;

typedef struct {
/* resources */
String  text;
XtCallbackList  activate;
XtCallbackList  modifyCallback;
XtCallbackList  afterModifyCallback;
String  valid;
int  max;
Boolean  echo;
XFontStruct * font;
Pixel  foreground;
Boolean  blinkingCursor;
int  blinkInterval;
int  selectThreshold;
Boolean  killSelection;
/* private state */
int  text_len;
int  text_pos;
int  text_start;
XComposeStatus  compose_stat;
GC  ngc;
GC  rgc;
GC  cursorGC;
Boolean  cursorActive;
Boolean  cursorVisible;
XtIntervalId  blinktimer;
Boolean  selecting;
Boolean  selected;
int  selectx;
int  selecty;
int  selectStart;
int  selectEnd;
} XfwfEntryPart;

typedef struct _XfwfEntryRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfEntryPart xfwfEntry;
} XfwfEntryRec;

externalref XfwfEntryClassRec xfwfEntryClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_ENTRYP_H */
