/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_FOLDTREEP_H
#define _XFWF_FOLDTREEP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/FoldTree.h>
_XFUNCPROTOBEGIN
typedef void (*layout_Proc)(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#define XtInherit_layout ((layout_Proc) _XtInherit)

typedef struct {
/* methods */
layout_Proc layout;
/* class variables */
} XfwfFoldingTreeClassPart;

typedef struct _XfwfFoldingTreeClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfFoldingTreeClassPart xfwfFoldingTree_class;
} XfwfFoldingTreeClassRec;

typedef struct {
/* resources */
Boolean  expanded;
XfwfIcon * iconExpand;
XfwfIcon * iconCollapse;
XfwfIcon * iconNoExpand;
Boolean  shrinkToFit;
Dimension  lineWidth;
Pixel  lineColor;
Dimension  childSpace;
XtCallbackList  activate;
/* private state */
Widget  tree_icon;
GC  line_gc;
Position * xpos;
Position * ypos;
} XfwfFoldingTreePart;

typedef struct _XfwfFoldingTreeRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfFoldingTreePart xfwfFoldingTree;
} XfwfFoldingTreeRec;

externalref XfwfFoldingTreeClassRec xfwfFoldingTreeClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_FOLDTREEP_H */
