/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_MENUBAR_H
#define _XFWF_MENUBAR_H
#include <Xfwf/Rows.h>
_XFUNCPROTOBEGIN
Boolean  XfwfCallProcessMenu(
#if NeedFunctionPrototypes
Widget,Widget ,Cursor 
#endif
);
typedef struct _XfwfMenuBarClassRec *XfwfMenuBarWidgetClass;
typedef struct _XfwfMenuBarRec *XfwfMenuBarWidget;
externalref WidgetClass xfwfMenuBarWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_MENUBAR_H */
