/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_PCBARP_H
#define _XFWF_PCBARP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/PcBar.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfPcBarClassPart;

typedef struct _XfwfPcBarClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfPcBarClassPart xfwfPcBar_class;
} XfwfPcBarClassRec;

typedef struct {
/* resources */
Pixel  foreground;
Pixel  textcolor;
int  percentage;
Boolean  displaypc;
Boolean  showzero;
Boolean  vertical;
Boolean  usetextcolor;
XFontStruct * font;
/* private state */
GC  draw_gc;
GC  text_gc;
} XfwfPcBarPart;

typedef struct _XfwfPcBarRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfPcBarPart xfwfPcBar;
} XfwfPcBarRec;

externalref XfwfPcBarClassRec xfwfPcBarClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_PCBARP_H */
