/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_PCBAR_H
#define _XFWF_PCBAR_H
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
void  XfwfPcBarSetPercentage(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNtextcolor
#define XtNtextcolor "textcolor"
#endif
#ifndef XtCTextcolor
#define XtCTextcolor "Textcolor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNpercentage
#define XtNpercentage "percentage"
#endif
#ifndef XtCPercentage
#define XtCPercentage "Percentage"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNdisplaypc
#define XtNdisplaypc "displaypc"
#endif
#ifndef XtCDisplaypc
#define XtCDisplaypc "Displaypc"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNshowzero
#define XtNshowzero "showzero"
#endif
#ifndef XtCShowzero
#define XtCShowzero "Showzero"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNvertical
#define XtNvertical "vertical"
#endif
#ifndef XtCVertical
#define XtCVertical "Vertical"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNusetextcolor
#define XtNusetextcolor "usetextcolor"
#endif
#ifndef XtCUsetextcolor
#define XtCUsetextcolor "Usetextcolor"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNfont
#define XtNfont "font"
#endif
#ifndef XtCFont
#define XtCFont "Font"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

typedef struct _XfwfPcBarClassRec *XfwfPcBarWidgetClass;
typedef struct _XfwfPcBarRec *XfwfPcBarWidget;
externalref WidgetClass xfwfPcBarWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_PCBAR_H */
