/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_PIEMENUP_H
#define _XFWF_PIEMENUP_H
#include <X11/ShellP.h>
#include <Xfwf/PieMenu.h>
_XFUNCPROTOBEGIN
#define MAXITEMS 6 


#define MAXACTIONS 6 


#define MAXPARAMS 6 


typedef struct {
	    char *label;
	    int nactions;
	    char *action[MAXACTIONS];
	    int num_params[MAXACTIONS];
	    char *params[MAXACTIONS][MAXPARAMS];
	} LabelAction;

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfPieMenuClassPart;

typedef struct _XfwfPieMenuClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ShellClassPart shell_class;
OverrideShellClassPart overrideShell_class;
XfwfPieMenuClassPart xfwfPieMenu_class;
} XfwfPieMenuClassRec;

typedef struct {
/* resources */
Dimension  holeRadius;
String  menu;
Pixel  background1;
Pixel  background2;
Pixel  background3;
Pixel  background4;
Pixel  background5;
Pixel  background6;
Pixel  foreground;
Pixel  foreground1;
Pixel  foreground2;
Pixel  foreground3;
Pixel  foreground4;
Pixel  foreground5;
Pixel  foreground6;
XFontStruct * font;
XFontStruct * font1;
XFontStruct * font2;
XFontStruct * font3;
XFontStruct * font4;
XFontStruct * font5;
XFontStruct * font6;
Dimension  frameWidth;
/* private state */
String  menu_copy;
LabelAction  items[MAXACTIONS];
GC  gc[MAXITEMS];
GC  linegc;
GC  lightgc;
GC  darkgc;
int  nitems;
Pixmap  emptystip;
Pixmap  stip4;
} XfwfPieMenuPart;

typedef struct _XfwfPieMenuRec {
CorePart core;
CompositePart composite;
ShellPart shell;
OverrideShellPart overrideShell;
XfwfPieMenuPart xfwfPieMenu;
} XfwfPieMenuRec;

externalref XfwfPieMenuClassRec xfwfPieMenuClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_PIEMENUP_H */
