/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_PULLDOWN_H
#define _XFWF_PULLDOWN_H
#include <Xfwf/Button.h>
_XFUNCPROTOBEGIN
#include <Xfwf/TextMenu.h>
#ifndef XtNpopup
#define XtNpopup "popup"
#endif
#ifndef XtCPopup
#define XtCPopup "Popup"
#endif
#ifndef XtRWidget
#define XtRWidget "Widget"
#endif

#ifndef XtNmenu
#define XtNmenu "menu"
#endif
#ifndef XtCMenu
#define XtCMenu "Menu"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNcascaded
#define XtNcascaded "cascaded"
#endif
#ifndef XtCCascaded
#define XtCCascaded "Cascaded"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNhotkey
#define XtNhotkey "hotkey"
#endif
#ifndef XtCHotkey
#define XtCHotkey "Hotkey"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNmenuCursor
#define XtNmenuCursor "menuCursor"
#endif
#ifndef XtCMenuCursor
#define XtCMenuCursor "MenuCursor"
#endif
#ifndef XtRCursor
#define XtRCursor "Cursor"
#endif

#ifndef XtNprepare
#define XtNprepare "prepare"
#endif
#ifndef XtCPrepare
#define XtCPrepare "Prepare"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNchangeSelection
#define XtNchangeSelection "changeSelection"
#endif
#ifndef XtCChangeSelection
#define XtCChangeSelection "ChangeSelection"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XfwfPullDownClassRec *XfwfPullDownWidgetClass;
typedef struct _XfwfPullDownRec *XfwfPullDownWidget;
externalref WidgetClass xfwfPullDownWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_PULLDOWN_H */
