/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ROWCOLP_H
#define _XFWF_ROWCOLP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/RowCol.h>
_XFUNCPROTOBEGIN
typedef void (*layout_Proc)(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#define XtInherit_layout ((layout_Proc) _XtInherit)

typedef struct {
/* methods */
layout_Proc layout;
/* class variables */
} XfwfRowColClassPart;

typedef struct _XfwfRowColClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfRowColClassPart xfwfRowCol_class;
} XfwfRowColClassRec;

typedef struct {
/* resources */
Boolean  storeByRow;
int  rows;
int  columns;
XfwfAlignment  alignment;
Boolean  shrinkToFit;
/* private state */
Dimension  max_width;
Dimension  max_height;
} XfwfRowColPart;

typedef struct _XfwfRowColRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfRowColPart xfwfRowCol;
} XfwfRowColRec;

externalref XfwfRowColClassRec xfwfRowColClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_ROWCOLP_H */
