/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ROWCOL_H
#define _XFWF_ROWCOL_H
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
#ifndef XtNstoreByRow
#define XtNstoreByRow "storeByRow"
#endif
#ifndef XtCStoreByRow
#define XtCStoreByRow "StoreByRow"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNrows
#define XtNrows "rows"
#endif
#ifndef XtCRows
#define XtCRows "Rows"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcolumns
#define XtNcolumns "columns"
#endif
#ifndef XtCColumns
#define XtCColumns "Columns"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNalignment
#define XtNalignment "alignment"
#endif
#ifndef XtCAlignment
#define XtCAlignment "Alignment"
#endif
#ifndef XtRXFwfAlignment
#define XtRXFwfAlignment "XFwfAlignment"
#endif

#ifndef XtNshrinkToFit
#define XtNshrinkToFit "shrinkToFit"
#endif
#ifndef XtCShrinkToFit
#define XtCShrinkToFit "ShrinkToFit"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

typedef struct _XfwfRowColClassRec *XfwfRowColWidgetClass;
typedef struct _XfwfRowColRec *XfwfRowColWidget;
externalref WidgetClass xfwfRowColWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_ROWCOL_H */
