/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ROWSP_H
#define _XFWF_ROWSP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/Rows.h>
_XFUNCPROTOBEGIN
typedef void (*layout_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_layout ((layout_Proc) _XtInherit)

typedef struct {
/* methods */
layout_Proc layout;
/* class variables */
} XfwfRowsClassPart;

typedef struct _XfwfRowsClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfRowsClassPart xfwfRows_class;
} XfwfRowsClassRec;

typedef struct {
/* resources */
Boolean  alignTop;
/* private state */
} XfwfRowsPart;

typedef struct _XfwfRowsRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfRowsPart xfwfRows;
} XfwfRowsRec;

externalref XfwfRowsClassRec xfwfRowsClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_ROWSP_H */
