/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_SCRWIN3P_H
#define _XFWF_SCRWIN3P_H
#include <Xfwf/BoardP.h>
#include <Xfwf/ScrWin3.h>
_XFUNCPROTOBEGIN
typedef void (*scroll_response_Proc)(
#if NeedFunctionPrototypes
Widget ,XtPointer ,XtPointer 
#endif
);
#define XtInherit_scroll_response ((scroll_response_Proc) _XtInherit)

typedef struct {
/* methods */
scroll_response_Proc scroll_response;
/* class variables */
} XfwfScrolledWindow3ClassPart;

typedef struct _XfwfScrolledWindow3ClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfScrolledWindow3ClassPart xfwfScrolledWindow3_class;
} XfwfScrolledWindow3ClassRec;

typedef struct {
/* resources */
Dimension  spacing;
Dimension  scrollbarWidth;
Dimension  colHdrHeight;
Dimension  rowHdrWidth;
Dimension  shadowWidth;
Boolean  hideHScrollbar;
Boolean  hideVScrollbar;
int  vScrollAmount;
int  hScrollAmount;
Position  initialX;
Position  initialY;
XtCallbackList  scrollCallback;
XtCallbackProc  scrollResponse;
/* private state */
Widget  ulboard;
Widget  CORNER;
Widget  cboard;
Widget  CCW;
Widget  rboard;
Widget  RCW;
Widget  vscroll;
Widget  hscroll;
Widget  frame;
Widget  board;
Widget  CW;
Boolean  initializing;
} XfwfScrolledWindow3Part;

typedef struct _XfwfScrolledWindow3Rec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfScrolledWindow3Part xfwfScrolledWindow3;
} XfwfScrolledWindow3Rec;

externalref XfwfScrolledWindow3ClassRec xfwfScrolledWindow3ClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_SCRWIN3P_H */
