/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_SWIPBTN_H
#define _XFWF_SWIPBTN_H
#include <Xfwf/Button.h>
_XFUNCPROTOBEGIN
typedef struct _XfwfSWIPButtonClassRec *XfwfSWIPButtonWidgetClass;
typedef struct _XfwfSWIPButtonRec *XfwfSWIPButtonWidget;
externalref WidgetClass xfwfSWIPButtonWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_SWIPBTN_H */
