/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_TEXTMENU_H
#define _XFWF_TEXTMENU_H
#include <X11/Shell.h>
_XFUNCPROTOBEGIN
typedef struct {
	    int n;
	    String label;
	} XfwfTextMenuData;

#ifndef XtNfont
#define XtNfont "font"
#endif
#ifndef XtCFont
#define XtCFont "Font"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNtablist
#define XtNtablist "tablist"
#endif
#ifndef XtCTablist
#define XtCTablist "Tablist"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNmenu
#define XtNmenu "menu"
#endif
#ifndef XtCMenu
#define XtCMenu "Menu"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNactive
#define XtNactive "active"
#endif
#ifndef XtCActive
#define XtCActive "Active"
#endif
#ifndef XtRLong
#define XtRLong "Long"
#endif

#ifndef XtNselection
#define XtNselection "selection"
#endif
#ifndef XtCSelection
#define XtCSelection "Selection"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcursor
#define XtNcursor "cursor"
#endif
#ifndef XtCCursor
#define XtCCursor "Cursor"
#endif
#ifndef XtRCursor
#define XtRCursor "Cursor"
#endif

#ifndef XtNactivate
#define XtNactivate "activate"
#endif
#ifndef XtCActivate
#define XtCActivate "Activate"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNchangeSelection
#define XtNchangeSelection "changeSelection"
#endif
#ifndef XtCChangeSelection
#define XtCChangeSelection "ChangeSelection"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XfwfTextMenuClassRec *XfwfTextMenuWidgetClass;
typedef struct _XfwfTextMenuRec *XfwfTextMenuWidget;
externalref WidgetClass xfwfTextMenuWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_TEXTMENU_H */
