/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_TEXTOUT_H
#define _XFWF_TEXTOUT_H
#include <Xfwf/Common.h>
_XFUNCPROTOBEGIN
void XfwfAddText(
#if NeedFunctionPrototypes
Widget,char *,int ,int ,int 
#endif
);
void XfwfEraseText(
#if NeedFunctionPrototypes
Widget
#endif
);
void XfwfComputeTextOutSize(
#if NeedFunctionPrototypes
Widget,Dimension *,Dimension *
#endif
);
#ifndef XtNinternalOffset
#define XtNinternalOffset "internalOffset"
#endif
#ifndef XtCInternalOffset
#define XtCInternalOffset "InternalOffset"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNfont1
#define XtNfont1 "font1"
#endif
#ifndef XtCFont1
#define XtCFont1 "Font1"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont2
#define XtNfont2 "font2"
#endif
#ifndef XtCFont2
#define XtCFont2 "Font2"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont3
#define XtNfont3 "font3"
#endif
#ifndef XtCFont3
#define XtCFont3 "Font3"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont4
#define XtNfont4 "font4"
#endif
#ifndef XtCFont4
#define XtCFont4 "Font4"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNcolor1
#define XtNcolor1 "color1"
#endif
#ifndef XtCColor1
#define XtCColor1 "Color1"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor2
#define XtNcolor2 "color2"
#endif
#ifndef XtCColor2
#define XtCColor2 "Color2"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor3
#define XtNcolor3 "color3"
#endif
#ifndef XtCColor3
#define XtCColor3 "Color3"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor4
#define XtNcolor4 "color4"
#endif
#ifndef XtCColor4
#define XtCColor4 "Color4"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor5
#define XtNcolor5 "color5"
#endif
#ifndef XtCColor5
#define XtCColor5 "Color5"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor6
#define XtNcolor6 "color6"
#endif
#ifndef XtCColor6
#define XtCColor6 "Color6"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor7
#define XtNcolor7 "color7"
#endif
#ifndef XtCColor7
#define XtCColor7 "Color7"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor8
#define XtNcolor8 "color8"
#endif
#ifndef XtCColor8
#define XtCColor8 "Color8"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

typedef struct _XfwfTextOutClassRec *XfwfTextOutWidgetClass;
typedef struct _XfwfTextOutRec *XfwfTextOutWidget;
externalref WidgetClass xfwfTextOutWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_TEXTOUT_H */
