/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_TEXTOUTP_H
#define _XFWF_TEXTOUTP_H
#include <Xfwf/CommonP.h>
#include <Xfwf/TextOut.h>
_XFUNCPROTOBEGIN
typedef struct _textChunk {
		String			text;
		int			font;
		int			color;
		int			nl;
		struct _textChunk	*next;
	} TextChunk;

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfTextOutClassPart;

typedef struct _XfwfTextOutClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfTextOutClassPart xfwfTextOut_class;
} XfwfTextOutClassRec;

typedef struct {
/* resources */
Dimension  internalOffset;
XFontStruct * font1;
XFontStruct * font2;
XFontStruct * font3;
XFontStruct * font4;
Pixel  color1;
Pixel  color2;
Pixel  color3;
Pixel  color4;
Pixel  color5;
Pixel  color6;
Pixel  color7;
Pixel  color8;
/* private state */
GC  ngc;
TextChunk * text;
TextChunk * tail;
} XfwfTextOutPart;

typedef struct _XfwfTextOutRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfTextOutPart xfwfTextOut;
} XfwfTextOutRec;

externalref XfwfTextOutClassRec xfwfTextOutClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_TEXTOUTP_H */
