/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_TOGGLEP_H
#define _XFWF_TOGGLEP_H
#include <Xfwf/ButtonP.h>
#include <Xfwf/Toggle.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfToggleClassPart;

typedef struct _XfwfToggleClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfLabelClassPart xfwfLabel_class;
XfwfButtonClassPart xfwfButton_class;
XfwfToggleClassPart xfwfToggle_class;
} XfwfToggleClassRec;

typedef struct {
/* resources */
XtCallbackList  onCallback;
XtCallbackList  offCallback;
Boolean  on;
XfwfIcon * onIcon;
XfwfIcon * offIcon;
/* private state */
GC  on_gc;
GC  off_gc;
Dimension  saveLeftMargin;
} XfwfTogglePart;

typedef struct _XfwfToggleRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfLabelPart xfwfLabel;
XfwfButtonPart xfwfButton;
XfwfTogglePart xfwfToggle;
} XfwfToggleRec;

externalref XfwfToggleClassRec xfwfToggleClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_TOGGLEP_H */
