    3    Foreign_Launch               0     0.0     0.0 H
      6     Evidence_Sources
  SBIRS
  STRAT
  Political
  Intel
  Radar
  Fire
      4     Hypothesis
  Foreign Launch
  Anticipated
  Friendly Impact
  Space Launch
      3     Conclusions
  Hostile			0.75     100.0
  Deliberate        0.75     100.0
  ICBM              0.75     100.0
#  Evidence labels follow. Must be 3, each < 5 chars
Lat      Lon      Alt
#  Default time units follow. Must be: Sec, Min, Hour, or Days
Min
<EOF>
