// freeobjs.H header file

#ifndef freeobjs_object
#define freeobjs_object

#include "free_list.H"
#include "freetypes.H"

/************************************************************************
*	freeobjs object 						*
************************************************************************/
class C_FREEOBJS : public C_FREE_LIST {

  private:

  protected:

  public:

    C_FREEOBJS();

};


#endif
