/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ALERTP_H
#define _XFWF_ALERTP_H
#include <X11/ShellP.h>
#include <Xfwf/Alert.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfAlertClassPart;

typedef struct _XfwfAlertClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ShellClassPart shell_class;
WMShellClassPart wMShell_class;
VendorShellClassPart vendorShell_class;
TransientShellClassPart transientShell_class;
XfwfAlertClassPart xfwfAlert_class;
} XfwfAlertClassRec;

typedef struct {
/* resources */
XfwfIcon * icon;
String  message;
String  buttons;
int  lastChoice;
XtCallbackList  callback;
/* private state */
Widget  outer;
Widget  iconw;
Widget  labelw;
Widget * buttonw;
int  num_buttons;
} XfwfAlertPart;

typedef struct _XfwfAlertRec {
CorePart core;
CompositePart composite;
ShellPart shell;
WMShellPart wMShell;
VendorShellPart vendorShell;
TransientShellPart transientShell;
XfwfAlertPart xfwfAlert;
} XfwfAlertRec;

externalref XfwfAlertClassRec xfwfAlertClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_ALERTP_H */
