/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ANIMATORP_H
#define _XFWF_ANIMATORP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/Animator.h>
_XFUNCPROTOBEGIN
typedef void (*start_animation_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_start_animation ((start_animation_Proc) _XtInherit)
typedef void (*stop_animation_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_stop_animation ((stop_animation_Proc) _XtInherit)

typedef struct {
/* methods */
start_animation_Proc start_animation;
stop_animation_Proc stop_animation;
/* class variables */
} XfwfAnimatorClassPart;

typedef struct _XfwfAnimatorClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfAnimatorClassPart xfwfAnimator_class;
} XfwfAnimatorClassRec;

typedef struct {
/* resources */
XImage ** images;
Cardinal * intervals;
Cardinal  defaultInterval;
Boolean  cycle;
/* private state */
XtIntervalId  timer;
int  cur_image;
int  cur_interval;
GC  image_gc;
} XfwfAnimatorPart;

typedef struct _XfwfAnimatorRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfAnimatorPart xfwfAnimator;
} XfwfAnimatorRec;

externalref XfwfAnimatorClassRec xfwfAnimatorClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_ANIMATORP_H */
