/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ARTTEXTP_H
#define _XFWF_ARTTEXTP_H
#include <Xfwf/TextOutP.h>
#include <Xfwf/ArtText.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfArticleTextClassPart;

typedef struct _XfwfArticleTextClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfTextOutClassPart xfwfTextOut_class;
XfwfArticleTextClassPart xfwfArticleText_class;
} XfwfArticleTextClassRec;

typedef struct {
/* resources */
XFontStruct * bodyFont;
XFontStruct * quoteFont;
XFontStruct * headerItemFont;
XFontStruct * headerValueFont;
Pixel  bodyColor;
Pixel  quoteColor;
Pixel  headerItemColor;
Pixel  headerValueColor;
char  quoteChar;
/* private state */
} XfwfArticleTextPart;

typedef struct _XfwfArticleTextRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfTextOutPart xfwfTextOut;
XfwfArticleTextPart xfwfArticleText;
} XfwfArticleTextRec;

externalref XfwfArticleTextClassRec xfwfArticleTextClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_ARTTEXTP_H */
