/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_BUTTON_H
#define _XFWF_BUTTON_H
#include <Xfwf/Label.h>
_XFUNCPROTOBEGIN
#ifndef XtNactivate
#define XtNactivate "activate"
#endif
#ifndef XtCActivate
#define XtCActivate "Activate"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNenter
#define XtNenter "enter"
#endif
#ifndef XtCEnter
#define XtCEnter "Enter"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNleave
#define XtNleave "leave"
#endif
#ifndef XtCLeave
#define XtCLeave "Leave"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XfwfButtonClassRec *XfwfButtonWidgetClass;
typedef struct _XfwfButtonRec *XfwfButtonWidget;
externalref WidgetClass xfwfButtonWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_BUTTON_H */
