/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ENFORCER_H
#define _XFWF_ENFORCER_H
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
typedef struct _XfwfEnforcerClassRec *XfwfEnforcerWidgetClass;
typedef struct _XfwfEnforcerRec *XfwfEnforcerWidget;
externalref WidgetClass xfwfEnforcerWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_ENFORCER_H */
