/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ENFORCERP_H
#define _XFWF_ENFORCERP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/Enforcer.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfEnforcerClassPart;

typedef struct _XfwfEnforcerClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfEnforcerClassPart xfwfEnforcer_class;
} XfwfEnforcerClassRec;

typedef struct {
/* resources */
/* private state */
int dummy;
} XfwfEnforcerPart;

typedef struct _XfwfEnforcerRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfEnforcerPart xfwfEnforcer;
} XfwfEnforcerRec;

externalref XfwfEnforcerClassRec xfwfEnforcerClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_ENFORCERP_H */
