/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_FOLDTREE_H
#define _XFWF_FOLDTREE_H
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
#ifndef XtNexpanded
#define XtNexpanded "expanded"
#endif
#ifndef XtCExpanded
#define XtCExpanded "Expanded"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNiconExpand
#define XtNiconExpand "iconExpand"
#endif
#ifndef XtCIconExpand
#define XtCIconExpand "IconExpand"
#endif
#ifndef XtRXFwfIcon
#define XtRXFwfIcon "XFwfIcon"
#endif

#ifndef XtNiconCollapse
#define XtNiconCollapse "iconCollapse"
#endif
#ifndef XtCIconCollapse
#define XtCIconCollapse "IconCollapse"
#endif
#ifndef XtRXFwfIcon
#define XtRXFwfIcon "XFwfIcon"
#endif

#ifndef XtNiconNoExpand
#define XtNiconNoExpand "iconNoExpand"
#endif
#ifndef XtCIconNoExpand
#define XtCIconNoExpand "IconNoExpand"
#endif
#ifndef XtRXFwfIcon
#define XtRXFwfIcon "XFwfIcon"
#endif

#ifndef XtNshrinkToFit
#define XtNshrinkToFit "shrinkToFit"
#endif
#ifndef XtCShrinkToFit
#define XtCShrinkToFit "ShrinkToFit"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNlineWidth
#define XtNlineWidth "lineWidth"
#endif
#ifndef XtCLineWidth
#define XtCLineWidth "LineWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNlineColor
#define XtNlineColor "lineColor"
#endif
#ifndef XtCLineColor
#define XtCLineColor "LineColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNchildSpace
#define XtNchildSpace "childSpace"
#endif
#ifndef XtCChildSpace
#define XtCChildSpace "ChildSpace"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNactivate
#define XtNactivate "activate"
#endif
#ifndef XtCActivate
#define XtCActivate "Activate"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XfwfFoldingTreeClassRec *XfwfFoldingTreeWidgetClass;
typedef struct _XfwfFoldingTreeRec *XfwfFoldingTreeWidget;
externalref WidgetClass xfwfFoldingTreeWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_FOLDTREE_H */
