/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_FRAMEP_H
#define _XFWF_FRAMEP_H
#include <Xfwf/CommonP.h>
#include <Xfwf/Frame.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfFrameClassPart;

typedef struct _XfwfFrameClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
} XfwfFrameClassRec;

typedef struct {
/* resources */
Cursor  cursor;
FrameType  frameType;
Dimension  frameWidth;
Dimension  outerOffset;
Dimension  innerOffset;
ShadowScheme  shadowScheme;
XfwfColor  topShadowColor;
XfwfColor  bottomShadowColor;
Bitmap  topShadowStipple;
Bitmap  bottomShadowStipple;
/* private state */
GC  lightgc;
GC  darkgc;
Pixmap  lightstipple;
Pixmap  darkstipple;
FrameType  old_frame_type;
} XfwfFramePart;

typedef struct _XfwfFrameRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
} XfwfFrameRec;

externalref XfwfFrameClassRec xfwfFrameClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_FRAMEP_H */
