/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_INDICATOR_H
#define _XFWF_INDICATOR_H
#include <Xfwf/Label.h>
_XFUNCPROTOBEGIN
#include <Xfwf/scroll.h>
void XfwfIndicatorSetLabel(
#if NeedFunctionPrototypes
Widget,String 
#endif
);
void XfwfIndicatorMovePoint(
#if NeedFunctionPrototypes
Widget,double 
#endif
);
void XfwfIndicatorGetPoint(
#if NeedFunctionPrototypes
Widget,double *
#endif
);
void XfwfIndicatorSetRange(
#if NeedFunctionPrototypes
Widget,double ,double 
#endif
);
void XfwfIndicatorGetRange(
#if NeedFunctionPrototypes
Widget,double *,double *
#endif
);
#ifndef XtNsliderColor
#define XtNsliderColor "sliderColor"
#endif
#ifndef XtCSliderColor
#define XtCSliderColor "SliderColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNsliderWidth
#define XtNsliderWidth "sliderWidth"
#endif
#ifndef XtCSliderWidth
#define XtCSliderWidth "SliderWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNrangeColor
#define XtNrangeColor "rangeColor"
#endif
#ifndef XtCRangeColor
#define XtCRangeColor "RangeColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNscrollCallback
#define XtNscrollCallback "scrollCallback"
#endif
#ifndef XtCScrollCallback
#define XtCScrollCallback "ScrollCallback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNscrollResponse
#define XtNscrollResponse "scrollResponse"
#endif
#ifndef XtCScrollResponse
#define XtCScrollResponse "ScrollResponse"
#endif
#ifndef XtRXTCallbackProc
#define XtRXTCallbackProc "XTCallbackProc"
#endif

#ifndef XtNsliderFrameWidth
#define XtNsliderFrameWidth "sliderFrameWidth"
#endif
#ifndef XtCSliderFrameWidth
#define XtCSliderFrameWidth "SliderFrameWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNsliderFrameType
#define XtNsliderFrameType "sliderFrameType"
#endif
#ifndef XtCSliderFrameType
#define XtCSliderFrameType "SliderFrameType"
#endif
#ifndef XtRFrameType
#define XtRFrameType "FrameType"
#endif

#ifndef XtNhairlineWidth
#define XtNhairlineWidth "hairlineWidth"
#endif
#ifndef XtCHairlineWidth
#define XtCHairlineWidth "HairlineWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNhairlineMargin
#define XtNhairlineMargin "hairlineMargin"
#endif
#ifndef XtCHairlineMargin
#define XtCHairlineMargin "HairlineMargin"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNhairlineColor
#define XtNhairlineColor "hairlineColor"
#endif
#ifndef XtCHairlineColor
#define XtCHairlineColor "HairlineColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNlabelMargin
#define XtNlabelMargin "labelMargin"
#endif
#ifndef XtCLabelMargin
#define XtCLabelMargin "LabelMargin"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNsliderMargin
#define XtNsliderMargin "sliderMargin"
#endif
#ifndef XtCSliderMargin
#define XtCSliderMargin "SliderMargin"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

typedef struct _XfwfIndicatorClassRec *XfwfIndicatorWidgetClass;
typedef struct _XfwfIndicatorRec *XfwfIndicatorWidget;
externalref WidgetClass xfwfIndicatorWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_INDICATOR_H */
