/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_OPTBUTTN_H
#define _XFWF_OPTBUTTN_H
#include <Xfwf/PullDown.h>
_XFUNCPROTOBEGIN
typedef struct _XfwfOptionButtonClassRec *XfwfOptionButtonWidgetClass;
typedef struct _XfwfOptionButtonRec *XfwfOptionButtonWidget;
externalref WidgetClass xfwfOptionButtonWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_OPTBUTTN_H */
