/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_PAGER_H
#define _XFWF_PAGER_H
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
#ifndef XtNtext
#define XtNtext "text"
#endif
#ifndef XtCText
#define XtCText "Text"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNfontFamily
#define XtNfontFamily "fontFamily"
#endif
#ifndef XtCFontFamily
#define XtCFontFamily "FontFamily"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNroman
#define XtNroman "roman"
#endif
#ifndef XtCRoman
#define XtCRoman "Roman"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNlines
#define XtNlines "lines"
#endif
#ifndef XtCLines
#define XtCLines "Lines"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNwrap
#define XtNwrap "wrap"
#endif
#ifndef XtCWrap
#define XtCWrap "Wrap"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNbaseline
#define XtNbaseline "baseline"
#endif
#ifndef XtCBaseline
#define XtCBaseline "Baseline"
#endif
#ifndef XtRFloat
#define XtRFloat "Float"
#endif

#ifndef XtNmargin
#define XtNmargin "margin"
#endif
#ifndef XtCMargin
#define XtCMargin "Margin"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNtablist
#define XtNtablist "tablist"
#endif
#ifndef XtCTablist
#define XtCTablist "Tablist"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRXFwfColor
#define XtRXFwfColor "XFwfColor"
#endif

typedef struct _XfwfPagerClassRec *XfwfPagerWidgetClass;
typedef struct _XfwfPagerRec *XfwfPagerWidget;
externalref WidgetClass xfwfPagerWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_PAGER_H */
