/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_PIEMENU_H
#define _XFWF_PIEMENU_H
#include <X11/Shell.h>
_XFUNCPROTOBEGIN
#ifndef XtNholeRadius
#define XtNholeRadius "holeRadius"
#endif
#ifndef XtCHoleRadius
#define XtCHoleRadius "HoleRadius"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNmenu
#define XtNmenu "menu"
#endif
#ifndef XtCMenu
#define XtCMenu "Menu"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNbackground1
#define XtNbackground1 "background1"
#endif
#ifndef XtCBackground1
#define XtCBackground1 "Background1"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNbackground2
#define XtNbackground2 "background2"
#endif
#ifndef XtCBackground2
#define XtCBackground2 "Background2"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNbackground3
#define XtNbackground3 "background3"
#endif
#ifndef XtCBackground3
#define XtCBackground3 "Background3"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNbackground4
#define XtNbackground4 "background4"
#endif
#ifndef XtCBackground4
#define XtCBackground4 "Background4"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNbackground5
#define XtNbackground5 "background5"
#endif
#ifndef XtCBackground5
#define XtCBackground5 "Background5"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNbackground6
#define XtNbackground6 "background6"
#endif
#ifndef XtCBackground6
#define XtCBackground6 "Background6"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground1
#define XtNforeground1 "foreground1"
#endif
#ifndef XtCForeground1
#define XtCForeground1 "Foreground1"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground2
#define XtNforeground2 "foreground2"
#endif
#ifndef XtCForeground2
#define XtCForeground2 "Foreground2"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground3
#define XtNforeground3 "foreground3"
#endif
#ifndef XtCForeground3
#define XtCForeground3 "Foreground3"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground4
#define XtNforeground4 "foreground4"
#endif
#ifndef XtCForeground4
#define XtCForeground4 "Foreground4"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground5
#define XtNforeground5 "foreground5"
#endif
#ifndef XtCForeground5
#define XtCForeground5 "Foreground5"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground6
#define XtNforeground6 "foreground6"
#endif
#ifndef XtCForeground6
#define XtCForeground6 "Foreground6"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNfont
#define XtNfont "font"
#endif
#ifndef XtCFont
#define XtCFont "Font"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont1
#define XtNfont1 "font1"
#endif
#ifndef XtCFont1
#define XtCFont1 "Font1"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont2
#define XtNfont2 "font2"
#endif
#ifndef XtCFont2
#define XtCFont2 "Font2"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont3
#define XtNfont3 "font3"
#endif
#ifndef XtCFont3
#define XtCFont3 "Font3"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont4
#define XtNfont4 "font4"
#endif
#ifndef XtCFont4
#define XtCFont4 "Font4"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont5
#define XtNfont5 "font5"
#endif
#ifndef XtCFont5
#define XtCFont5 "Font5"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNfont6
#define XtNfont6 "font6"
#endif
#ifndef XtCFont6
#define XtCFont6 "Font6"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNframeWidth
#define XtNframeWidth "frameWidth"
#endif
#ifndef XtCFrameWidth
#define XtCFrameWidth "FrameWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

typedef struct _XfwfPieMenuClassRec *XfwfPieMenuWidgetClass;
typedef struct _XfwfPieMenuRec *XfwfPieMenuWidget;
externalref WidgetClass xfwfPieMenuWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_PIEMENU_H */
