/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_RADIOGRP_H
#define _XFWF_RADIOGRP_H
#include <Xfwf/Group.h>
_XFUNCPROTOBEGIN
#include <Xfwf/Converters.h>
#ifndef XtNlabels
#define XtNlabels "labels"
#endif
#ifndef XtCLabels
#define XtCLabels "Labels"
#endif
#ifndef XtRXFwfStringArray
#define XtRXFwfStringArray "XFwfStringArray"
#endif

typedef struct _XfwfRadioGroupClassRec *XfwfRadioGroupWidgetClass;
typedef struct _XfwfRadioGroupRec *XfwfRadioGroupWidget;
externalref WidgetClass xfwfRadioGroupWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_RADIOGRP_H */
