/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_RADIOGRPP_H
#define _XFWF_RADIOGRPP_H
#include <Xfwf/GroupP.h>
#include <Xfwf/RadioGrp.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfRadioGroupClassPart;

typedef struct _XfwfRadioGroupClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfRowColClassPart xfwfRowCol_class;
XfwfGroupClassPart xfwfGroup_class;
XfwfRadioGroupClassPart xfwfRadioGroup_class;
} XfwfRadioGroupClassRec;

typedef struct {
/* resources */
XfwfStringArray  labels;
/* private state */
} XfwfRadioGroupPart;

typedef struct _XfwfRadioGroupRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfRowColPart xfwfRowCol;
XfwfGroupPart xfwfGroup;
XfwfRadioGroupPart xfwfRadioGroup;
} XfwfRadioGroupRec;

externalref XfwfRadioGroupClassRec xfwfRadioGroupClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_RADIOGRPP_H */
