/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_ROWS_H
#define _XFWF_ROWS_H
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
#ifndef XtNalignTop
#define XtNalignTop "alignTop"
#endif
#ifndef XtCAlignTop
#define XtCAlignTop "AlignTop"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

typedef struct _XfwfRowsClassRec *XfwfRowsWidgetClass;
typedef struct _XfwfRowsRec *XfwfRowsWidget;
externalref WidgetClass xfwfRowsWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_ROWS_H */
