/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_SCROLLWINP_H
#define _XFWF_SCROLLWINP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/ScrollWin.h>
_XFUNCPROTOBEGIN
typedef void (*scroll_response_Proc)(
#if NeedFunctionPrototypes
Widget ,XtPointer ,XtPointer 
#endif
);
#define XtInherit_scroll_response ((scroll_response_Proc) _XtInherit)

typedef struct {
/* methods */
scroll_response_Proc scroll_response;
/* class variables */
} XfwfScrolledWindowClassPart;

typedef struct _XfwfScrolledWindowClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfScrolledWindowClassPart xfwfScrolledWindow_class;
} XfwfScrolledWindowClassRec;

typedef struct {
/* resources */
Dimension  spacing;
Dimension  scrollbarWidth;
Dimension  shadowWidth;
Boolean  hideHScrollbar;
Boolean  hideVScrollbar;
int  vScrollAmount;
int  hScrollAmount;
Position  initialX;
Position  initialY;
XtCallbackList  scrollCallback;
XtCallbackProc  scrollResponse;
/* private state */
Widget  vscroll;
Widget  hscroll;
Widget  frame;
Widget  board;
Widget  CW;
Boolean  initializing;
XtCallbackProc  vscroll_resp;
XtCallbackProc  hscroll_resp;
} XfwfScrolledWindowPart;

typedef struct _XfwfScrolledWindowRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfScrolledWindowPart xfwfScrolledWindow;
} XfwfScrolledWindowRec;

externalref XfwfScrolledWindowClassRec xfwfScrolledWindowClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_SCROLLWINP_H */
