/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_SLIDER4P_H
#define _XFWF_SLIDER4P_H
#include <Xfwf/Slider2P.h>
#include <Xfwf/Slider4.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfSlider4ClassPart;

typedef struct _XfwfSlider4ClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfLabelClassPart xfwfLabel_class;
XfwfSlider2ClassPart xfwfSlider2_class;
XfwfSlider4ClassPart xfwfSlider4_class;
} XfwfSlider4ClassRec;

typedef struct {
/* resources */
XfwfColor  sashColor;
Pixmap  sashPixmap;
FrameType  sashFrameType;
Dimension  sashFrameWidth;
Boolean  resizeEqualSides;
/* private state */
GC  sashgc;
GC  sashlightgc;
GC  sashdarkgc;
Boolean  resize_in_progress;
} XfwfSlider4Part;

typedef struct _XfwfSlider4Rec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfLabelPart xfwfLabel;
XfwfSlider2Part xfwfSlider2;
XfwfSlider4Part xfwfSlider4;
} XfwfSlider4Rec;

externalref XfwfSlider4ClassRec xfwfSlider4ClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_SLIDER4P_H */
