/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_SLIDER4_H
#define _XFWF_SLIDER4_H
#include <Xfwf/Slider2.h>
_XFUNCPROTOBEGIN
#ifndef XtNsashColor
#define XtNsashColor "sashColor"
#endif
#ifndef XtCSashColor
#define XtCSashColor "SashColor"
#endif
#ifndef XtRXFwfColor
#define XtRXFwfColor "XFwfColor"
#endif

#ifndef XtNsashPixmap
#define XtNsashPixmap "sashPixmap"
#endif
#ifndef XtCSashPixmap
#define XtCSashPixmap "SashPixmap"
#endif
#ifndef XtRPixmap
#define XtRPixmap "Pixmap"
#endif

#ifndef XtNsashFrameType
#define XtNsashFrameType "sashFrameType"
#endif
#ifndef XtCSashFrameType
#define XtCSashFrameType "SashFrameType"
#endif
#ifndef XtRFrameType
#define XtRFrameType "FrameType"
#endif

#ifndef XtNsashFrameWidth
#define XtNsashFrameWidth "sashFrameWidth"
#endif
#ifndef XtCSashFrameWidth
#define XtCSashFrameWidth "SashFrameWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNresizeEqualSides
#define XtNresizeEqualSides "resizeEqualSides"
#endif
#ifndef XtCResizeEqualSides
#define XtCResizeEqualSides "ResizeEqualSides"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

typedef struct _XfwfSlider4ClassRec *XfwfSlider4WidgetClass;
typedef struct _XfwfSlider4Rec *XfwfSlider4Widget;
externalref WidgetClass xfwfSlider4WidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_SLIDER4_H */
