/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_SPINLABELP_H
#define _XFWF_SPINLABELP_H
#include <Xfwf/LabelP.h>
#include <Xfwf/SpinLabel.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfSpinLabelClassPart;

typedef struct _XfwfSpinLabelClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfLabelClassPart xfwfLabel_class;
XfwfSpinLabelClassPart xfwfSpinLabel_class;
} XfwfSpinLabelClassRec;

typedef struct {
/* resources */
Pixel  arrowForeground;
XtCallbackList  callback;
Dimension  labelframeWidth;
FrameType  labelframeType;
Boolean  horizontal;
/* private state */
Widget  _child[3];
} XfwfSpinLabelPart;

typedef struct _XfwfSpinLabelRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfLabelPart xfwfLabel;
XfwfSpinLabelPart xfwfSpinLabel;
} XfwfSpinLabelRec;

externalref XfwfSpinLabelClassRec xfwfSpinLabelClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_SPINLABELP_H */
