/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_TABSP_H
#define _XFWF_TABSP_H
#include <Xfwf/BoardP.h>
#include <Xfwf/Tabs.h>
_XFUNCPROTOBEGIN
typedef void (*border_highlight_Proc)(
#if NeedFunctionPrototypes
void
#endif
);
#define XtInherit_border_highlight ((border_highlight_Proc) _XtInherit)
typedef void (*border_unhighlight_Proc)(
#if NeedFunctionPrototypes
void
#endif
);
#define XtInherit_border_unhighlight ((border_unhighlight_Proc) _XtInherit)

typedef struct {
/* methods */
border_highlight_Proc border_highlight;
border_unhighlight_Proc border_unhighlight;
/* class variables */
} XfwfTabsClassPart;

typedef struct _XfwfTabsClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfTabsClassPart xfwfTabs_class;
} XfwfTabsClassRec;

typedef struct {
/* resources */
XfwfColor  foreground;
TabsOrientation  orientation;
int  lefttabs;
int  righttabs;
XfwfStringArray  labels;
int  tabWidthPercentage;
int  cornerwidth;
int  cornerheight;
int  textmargin;
XfwfColor  tabcolor;
XFontStruct * font;
XtCallbackList  activate;
/* private state */
GC  textgc;
GC  topgc;
GC  bottomgc;
GC  backgc;
GC  fillgc;
int * tabwidths;
int * offsets;
} XfwfTabsPart;

typedef struct _XfwfTabsRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfTabsPart xfwfTabs;
} XfwfTabsRec;

externalref XfwfTabsClassRec xfwfTabsClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_TABSP_H */
