/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_TEXTMENUP_H
#define _XFWF_TEXTMENUP_H
#include <X11/ShellP.h>
#include <Xfwf/TextMenu.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfTextMenuClassPart;

typedef struct _XfwfTextMenuClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ShellClassPart shell_class;
OverrideShellClassPart overrideShell_class;
XfwfTextMenuClassPart xfwfTextMenu_class;
} XfwfTextMenuClassRec;

typedef struct {
/* resources */
XFontStruct * font;
Pixel  foreground;
String  tablist;
String  menu;
long  active;
int  selection;
Cursor  cursor;
XtCallbackList  activate;
XtCallbackList  changeSelection;
/* private state */
Cardinal  nitems;
char * shortcut;
Position * offset;
String * item;
Position * line;
GC  gc;
GC  rvgc;
GC  graygc;
int * tabs;
int  itemheight;
} XfwfTextMenuPart;

typedef struct _XfwfTextMenuRec {
CorePart core;
CompositePart composite;
ShellPart shell;
OverrideShellPart overrideShell;
XfwfTextMenuPart xfwfTextMenu;
} XfwfTextMenuRec;

externalref XfwfTextMenuClassRec xfwfTextMenuClassRec;

_XFUNCPROTOEND
#endif /* _XFWF_TEXTMENUP_H */
