/* Generated by wbuild
 * (generator version 3.1)
 */
#ifndef _XFWF_TOGGLE_H
#define _XFWF_TOGGLE_H
#include <Xfwf/Button.h>
_XFUNCPROTOBEGIN
#ifndef XtNonCallback
#define XtNonCallback "onCallback"
#endif
#ifndef XtCOnCallback
#define XtCOnCallback "OnCallback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNoffCallback
#define XtNoffCallback "offCallback"
#endif
#ifndef XtCOffCallback
#define XtCOffCallback "OffCallback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNon
#define XtNon "on"
#endif
#ifndef XtCOn
#define XtCOn "On"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNonIcon
#define XtNonIcon "onIcon"
#endif
#ifndef XtCOnIcon
#define XtCOnIcon "OnIcon"
#endif
#ifndef XtRXFwfIcon
#define XtRXFwfIcon "XFwfIcon"
#endif

#ifndef XtNoffIcon
#define XtNoffIcon "offIcon"
#endif
#ifndef XtCOffIcon
#define XtCOffIcon "OffIcon"
#endif
#ifndef XtRXFwfIcon
#define XtRXFwfIcon "XFwfIcon"
#endif

typedef struct _XfwfToggleClassRec *XfwfToggleWidgetClass;
typedef struct _XfwfToggleRec *XfwfToggleWidget;
externalref WidgetClass xfwfToggleWidgetClass;
_XFUNCPROTOEND
#endif /* _XFWF_TOGGLE_H */
