/* Automatically generated by po2tbl.sed from gODBCConfig.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"gODBCConfig - ODBC Data Source Administrator", 2},
  {"Add", 3},
  {"Remove", 4},
  {"Configure...", 5},
  {"\
User data source configuration is stored in your home directory. This allows \
you configure data access without having to be system administrator", 6},
  {"Name", 7},
  {"Description", 8},
  {"Driver", 9},
  {"User DSN", 10},
  {"\
System data sources are shared among all users of this machine.These data \
sources may also be used by system services. Only the administrator can \
configure system data sources.", 11},
  {"System DSN", 12},
  {"\
These drivers facilitate communication between the Driver Manager and the \
data server. Many ODBC drivers  for Linux can be downloaded from the \
Internet while others are obtained from your database vendor.", 13},
  {"Driver Lib", 14},
  {"Setup Lib", 15},
  {"Drivers", 16},
  {"\
Tracing allows you to create logs of the calls to ODBC drivers. Great for \
support people, or to aid you in debugging applications.\n\
You must be 'root' to set", 17},
  {"Browse", 18},
  {"Trace File", 19},
  {"Tracing On", 20},
  {"Tracing", 21},
  {"\
Open DataBase Connectivity (ODBC) was developed to be an Open and portable \
standard for accessing data. unixODBC implements this standard for \
Linux/UNIX.", 22},
  {"http://www.unixodbc.org", 23},
  {"Database System", 24},
  {"Credits", 25},
  {"Application", 26},
  {"Driver Manager", 27},
  {"odbcinst.ini", 28},
  {"odbc.ini", 29},
  {"Config", 30},
  {"About", 31},
  {"gODBCConfig - Appication", 32},
  {"\
The Application communicates with the Driver Manager using the standard ODBC \
calls.\n\
\n\
The application does not care; where the data is stored, how it is stored, \
or even how the system is configured to access the data.\n\
\n\
The Application only needs to know the data source name (DSN)\n\
\n\
The Application is not hard wired to a particular database system. This \
allows the user to select a different database system using the ODBCConfig \
Tool.", 33},
  {"gODBCConfig - Driver Manager", 34},
  {"\
The Driver Manager carries out a number of functions, such as:\n\
1. Resolve data source names via odbcinst lib)\n\
2. Loads any required drivers\n\
3. Calls the drivers exposed functions to communicate with the database. \
Some functionality, such as listing all Data Source, is only present in the \
Driver Manager or via odbcinst lib).", 35},
  {" ", 36},
  {"ODBCConfig - Drivers", 37},
  {"\
The ODBC Drivers contain code specific to a Database System and provides a \
set of callable functions to the Driver Manager.\n\
Drivers may implement some database functionality when it is required by \
ODBC and is not present in the Database System.\n\
Drivers may also translate data types.\n\
\n\
ODBC Drivers can be obtained from the Internet or directly from the Database \
vendor.\n\
\n\
Check http://www.unixodbc.org for drivers", 38},
  {"ODBCConfig - Database Systems", 39},
  {"\
Perhaps the most common type of Database System today is an SQL Server\n\
\n\
SQL Servers with Heavy Functionality\n\
  ADABAS-D\n\
  Empress\n\
  Sybase - www.sybase.com\n\
  Oracle - www.oracle.com\n\
\n\
SQL Servers with Lite Functionality\n\
  MiniSQL\n\
  MySQL\n\
  Solid\n\
\n\
The Database System may be running on the local machine or on a remote \
machine. It may also store its information in a variety of ways. This does \
not matter to an ODBC application because the Driver Manager and the Driver \
provides a consistent interface to the Database System.", 40},
  {"ODBCConfig - odbc.ini", 41},
  {"\
This is the main configuration file for ODBC.\n\
It contains Data Source configuration.\n\
\n\
It is used by the Driver Manager to determine, from a given Data Source \
Name, such things as the name of the Driver.\n\
\n\
It is a simple text file but is configured using the ODBCConfig tool.\n\
The User data sources are typically stored in ~/.odbc.ini while the System \
data sources are stored in /usr/local/etc/odbc.ini\n", 42},
  {"ODBCConfig", 43},
  {"\
This is the program you are using now. This program allows the user to \
easily configure ODBC.", 44},
  {"ODBCConfig - odbcinst.ini", 45},
  {"\
odbcinst.ini contains a list of all installed ODBC Drivers. Each entry also \
contains some information about the driver such as the file name(s) of the \
driver.\n\
\n\
An entry should be made when an ODBC driver is installed and removed when \
the driver is uninstalled. This can be done using ODBCConfig or the odbcinst \
command tool.", 46},
  {"ODBCConfig - Credits", 47},
  {"\
unixODBC consists of the following components\n\
\n\
- Driver Manager\n\
- GUI Data Manager\n\
- GUI Config\n\
- Several Drivers and Driver Config libs\n\
- Driver Code Template\n\
- Driver Config Code Template\n\
- ODBCINST lib\n\
- odbcinst (command line tool for install scripts)\n\
- INI lib\n\
- LOG lib\n\
- LST lib\n\
- TRE lib\n\
- SQI lib\n\
- isql (command line tool for SQL)\n\
\n\
All code is released under GPL and the LGPL license.\n", 48},
  {"gODBCConfig - New Driver", 49},
  {"FileUsage", 50},
  {"Setup", 51},
  {"gODBCConfig - Configure Driver", 52},
  {"gODBCConfig - Add DSN", 53},
  {"Select the DRIVER to use or Add a new one", 54},
  {"Could not load %s", 55},
  {"Could not write to (%s)", 56},
  {"Select a driver to remove", 57},
  {"Select a driver to configure", 58},
  {"Enter a DSN name", 59},
  {"Could not construct a property list for (%s)", 60},
  {"Select a driver to Use", 61},
  {"DSN", 62},
  {"Select a DSN to configure", 63},
  {"Unable to find a Driver line for this entry", 64},
  {"Select File", 65},
  {"Select a DSN to Remove", 66},
  {"Could not write property list for (%s)", 67},
  {"Could not write to %s", 68},
  {"Couldn't find pixmap file: %s", 69},
  {"Couldn't create pixmap from file: %s", 70},
};

int _msg_tbl_length = 70;
