/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "REDIforms.h"

FD_readistatus *create_form_readistatus(void)
{
  FL_OBJECT *obj;
  FD_readistatus *fdui = (FD_readistatus *) fl_calloc(1, sizeof(*fdui));

  fdui->readistatus = fl_bgn_form(FL_NO_BOX, 850, 460);
  obj = fl_add_box(FL_UP_BOX,0,0,850,460,"");
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,10,100,280,10,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,290,10,10,440,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,redinoneCB,0);
  fdui->plause_pie = obj = fl_add_chart(FL_BAR_CHART,770,400,70,50,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_button(FL_NORMAL_BUTTON,760,10,80,30,"Exit");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,REDIexitCB,0);
  fdui->redi_select[0] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,20,40,80,20,"ICBM");
    fl_set_object_color(obj,FL_GREEN,FL_GREEN);
    fl_set_object_callback(obj,rediselectCB,0);
  fdui->redi_select[1] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,110,40,80,20,"SLBM");
    fl_set_object_color(obj,FL_GREEN,FL_GREEN);
    fl_set_object_callback(obj,rediselectCB,1);
  fdui->redi_select[2] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,200,40,80,20,"BOMBER");
    fl_set_object_color(obj,FL_GREEN,FL_GREEN);
    fl_set_object_callback(obj,rediselectCB,2);
  fdui->redi_select[3] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,20,70,80,20,"TANKER");
    fl_set_object_color(obj,FL_YELLOW,FL_YELLOW);
    fl_set_object_callback(obj,rediselectCB,3);
  fdui->redi_select[4] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,110,70,80,20,"RECCE");
    fl_set_object_color(obj,FL_RED,FL_RED);
    fl_set_object_callback(obj,rediselectCB,4);
  fdui->redi_select[5] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,200,70,80,20,"C2");
    fl_set_object_color(obj,FL_GREEN,FL_GREEN);
    fl_set_object_callback(obj,rediselectCB,5);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,40,10,60,10,"> 90");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,110,10,60,10,"90 - 70");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_YELLOW,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_lightbutton(FL_PUSH_BUTTON,180,10,60,10,"< 70");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_RED,FL_COL1);
    fl_set_object_lsize(obj,FL_TINY_SIZE);
    fl_set_object_callback(obj,redinoneCB,0);
  fdui->site_browser = obj = fl_add_browser(FL_NORMAL_BROWSER,300,70,130,380,"Site Status");
    fl_set_object_color(obj,FL_COL1,FL_COL1);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
    fl_add_browser_line(obj, "FE Warren");
    fl_add_browser_line(obj, "Malmstrom");
    fl_add_browser_line(obj, "Minot");
    fl_add_browser_line(obj, "TOTAL");
  obj = fl_add_chart(FL_BAR_CHART,690,400,70,50,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_chart(FL_BAR_CHART,605,400,70,50,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_chart(FL_BAR_CHART,520,400,70,50,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_chart(FL_BAR_CHART,440,400,70,50,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
  obj = fl_add_positioner(FL_NORMAL_POSITIONER,430,10,10,440,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,10,380,280,20,"Inspection, Exercises, and Evaluation");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
  fdui->redi_status[51] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,400,70,20,"NSI");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,51);
  fdui->redi_status[52] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,420,70,20,"ORI");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,52);
  fdui->redi_status[53] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,70,400,70,20,"STPI");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,53);
  fdui->redi_status[54] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,70,420,70,20,"Eval");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,54);
  fdui->redi_status[55] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,130,400,70,20,"Polehat");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,55);
  fdui->redi_status[56] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,130,420,70,20,"B Bronze");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,56);
  fdui->redi_status[57] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,210,400,70,20,"G Archer");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,57);
  fdui->redi_status[58] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,210,420,70,20,"Fce/Fot&E");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,58);
  obj = fl_add_text(FL_NORMAL_TEXT,10,110,140,20,"Forces");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,150,110,140,20,"Forces & C4I");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,10,180,140,20,"Equipment");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,10,310,140,20,"Personnel");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
  obj = fl_add_text(FL_NORMAL_TEXT,150,180,140,20,"Sorts C-level");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
  fdui->redi_status[1] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,130,100,20,"Alert");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,1);
  fdui->redi_status[11] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,200,100,20,"Platform");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,11);
  fdui->redi_status[12] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,220,100,20,"Weapon");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,12);
  fdui->redi_status[13] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,240,100,20,"Sensor");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,13);
  fdui->redi_status[14] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,260,100,20,"Plan");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,14);
  fdui->redi_status[15] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,280,100,20,"Equipment");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,15);
  fdui->redi_status[21] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,330,100,20,"Crew");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,21);
  fdui->redi_status[22] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,10,350,100,20,"S Personnel");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,22);
  fdui->redi_status[31] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,130,100,20,"C4I");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,31);
  fdui->redi_status[32] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,150,100,20,"C4I Trans");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,32);
  fdui->redi_status[41] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,200,100,20,"E Equipment");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,41);
  fdui->redi_status[42] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,220,100,20,"S Equipment");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,42);
  fdui->redi_status[43] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,240,100,20,"Equip Cond");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,43);
  fdui->redi_status[44] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,260,100,20,"Personnel");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,44);
  fdui->redi_status[45] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,280,100,20,"E Personnel");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,45);
  fdui->redi_status[46] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,300,100,20,"Training");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,46);
  fdui->redi_status[47] = obj = fl_add_lightbutton(FL_PUSH_BUTTON,150,320,100,20,"Commander's Assess");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_GREEN,FL_COL1);
    fl_set_object_callback(obj,redistatusCB,47);
  fdui->redi_sites = obj = fl_add_text(FL_NORMAL_TEXT,300,30,130,20,"ICBM");
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_callback(obj,redinoneCB,0);
  fdui->redi_3D = obj = fl_add_pixmap(FL_NORMAL_PIXMAP,440,70,400,320,"");
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_callback(obj,redinoneCB,0);
    fl_set_pixmap_file(obj, "../BitMaps/readi3D.xpm");
  fl_end_form();

  fdui->readistatus->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

