// nostateobj.H header file

#ifndef nostobj_object
#define nostobj_object

#include "simobj.H"

/************************************************************************
*	nostateobj object - nostate object for stateless computations	*
************************************************************************/
class C_NOSTATEOBJ : public C_SIMOBJ {

  private:

  protected:

  public:

    C_NOSTATEOBJ();

};


#endif
