/* Don't edit this file, it is produced automaticaly from UnifiedList.txt */
#ifndef _UNIFIED_H
#define _UNIFIED_H
# define _Sabstract _UnifiedName(62)
# define _Sauthor_name _UnifiedName(1003)
# define _Sauthor_name_conference _UnifiedName(1006)
# define _Sauthor_name_corporate _UnifiedName(1005)
# define _Sauthor_name_personal _UnifiedName(1004)
# define _Sauthor_title _UnifiedName(1000)
# define _Sbody _UnifiedName(1010)
# define _Scinematagrapher _UnifiedName(-9000)
# define _Sclassification_bliss _UnifiedName(15)
# define _Sclassification_dewey _UnifiedName(13)
# define _Sclassification_lc _UnifiedName(16)
# define _Sclassification_mos _UnifiedName(19)
# define _Sclassification_nal _UnifiedName(18)
# define _Sclassification_nlm _UnifiedName(17)
# define _Sclassification_udc _UnifiedName(14)
# define _Sclassification_govt_publication _UnifiedName(50)
# define _Sclassification_local _UnifiedName(20)
# define _Scode_geographic_area _UnifiedName(55)
# define _Scode_institution _UnifiedName(56)
# define _Scode_language _UnifiedName(54)
# define _Scode_microform_generation _UnifiedName(61)
# define _Scommentary _UnifiedName(-9001)
# define _Sconcept_reference _UnifiedName(1015)
# define _Sconcept_text _UnifiedName(1014)
# define _Scontent_type _UnifiedName(1034)
# define _Sdate _UnifiedName(30)
# define _Sdate_acquisition _UnifiedName(32)
# define _Sdate_publication _UnifiedName(31)
# define _Sdirector _UnifiedName(-9002)
# define _Sdistributor _UnifiedName(-9003)
# define _Seditor _UnifiedName(1020)
# define _Sfee_gema _UnifiedName(-9004)
# define _Sfee_purchase _UnifiedName(-9005)
# define _Sfee_rent _UnifiedName(-9006)
# define _Sgeographic_class _UnifiedName(1022)
# define _Sheadline _UnifiedName(-9007)
# define _Sidentifier_coden _UnifiedName(60)
# define _Sidentifier_isbn _UnifiedName(7)
# define _Sidentifier_issn _UnifiedName(8)
# define _Sidentifier_legal_deposit _UnifiedName(49)
# define _Sidentifier_local_call _UnifiedName(53)
# define _Sidentifier_national_bibliography _UnifiedName(48)
# define _Sidentifier_publisher_for_music _UnifiedName(51)
# define _Sidentifier_standard _UnifiedName(1007)
# define _Sidentifier_url _UnifiedName(-9008)
# define _Slocus _UnifiedName(-9009)
# define _Smap_scale _UnifiedName(1024)
# define _Smaterial_type _UnifiedName(1031)
# define _Smedia_descriptor _UnifiedName(-9010)
# define _Smedia_length _UnifiedName(-9011)
# define _Smusic_key _UnifiedName(1025)
# define _Sname _UnifiedName(1002)
# define _Sname_conference _UnifiedName(3)
# define _Sname_corporate _UnifiedName(2)
# define _Sname_geographic _UnifiedName(58)
# define _Sname_geographic_place_publication _UnifiedName(59)
# define _Sname_personal _UnifiedName(1)
# define _Snote _UnifiedName(63)
# define _Snucleic_acid _UnifiedName(-9012)
# define _Snucleic_acid_count _UnifiedName(-9013)
# define _Snumber_bnb _UnifiedName(10)
# define _Snumber_bnf _UnifiedName(11)
# define _Snumber_db _UnifiedName(52)
# define _Snumber_lc _UnifiedName(9)
# define _Snumber_local _UnifiedName(12)
# define _Spage_numbers _UnifiedName(-9014)
# define _Sproducer _UnifiedName(-9015)
# define _Spublisher _UnifiedName(1018)
# define _Srating _UnifiedName(-9016)
# define _Srecord_source _UnifiedName(1019)
# define _Srecord_ctime _UnifiedName(-9017)
# define _Srecord_mtime _UnifiedName(-9018)
# define _Srecord_author _UnifiedName(-9019)
# define _Srelated_periodical _UnifiedName(1026)
# define _Sreport_number _UnifiedName(1027)
# define _Sstock_number _UnifiedName(1028)
# define _Ssequence _UnifiedName(-9020)
# define _Ssequence_length _UnifiedName(-9021)
# define _Ssubject _UnifiedName(21)
# define _Ssubject_bdi _UnifiedName(23)
# define _Ssubject_inspec _UnifiedName(24)
# define _Ssubject_lc _UnifiedName(27)
# define _Ssubject_lc_children _UnifiedName(1008)
# define _Ssubject_mesh _UnifiedName(25)
# define _Ssubject_pa _UnifiedName(26)
# define _Ssubject_precis _UnifiedName(45)
# define _Ssubject_rameau _UnifiedName(22)
# define _Ssubject_rswk _UnifiedName(46)
# define _Ssubject_rvm _UnifiedName(28)
# define _Ssubject_local _UnifiedName(29)
# define _Ssubject_name_personal _UnifiedName(1009)
# define _Ssubject_subdivision _UnifiedName(47)
# define _Sthematic_number _UnifiedName(1030)
# define _Stitle _UnifiedName(4)
# define _Stitle_abbreviated _UnifiedName(43)
# define _Stitle_added_title_page _UnifiedName(37)
# define _Stitle_caption _UnifiedName(38)
# define _Stitle_collective _UnifiedName(34)
# define _Stitle_cover _UnifiedName(36)
# define _Stitle_expanded _UnifiedName(44)
# define _Stitle_former _UnifiedName(42)
# define _Stitle_key _UnifiedName(33)
# define _Stitle_other_variant _UnifiedName(41)
# define _Stitle_parallel _UnifiedName(35)
# define _Stitle_running _UnifiedName(39)
# define _Stitle_series _UnifiedName(5)
# define _Stitle_spine _UnifiedName(40)
# define _Stitle_uniform _UnifiedName(6)
# define _Sother_fields _UnifiedName(-9022)



extern 
#ifdef __cplusplus
  "C" {
#endif
const char *_UnifiedName(int);
#ifdef __cplusplus
};
#endif
#endif
