#!/bin/sh

#Work in progress - not yet working! (arjen)

tmp=/tmp/temp-pic.pnm

all="myaccess_odbc mydsn_example mydsn_test_fail mydsn
myaccess mydsn_icon mydsn_test_success myflowchart
myarchitecture mydsn_setup mydsn_trace"

new=""

set -x
cd Images

# for c in $all; do cp empty.png $c.pdf; done; exit

for c in $new
do
  # For HTML version
#  giftopnm ../Raw-Flags/$c.gif | \
#  pnmscale -xsize 30 > $tmp
#  pnmpaste $tmp 1 1 ../Images/flag-background.pnm > $c.pnm
#  rm -f $tmp
  # For web version
#  ppmtogif $c.pnm > $c.gif
  # or cjpeg -optimize -quality 70 -outfile $c.jpg
  # For PDF version (this coredumps. use empty file until fixed)
  # pnmtopng -verbose $c.pnm > $c.png
  cp ../Images/empty.png $c.pdf
  # For TeX version
  giftopnm ../Raw-Flags/$c.gif | \
   pnmscale -xsize 30 | \
   pnmtops -noturn > $c.eps
  # For text version
  echo -n "" > $c.txt
done
