// freeoms.H header file

#ifndef freeoms_object
#define freeoms_object

#include "free_list.H"
#include "freetypes.H"

/************************************************************************
*	freeoms object 							*
************************************************************************/
class C_FREEOMS : public C_FREE_LIST {

  private:

  protected:

  public:

    C_FREEOMS();

};


#endif
