// ranobj.H header file

#ifndef ranobj_object
#define ranobj_object

#include "mover.H"

/************************************************************************
*	ranobj object 							*
************************************************************************/
class C_RANOBJ : public C_MOVER {

  private:

  protected:

  public:

    C_RANOBJ();
    void init_ranobj(C_BASETYPE *rantype);

};


#endif
