/**********************************************************************
  asf_misc.H

  Things specific to the ASF, such as the conversion function get_type
  which takes a <type,id> pair  and returns a character string;

  -- 06/29/93: created by Y. Tung

*********************************************************************/

#ifndef ASF_MISC
#define ASF_MISC                            "asf_miscclass"

#include "get_type.C"

#endif

