-Case_ID
-Hypothesis
-Belief
-Disbelief
+Who_(People_&_Groups)
>Report_Org
>Report_Type
>Report_Class
>Report_Name
>Enemy_IP
>Enemy_Port
>Enemy_Desc
>Enemy_Name
>Dest_IP
>Dest_Port
>Dest_Desc
>Dest_Name
+Why
>Strat
>Ops
>Tact
>?1
+Where
>Region
>Nation
>Local
>City
>Structure
>Latitude
>Longitude
>Altitude
+How
>Means
>Vuln
>Target
+What
>Action
>Result
>Data_Seq_#
>Expected
+Hedges
>How_Big
>How_Sure
>Urgency
>Flags
>?2
>?3
>?4
>?5
+When
>Start_Time
>End_Time
>Duration
>?6
-Evidence_Type
-Info_ID
-Prepared
-Prep_Date
