-Case_ID
-Hypothesis
-Belief
-Disbelief
+Who_(People_&_Groups)
>Report_Org
>Report_Affil
>Report_Desc
>Report_Name
>Enemy_Org
>Enemy_Affil
>Enemy_Desc
>Enemy_Name
>Ally_Org
>Ally_Affil
>Ally_Desc
>Ally_Name
+3rd_Party
>Party_Org
>Party_Affil
>Party_Desc
>Party_Name
+Where_(Location)
>Region
>Nation
>Locale
>City
>Structure
>Latitude
>Longitud
>Altitude
+What_(Activities_&_Events)
>Subject
>Action
>Objective
+Why_(Goal/Intent/Purpose)
>Strategic
>Operation
>Tactical
>Task
+How_(Means_&_Methods)
>Method
>Desc_1
>Desc_2
>Desc_3
>Casualties
>Injuries
>Cost
>Adjective
+When_(Time_&_Duration)
>Start_Time
>End_Time
>Duration
>Time_Frame
-Evidence_Type
-Description
-Prepared
-Prep_Date
