-Case_ID
-Hypothesis
-Belief
-Disbelief
+?Undefined?
>Report_Org
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
+?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
+?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
+?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
+?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
+?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
+Report_Org
>?Undefined?
>?Undefined?
>?Undefined?
>?Undefined?
-Evidence_Type
-Info_ID
-Prepared
-Prep-Date
