-Case_ID
-Hypothesis
-Belief
-Disbelief
+Who
>Author_Name
>Author_Affil
>Reporter_Name
>Reporter_Affil
>Expert_Name
>Expert_Affil
>Interested_Party_Name
>Interested_Party_Affil
+What
>Tech_Desc
>Domain
>Keyword_1
>Keyword_2
>Keyword_3
>Keyword_4
>Keyword_5
+Why
>Purpose
>Problem
>Target_Audience
+When
>Dev_Start
>Dev_End
>Availability
+Where
>Country
>State
>City
>Extent
+How
>Representation
>Algorithm
>Utility
>Benefits
>Drawbacks
>Importance
>Dev_Stage
>Prevalence
>Acceptance
>Interface_Style
>Product
>Cost
>Language
>OS
?
?
?
?
?
?
?
?
?
