-Case_ID
-Hypothesis
-Belief
-Disbelief
+Target_Information
>Function
>Range
>Frequency
>Assoc._weapon_sys.
>Recognition
>System_Designation
>Type
>Mission
>System_Developer
>Missile_Developer
>Serial_Production
>System_Composition
+Performances
>Probability_of_Kill_(non-manuevering)
>Probability_of_Kill_(manuevering)
>Tracking_Ability
>Length
+Where_(Location)
>Target_Country
>Target_Local
>Target_City
>Target_Address
>Target_Latitude
>Target_Longitude
>Target_Altitude
>Target_Extent
+Performances
>Diameter
>Wing_Span
>Max_Speed
+Performances
>Launch_Weight
>Max_Effective_range
>Min_effective_range
>Max_effective_Altitude
+Performance
>Min_effective_Altitude
>Propulsion
>Warhead
>Reload_Time
>Time_to_Deployment
>Reaction_Time
>Op._Temp.
>Performance_Upgrades
+When_(Time_&_Duration)
>Evidence_Time
>Threat_Duration
>Last_Event
>Time_Frame
-Evidence_Type
-Info-ID
-Prepared
-Prep-Date
