#!/bin/tcsh -x
../bin/gm g1a g1b
../bin/gm g2a g2b
../bin/gm g2a g2c
../bin/gm g2a g2d
../bin/gm g3a g3b
../bin/gm g3a g3c
../bin/gm g3a g3d
../bin/gm g3a g3e
../bin/gm g3a g3f
../bin/gm g3a g3g
../bin/gm g3a g3h
../bin/gm g3a g3i
../bin/gm g3a g3j
../bin/gm g4a g4b
../bin/gm g4a g4c
../bin/gm g5a g5b
../bin/gm overlap1.g overlap2.g
../bin/gm overlap1.g overlap3.g
