/*
 *----------------------------------------------------------------------------
 *<
 * file:		rsd_geom.h
 *
 * abstract:	binary geometry file command codes
 *
 * revision:	1	initial implementation		7/87		S. Gray
 *
 * date:		July, 1987
 *
 * author:		Steve Gray
 *
 * notes:		
 *>
 *----------------------------------------------------------------------------
 */

#define	RSD_POLY		1
#define	RSD_COLOR		2
#define	RSD_RECT		3
#define	RSD_RECTF		4
#define	RSD_MOVE		5
#define	RSD_DRAW		6
#define	RSD_CMOV		7
#define	RSD_CHARSTR		8
#define	RSD_CLEAR		9
#define	RSD_PATTERN		10
#define	RSD_MAPCOLOR	11
#define	RSD_PNT			12

