# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/unixODBC
pkglibdir = $(libdir)/unixODBC
pkgincludedir = $(includedir)/unixODBC

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = @target_alias@
target_triplet = @target@
AS = @AS@
AWK = gawk
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
ECHO = echo
EXEEXT = 
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = @GMSGFMT@
ICONV_CHAR_ENCODING = auto-search
ICONV_UNICODE_ENCODING = auto-search
IDL = @IDL@
INCLTDL = -I${top_srcdir}/libltdl
KDE_EXTRA_RPATH = @KDE_EXTRA_RPATH@
KDE_INCLUDES = @KDE_INCLUDES@
KDE_LDFLAGS = @KDE_LDFLAGS@
KDE_RPATH = @KDE_RPATH@
KDE_USE_FINAL_FALSE = @KDE_USE_FINAL_FALSE@
KDE_USE_FINAL_TRUE = @KDE_USE_FINAL_TRUE@
LEX = flex
LFLAGS =  -i
LIBADD_CRYPT = -lcrypt
LIBADD_DL = 
LIBCOMPAT = @LIBCOMPAT@
LIBCRYPT = @LIBCRYPT@
LIBDL = @LIBDL@
LIBICONV = 
LIBJPEG = @LIBJPEG@
LIBLTDL = ${top_builddir}/libltdl/libltdlc.la
LIBMICO = @LIBMICO@
LIBNSL = -lnsl
LIBPNG = 
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBSOCKET = 
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = @LIBUCB@
LIBZ = 
LIB_KAB = @LIB_KAB@
LIB_KDECORE = @LIB_KDECORE@
LIB_KDEUI = @LIB_KDEUI@
LIB_KFILE = @LIB_KFILE@
LIB_KFM = @LIB_KFM@
LIB_KFORMULA = @LIB_KFORMULA@
LIB_KHTML = @LIB_KHTML@
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = @LIB_KIO@
LIB_MEDIATOOL = @LIB_MEDIATOOL@
LIB_QT = -lqt $(LIBPNG) -lXext $(LIB_X11)
LIB_SMB = @LIB_SMB@
LIB_VERSION = 1:0:0
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = 
MSGFMT = @MSGFMT@
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = unixODBC
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PTH_CFLAGS = 
PTH_CPPFLAGS = 
PTH_LDFLAGS = 
PTH_LIBS = 
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = 
QT_LDFLAGS = 
RANLIB = ranlib
READLINE = -lreadline -lcurses
SHLIBEXT = .so
STRIP = strip
TOPSUBDIRS = @TOPSUBDIRS@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_NLS = @USE_NLS@
VERSION = 2.2.3
XGETTEXT = @XGETTEXT@
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = @X_EXTRA_LIBS@
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
YACC = bison -y
all_includes = @all_includes@
all_libraries = @all_libraries@
idldir = @idldir@
kde_appsdir = @kde_appsdir@
kde_bindir = @kde_bindir@
kde_cgidir = @kde_cgidir@
kde_confdir = @kde_confdir@
kde_datadir = @kde_datadir@
kde_htmldir = @kde_htmldir@
kde_icondir = @kde_icondir@
kde_includes = @kde_includes@
kde_libraries = @kde_libraries@
kde_locale = @kde_locale@
kde_mimedir = @kde_mimedir@
kde_minidir = @kde_minidir@
kde_servicesdir = @kde_servicesdir@
kde_servicetypesdir = @kde_servicetypesdir@
kde_sounddir = @kde_sounddir@
kde_toolbardir = @kde_toolbardir@
kde_wallpaperdir = @kde_wallpaperdir@
micodir = @micodir@
msql_headers = 
msql_libraries = 
qt_includes = 
qt_libraries = 
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

libodbcinstQ_la_LDFLAGS =          -version-info 1:0:0 		-export-dynamic 		-export-symbols odbcinstQ.exp 	    -module


#lib_LTLIBRARIES = libodbcinstQ.la

#INCLUDES = -I../include      -DSYSTEM_FILE_PATH=\"${prefix}/etc\" -DDEFLIB_PATH=\"${exec_prefix}/lib\" $(INCLTDL)

#libodbcinstQ_la_LIBADD = -L/usr/X11R6/lib 	 	 	-lqt $(LIBPNG) -lXext $(LIB_X11) 	../odbcinst/libodbcinst.la 	../extras/libodbcextraslc.la 	../DriverManager/libodbc.la 

#libodbcinstQ_la_DEPENDANCIES = 	../odbcinst/libodbcinst.la 	../extras/libodbcextraslc.la 	../DriverManager/libodbc.la

#libodbcinstQ_la_SOURCES = 	CAbout.cpp 	CCredits.cpp 	CDLL.cpp 	CDSNList.cpp 	CDriverPrompt.cpp 	CDrivers.cpp 	CFileDSN.cpp 	CFileList.cpp 	CFileSelector.cpp 	CODBCConfig.cpp 	CProperties.cpp 	CPropertiesFrame.cpp 	CSplashDialog.cpp 	CStatDetails.cpp 	CStatSummary.cpp 	CStats.cpp 	CSystemDSN.cpp 	CTracing.cpp 	CUserDSN.cpp 	mCAbout.cpp 	mCCredits.cpp 	mCDSNList.cpp 	mCDriverPrompt.cpp 	mCDrivers.cpp 	mCFileDSN.cpp 	mCFileList.cpp 	mCFileSelector.cpp 	mCODBCConfig.cpp 	mCProperties.cpp 	mCPropertiesFrame.cpp 	mCStatDetails.cpp 	mCStatSummary.cpp 	mCStats.cpp 	mCSystemDSN.cpp 	mCTracing.cpp 	mCUserDSN.cpp 	SQLManageDataSources.cpp

EXTRA_DIST =  	CAbout.h 	CTracing.h 	CStats.h 	CStatSummary.h 	CSplashDialog.h 	CStatDetails.h 	CDLL.h 	CDSNList.h 	CFileList.h 	CDriverPrompt.h 	CDrivers.h 	CFileSelector.h 	CODBCConfig.h 	CPropertiesFrame.h 	CProperties.h 	CSystemDSN.h 	CFileDSN.h 	CUserDSN.h 	CCredits.h 	Splash.xpm 	ODBC.xpm 	computer.xpm 	driver.xpm 	info.xpm 	checkOk.xpm 	checkCancel.xpm 	person.xpm 	server.xpm 	smallLinuxODBC.xpm 	ODBC.xpm 	Canada.xpm 	GreatBritain.xpm 	trace.xpm 	NoFlag.xpm 	odbcinstQ.exp

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS =  -DPACKAGE=\"unixODBC\" -DVERSION=\"2.2.3\" -DYYTEXT_POINTER=1 -DHAVE_SYS_SEM_H=1 -DHAVE_DLFCN_H=1 -DLTDL_SHLIB_EXT=\".so\" -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_LIBCRYPT=1 -DHAVE_LIBM=1 -DHAVE_READLINE_HISTORY_H=1 -DHAVE_READLINE=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_SYS_TIME_H=1 -DSIZEOF_LONG=4 -DHAVE_LONG_LONG=1 -DHAVE_STRCASECMP=1 -DHAVE_STRNCASECMP=1 -DHAVE_VSNPRINTF=1 -DHAVE_STRTOL=1 -DHAVE_LIBPTHREAD=1 -D_REENTRANT=1 -DHAVE_LOCALTIME_R=1 -DHAVE_FTOK=1 -DHAVE_SEMGET=1 -DHAVE_SHMGET=1 -DHAVE_SEMOP=1 -DHAVE_SNPRINTF=1 -DNEED_SEMUNDO_UNION=1 -DCOLLECT_STATS=1 -DSTDC_HEADERS=1 -DHAVE_MALLOC_H=1 -DHAVE_UNISTD_H=1 -DHAVE_PWD_H=1 -DHAVE_CRYPT_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STRINGS_H=1 -DHAVE_STRING_H=1 -DHAVE_LOCALE_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_SEM_H=1 -DHAVE_DIRENT_H=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_VPRINTF=1 -DHAVE_PUTENV=1 -DHAVE_SOCKET=1 -DHAVE_STRDUP=1 -DHAVE_STRSTR=1 -DHAVE_SETENV=1  -I. -I$(srcdir) 
CPPFLAGS = 
LDFLAGS = 
LIBS = -lm  -lpthread
#libodbcinstQ_la_DEPENDENCIES =  ../odbcinst/libodbcinst.la \
#../extras/libodbcextraslc.la ../DriverManager/libodbc.la
#libodbcinstQ_la_OBJECTS =  CAbout.lo CCredits.lo CDLL.lo \
#CDSNList.lo CDriverPrompt.lo CDrivers.lo CFileDSN.lo \
#CFileList.lo CFileSelector.lo CODBCConfig.lo CProperties.lo \
#CPropertiesFrame.lo CSplashDialog.lo CStatDetails.lo \
#CStatSummary.lo CStats.lo CSystemDSN.lo CTracing.lo \
#CUserDSN.lo mCAbout.lo mCCredits.lo mCDSNList.lo \
#mCDriverPrompt.lo mCDrivers.lo mCFileDSN.lo mCFileList.lo \
#mCFileSelector.lo mCODBCConfig.lo mCProperties.lo \
#mCPropertiesFrame.lo mCStatDetails.lo mCStatSummary.lo \
#mCStats.lo mCSystemDSN.lo mCTracing.lo mCUserDSN.lo \
#SQLManageDataSources.lo
CXXFLAGS = -g -O2
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  README INSTALL Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libodbcinstQ_la_SOURCES)
OBJECTS = $(libodbcinstQ_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps odbcinstQ/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libodbcinstQ.la: $(libodbcinstQ_la_OBJECTS) $(libodbcinstQ_la_DEPENDENCIES)
	$(CXXLINK) -rpath $(libdir) $(libodbcinstQ_la_LDFLAGS) $(libodbcinstQ_la_OBJECTS) $(libodbcinstQ_la_LIBADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = odbcinstQ

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
CAbout.lo CAbout.o : CAbout.cpp CAbout.h CCredits.h info.xpm
CCredits.lo CCredits.o : CCredits.cpp CCredits.h NoFlag.xpm Canada.xpm \
	GreatBritain.xpm
CDLL.lo CDLL.o : CDLL.cpp ../libltdl/ltdl.h CDLL.h
CDriverPrompt.lo CDriverPrompt.o : CDriverPrompt.cpp CDriverPrompt.h \
	CDrivers.h ../include/ini.h ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/log.h ../include/lst.h \
	../include/odbcinst.h ../include/sql.h ../include/sqltypes.h \
	CPropertiesFrame.h CProperties.h CFileSelector.h
CDrivers.lo CDrivers.o : CDrivers.cpp CDrivers.h ../include/ini.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h CPropertiesFrame.h CProperties.h \
	CFileSelector.h driver.xpm
CDSNList.lo CDSNList.o : CDSNList.cpp CDSNList.h ../include/ini.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h CDriverPrompt.h CDrivers.h \
	CPropertiesFrame.h CProperties.h CFileSelector.h CDLL.h
CFileDSN.lo CFileDSN.o : CFileDSN.cpp CFileDSN.h CFileList.h \
	../include/ini.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CDriverPrompt.h \
	CDrivers.h CPropertiesFrame.h CProperties.h CFileSelector.h \
	CDLL.h server.xpm
CFileList.lo CFileList.o : CFileList.cpp CFileList.h ../include/ini.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h CDriverPrompt.h CDrivers.h \
	CPropertiesFrame.h CProperties.h CFileSelector.h CDLL.h
CFileSelector.lo CFileSelector.o : CFileSelector.cpp CFileSelector.h
CODBCConfig.lo CODBCConfig.o : CODBCConfig.cpp CODBCConfig.h CUserDSN.h \
	CDSNList.h ../include/ini.h ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/log.h ../include/lst.h \
	../include/odbcinst.h ../include/sql.h ../include/sqltypes.h \
	CDriverPrompt.h CDrivers.h CPropertiesFrame.h CProperties.h \
	CFileSelector.h CDLL.h CSystemDSN.h CFileDSN.h CFileList.h \
	CAbout.h CCredits.h CTracing.h CStats.h CStatSummary.h \
	../include/uodbc_stats.h CStatDetails.h ODBC.xpm
CPropertiesFrame.lo CPropertiesFrame.o : CPropertiesFrame.cpp \
	CPropertiesFrame.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/ini.h ../include/log.h ../include/lst.h \
	../include/odbcinst.h ../include/sql.h ../include/sqltypes.h \
	CProperties.h CFileSelector.h
CProperties.lo CProperties.o : CProperties.cpp CProperties.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CFileSelector.h \
	checkOk.xpm checkCancel.xpm
CSplashDialog.lo CSplashDialog.o : CSplashDialog.cpp CSplashDialog.h \
	Splash.xpm
CStatDetails.lo CStatDetails.o : CStatDetails.cpp CStatDetails.h \
	../include/uodbc_stats.h info.xpm
CStats.lo CStats.o : CStats.cpp CStats.h CStatSummary.h \
	../include/uodbc_stats.h CStatDetails.h info.xpm
CStatSummary.lo CStatSummary.o : CStatSummary.cpp CStatSummary.h \
	../include/uodbc_stats.h info.xpm
CSystemDSN.lo CSystemDSN.o : CSystemDSN.cpp CSystemDSN.h CDSNList.h \
	../include/ini.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CDriverPrompt.h \
	CDrivers.h CPropertiesFrame.h CProperties.h CFileSelector.h \
	CDLL.h server.xpm
CTracing.lo CTracing.o : CTracing.cpp CTracing.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CFileSelector.h \
	trace.xpm
CUserDSN.lo CUserDSN.o : CUserDSN.cpp CUserDSN.h CDSNList.h \
	../include/ini.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CDriverPrompt.h \
	CDrivers.h CPropertiesFrame.h CProperties.h CFileSelector.h \
	CDLL.h person.xpm
mCAbout.lo mCAbout.o : mCAbout.cpp CAbout.h CCredits.h
mCCredits.lo mCCredits.o : mCCredits.cpp CCredits.h
mCDriverPrompt.lo mCDriverPrompt.o : mCDriverPrompt.cpp CDriverPrompt.h \
	CDrivers.h ../include/ini.h ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/log.h ../include/lst.h \
	../include/odbcinst.h ../include/sql.h ../include/sqltypes.h \
	CPropertiesFrame.h CProperties.h CFileSelector.h
mCDrivers.lo mCDrivers.o : mCDrivers.cpp CDrivers.h ../include/ini.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h CPropertiesFrame.h CProperties.h \
	CFileSelector.h
mCDSNList.lo mCDSNList.o : mCDSNList.cpp CDSNList.h ../include/ini.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h CDriverPrompt.h CDrivers.h \
	CPropertiesFrame.h CProperties.h CFileSelector.h CDLL.h
mCFileDSN.lo mCFileDSN.o : mCFileDSN.cpp CFileDSN.h CFileList.h \
	../include/ini.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CDriverPrompt.h \
	CDrivers.h CPropertiesFrame.h CProperties.h CFileSelector.h \
	CDLL.h
mCFileList.lo mCFileList.o : mCFileList.cpp CFileList.h ../include/ini.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h CDriverPrompt.h CDrivers.h \
	CPropertiesFrame.h CProperties.h CFileSelector.h CDLL.h
mCFileSelector.lo mCFileSelector.o : mCFileSelector.cpp CFileSelector.h
mCODBCConfig.lo mCODBCConfig.o : mCODBCConfig.cpp CODBCConfig.h \
	CUserDSN.h CDSNList.h ../include/ini.h ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/log.h ../include/lst.h \
	../include/odbcinst.h ../include/sql.h ../include/sqltypes.h \
	CDriverPrompt.h CDrivers.h CPropertiesFrame.h CProperties.h \
	CFileSelector.h CDLL.h CSystemDSN.h CFileDSN.h CFileList.h \
	CAbout.h CCredits.h CTracing.h CStats.h CStatSummary.h \
	../include/uodbc_stats.h CStatDetails.h
mCPropertiesFrame.lo mCPropertiesFrame.o : mCPropertiesFrame.cpp \
	CPropertiesFrame.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/ini.h ../include/log.h ../include/lst.h \
	../include/odbcinst.h ../include/sql.h ../include/sqltypes.h \
	CProperties.h CFileSelector.h
mCProperties.lo mCProperties.o : mCProperties.cpp CProperties.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CFileSelector.h
mCStatDetails.lo mCStatDetails.o : mCStatDetails.cpp CStatDetails.h \
	../include/uodbc_stats.h
mCStats.lo mCStats.o : mCStats.cpp CStats.h CStatSummary.h \
	../include/uodbc_stats.h CStatDetails.h
mCStatSummary.lo mCStatSummary.o : mCStatSummary.cpp CStatSummary.h \
	../include/uodbc_stats.h
mCSystemDSN.lo mCSystemDSN.o : mCSystemDSN.cpp CSystemDSN.h CDSNList.h \
	../include/ini.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CDriverPrompt.h \
	CDrivers.h CPropertiesFrame.h CProperties.h CFileSelector.h \
	CDLL.h
mCTracing.lo mCTracing.o : mCTracing.cpp CTracing.h \
	../include/odbcinstext.h ../libltdl/ltdl.h ../include/ini.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CFileSelector.h
mCUserDSN.lo mCUserDSN.o : mCUserDSN.cpp CUserDSN.h CDSNList.h \
	../include/ini.h ../include/odbcinstext.h ../libltdl/ltdl.h \
	../include/log.h ../include/lst.h ../include/odbcinst.h \
	../include/sql.h ../include/sqltypes.h CDriverPrompt.h \
	CDrivers.h CPropertiesFrame.h CProperties.h CFileSelector.h \
	CDLL.h
SQLManageDataSources.lo SQLManageDataSources.o : \
	SQLManageDataSources.cpp ../include/odbcinstext.h \
	../libltdl/ltdl.h ../include/ini.h ../include/log.h \
	../include/lst.h ../include/odbcinst.h ../include/sql.h \
	../include/sqltypes.h CODBCConfig.h CUserDSN.h CDSNList.h \
	CDriverPrompt.h CDrivers.h CPropertiesFrame.h CProperties.h \
	CFileSelector.h CDLL.h CSystemDSN.h CFileDSN.h CFileList.h \
	CAbout.h CCredits.h CTracing.h CStats.h CStatSummary.h \
	../include/uodbc_stats.h CStatDetails.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLTLIBRARIES
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLTLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


#mCDrivers.cpp: CDrivers.h
#	 CDrivers.h -o mCDrivers.cpp

#mCODBCConfig.cpp: CODBCConfig.h
#	 CODBCConfig.h -o mCODBCConfig.cpp

#mCSystemDSN.cpp: CSystemDSN.h
#	 CSystemDSN.h -o mCSystemDSN.cpp

#mCFileDSN.cpp: CFileDSN.h
#	 CFileDSN.h -o mCFileDSN.cpp

#mCUserDSN.cpp: CUserDSN.h
#	 CUserDSN.h -o mCUserDSN.cpp

#mCTracing.cpp: CTracing.h
#	 CTracing.h -o mCTracing.cpp

#mCStats.cpp: CStats.h
#	 CStats.h -o mCStats.cpp

#mCStatSummary.cpp: CStatSummary.h
#	 CStatSummary.h -o mCStatSummary.cpp

#mCStatDetails.cpp: CStatDetails.h
#	 CStatDetails.h -o mCStatDetails.cpp

#mCAbout.cpp: CAbout.h
#	 CAbout.h -o mCAbout.cpp

#mCDriverPrompt.cpp: CDriverPrompt.h
#	 CDriverPrompt.h -o mCDriverPrompt.cpp

#mCPropertiesFrame.cpp: CPropertiesFrame.h
#	 CPropertiesFrame.h -o mCPropertiesFrame.cpp

#mCProperties.cpp: CProperties.h
#	 CProperties.h -o mCProperties.cpp

#mCFileSelector.cpp: CFileSelector.h
#	 CFileSelector.h -o mCFileSelector.cpp

#mCDSNList.cpp: CDSNList.h
#	 CDSNList.h -o mCDSNList.cpp

#mCFileList.cpp: CFileList.h
#	 CFileList.h -o mCFileList.cpp

#mCCredits.cpp: CCredits.h
#	 CCredits.h -o mCCredits.cpp

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
