/**
 * IRoamAgent.java
 * <p>
 * @version 1.0
 * @author generated by igen 3.3 at Wed Nov 22 13:38:05 MST 2000
 */

public interface IRoamAgent
  {
  void addToItinerary( java.lang.String arg1, int arg2 );
  void atProgram();
  void dismiss();
  java.lang.String getUptime();
  void launch();
  }
