/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class UnixTimers */

#ifndef _Included_UnixTimers
#define _Included_UnixTimers

#pragma pack(4)

typedef struct ClassUnixTimers {
    double putime;
    double pstime;
    double cutime;
    double cstime;
    double elapsed;
} ClassUnixTimers;
HandleTo(UnixTimers);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
extern void UnixTimers_getTimes(struct HUnixTimers *);
#ifdef __cplusplus
}
#endif
#endif
