#
# /etc/cshrc
#
# System wide environment and startup programs for csh users
#
setenv JDK_HOME /usr/local/Java
setenv SWARMHOME /usr
#
setenv DREHOME $HOME
setenv SODIHOME $DREHOME/Sodi
setenv XERCESCROOT $DREHOME/Xerces
setenv PVM_ROOT $DREHOME/pvm3
setenv LEFTYPATH $DREHOME/gv1.7c/lib/lefty
setenv SPEEDES $DREHOME/Speedes
setenv PROXDIR $SPEEDES/demos/prox
setenv DATADIR $SODIHOME/RSD_Data
setenv MODELDIR $SODIHOME/Models
setenv BITMAPDIR $SODIHOME/BitMaps
setenv PARMDIR $SODIHOME/Run
setenv SNAPDIR /tmp/ScreenSnaps/
#
setenv SEARCH "Isearch -q -d JCSindexes/JCS_WO"
setenv GPDADOMAIN aoc
setenv SEARCHDIR JCSorders
#
#setenv SEARCH "Isearch -q -d IDSindexes/Snort"
#setenv GPDADOMAIN iow
#setenv SEARCHDIR IDSattack
#
setenv PATH /usr/gnat/bin:.:$HOME/bin:$SODIHOME/Bin:/usr/bin:/usr/local/VNC:/usr/local/bin:$XERCESCROOT/bin:/bin:/usr/X11R6/bin:/usr/local/Java/bin:/usr/java/jdk1.3.1_02/bin:$HOME/Voyager/bin:/usr/lib/gcc-lib/i386-redhat-linux/2.96
#
setenv LD_LIBRARY_PATH .:$SODIHOME/Lib:$SODIHOME/Lib/X11:$HOME/Protege-2000/plugins:$XERCESCROOT/lib:$HOME/Protege-2000:/usr/local/lib
#
setenv CLASSPATH .:$HOME/Voyager/lib/voyager.jar:$HOME/Voyager/lib/jgl3.1.0.jar:$HOME/Repast/lib/repast.jar:$HOME/Repast/lib/colt.jar:$HOME/Repast/lib/plot.jar
#
setenv LS_COLORS di=33
setenv TERM vt100
setenv HOSTNAME `/bin/hostname`
setenv DESKTOP  "158.114.53.175:0.0"
setenv CONF1014 "158.114.53.7:0.0"
setenv SAFEDAYS 10

setenv CXX g++
setenv EXTRA_CC_OPTIONS "-w -fpermissive  -I/usr/include/g++"

setenv PVM_ARCH LINUX

#setenv PLANREAL True
setenv PLANTEST True

if ($?prompt) then
  [ "$SHELL" = /bin/tcsh ]
  if ($status == 0) then
    set prompt='%n@%m %/: ' 
  else
    set prompt=\[`id -nu`@`hostname -s`\]$\ 
  endif
endif

#limit coredumpsize 1000

[ `id -gn` = `id -un` -a `id -u` -gt 14 ]
if $status then
	umask 022
else
	umask 002
endif

set history=1000

test -d /etc/profile.d
if ($status == 0) then
	set nonomatch
        foreach i ( /etc/profile.d/*.csh )
		test -f $i
		if ($status == 0) then
               		source $i
		endif
        end
	unset nonomatch
endif

alias es       emacs -fn 10x20
alias ls       ls -F --color
alias h        history
alias del      '/usr/local/bin/safedelete'
alias purge    safedelchk
alias vncstart 'vncserver :13 -dontdisconnect -alwaysshared'
alias vncstop  'vncserver -kill :13'
