/**
 * IHomeAgent.java
 * <p>
 * @version 1.0
 * @author generated by igen 3.3 at Wed Nov 22 13:37:19 MST 2000
 */

public interface IHomeAgent
  {
  void arrived();
  void dismiss();
  void putMessage( java.lang.String arg1 );
  }
