/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class UnixTimers */
/* SYMBOL: "UnixTimers/getTimes()V", Java_UnixTimers_getTimes_stub */
stack_item *Java_UnixTimers_getTimes_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void UnixTimers_getTimes(void *);
	(void) UnixTimers_getTimes(_P_[0].p);
	return _P_;
}
